DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, README.md
Updated line 783 of MSFT_xSQLServerSetup.psm1 to fix issue #21.
=> Fix for GetFirstItemPropertyValue to correctly handle registry keys with only one value. Fixes #21

DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1, DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.schema.mof, README.md
Changes to xSQLServerMemory
1. adding possibility to manager memory for multiply SQL instances. Changes were made to DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.schema.mof file, another key value was added - SQLInstanceName;
2. adding possibility to manage memory for multiply SQL instances. Changes were made to  DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1 fileL
-  ammended change to accept 0 MB as MinMemory value, predefined value was set to -1, as 0 in all _if_ checks as _$false_;
-  SQLInstanceName value became mandatory for this xSQLServerMemory functionality.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/49)
=> Changes to xSQLServerMemory part:

README.md
Automerge of PR #66 following 1.8 release incorrectly list xSQLServerReplication resource as part of 1.8 release, it should be in unreleased section.
Also fixed some line endings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/104)
=> readme.md: fixed unreleased section

DSCResources/xSQLServerAvailabilityGroupListener/xSQLServerAvailabilityGroupListener.psm1, README.md, Tests/Unit/Stubs/SMO.cs, Tests/Unit/Stubs/SQLPSStub.psm1, Tests/Unit/Stubs/SQLServerStub.psm1, Tests/Unit/xSQLServerAvailabilityGroupListener.Tests.ps1, Tests/Unit/xSQLServerEndpointPermission.Tests.ps1, Tests/Unit/xSQLServerEndpointState.Tests.ps1, Tests/Unit/xSQLServerPermission.Tests.ps1, en-US/xSQLServer.strings.psd1
* Added tests for resources
- xSQLServerPermission
- xSQLServerEndpointState
- xSQLServerEndpointPermission
- xSQLServerAvailabilityGroupListener
* Fixes in xSQLServerAvailabilityGroupListener
- In one case the Get-method did not report that DHCP was configured. 
- Now the resource will throw 'Not supported' when IP is changed between Static and DHCP.
- Fixed an issue where sometimes the listener wasn't removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/98)
=> Additional tests, and some fixes, related to AlwaysOn

DSCResources/MSFT_xSQLAOGroupEnsure/MSFT_xSQLAOGroupEnsure.psm1, README.md
I have been having an issue where I can't use the DSC modules to set up a named instance due to the New-ListenerADObject cmdlet in DSCResources/MSFT_xSQLAOGroupEnsure/MSFT_xSQLAOGroupEnsure.psm1 not accepting a named instance. Please let me know if there is anything else I need to do.
Superseding https://github.com/PowerShell/xSQLServer/pull/100 because I can't git.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/113)
=> Add parameters for New-ListenerADObject to use named SQL server and instance

Tests/Unit/Stubs/Write-ModuleStubFile.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/112)
=> Adding helper function for generating stubs file (fixes #111)

DSCResources/MSFT_xSQLServerLogin/MSFT_xSQLServerLogin.psm1, DSCResources/MSFT_xSQLServerLogin/MSFT_xSQLServerLogin.schema.mof, README.md, Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1, Tests/Unit/Stubs/SMO.cs
* Changes to xSQLServerLogin
- Fixed an issue when dropping logins (issue #105).
- Fixed an issue where it was not possible to add the same login to two instances on the same server (#31).
- Added unit test for the resource.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/106)
=> Changes to xSQLServerLogin (Fixes #105, #31)

DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1, Examples/Resources/xSQLServerDatabaseOwner/1-SetDatabaseOwner.ps1, README.md, Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1, xSQLServerHelper.psm1
- Added tests for resources
- xSQLServerDatabaseOwner
- Fixes and enhancements in xSQLServerDatabaseOwner 
- BREAKING CHANGE: Fixed so the same owner can now be added in one or more databases, and/or one or more instances. Now the parameters SQLServer and SQLInstanceName are mandatory.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/138)
=> BREAKING CHANGE: Changes to xSQLServerDatabaseOwner

DSCResources/MSFT_xSQLServerConfiguration/MSFT_xSQLServerConfiguration.psm1, DSCResources/MSFT_xSQLServerConfiguration/MSFT_xSQLServerConfiguration.schema.mof, README.md, Tests/Unit/MSFT_xSQLServerConfiguration.Tests.ps1, Tests/Unit/Stubs/SMO.cs, en-US/xSQLServer.strings.psd1, xSQLServerHelper.psm1
The xSQLServerConfiguration resource only supported changing configuration values for the local computer, not for clustered instances. This PR makes the following changes:
- Updated MOF and resource parameters to be consistent with other resources [**BREAKING CHANGE**]
- Now using helper function Connect-SQL
- Created new internal restart function that supports clusters
- Removed unused internal functions and objects
- Created unit tests per template (Issue #92)
- Updated README to reflect changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/143)
=> BREAKING CHANGE: Updated xSQLServerConfiguration to support clustered instances (Fixes #144)

DSCResources/MSFT_xSQLAOGroupJoin/MSFT_xSQLAOGroupJoin.psm1, README.md
There is a bug where the Availability Group name is not output in verbose logging. This is due to the wrong variable used ($AvailabilityGroup contains $null since it's never initialized). 
We should use variable $AvailabilityGroupName instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/192)
=> xSQLAOGroupJoin: Fix missing AG name in error message (fixes #194)

DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.psm1, DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.schema.mof, README.md, Tests/Unit/MSFT_xSQLServerRole.Tests.ps1, xSQLServerHelper.psm1
Fixes #151 and #165
Change xSQLServerRole Resource:
defaults to Ensure = Present
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/154)
=> Fix Ensure equal Present in xSQLServerRole resource (Fixes #151,#165)

CHANGELOG.md, CONTRIBUTING.md, Tests/Unit/MSFT_xSQLAOGroupEnsure.Tests.ps1, Tests/Unit/MSFT_xSQLServerAvailabilityGroupListener.Tests.ps1, Tests/Unit/MSFT_xSQLServerConfiguration.Tests.ps1, Tests/Unit/MSFT_xSQLServerDatabase.Tests.ps1, Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1, Tests/Unit/MSFT_xSQLServerEndpointPermission.Tests.ps1, Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1, Tests/Unit/MSFT_xSQLServerPermission.Tests.ps1, Tests/Unit/MSFT_xSQLServerRole.Tests.ps1, appveyor.yml
Improvements how tests are initiated in AppVeyor
- Removed previous workaround (issue #201) from unit tests.
- Changes in appveyor.yml so that SQL modules are removed before common test is run.
- Changes to CONTRIBUTING.md
- Removed the text about the need to do the workaround in tests (issue #201).
- Added a short descriptive text how tests works with AppVeyor.
- Added text explaining that a review only starts when all tests are passing.
Fixes #239
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/245)
=> Improvements how tests are initiated in AppVeyor

CHANGELOG.md, DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1
- The resource no longer uses Win32_Product WMI class when evaluating if SQL Server Management Studio is installed. See article [kb974524](https://support.microsoft.com/en-us/kb/974524) for more information.
This is one part to solve the issue #207.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/248)
=> xSQLServerSetup: Removed dependency of Win32_Product WMI class

CHANGELOG.md, DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1
- Now it uses CIM cmdlets to get information from WMI classes.
- Resolved all of the PSScriptAnalyzer warnings that was triggered in the common tests.
Fixes #267
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/269)
=> xSQLServerSetup: Now using CIM cmdlet. Also resolves PSSA warnings.

CHANGELOG.md, DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.schema.mof, README.md, Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1
- Changes to the helper function Copy-ItemWithRoboCopy
- Robocopy is now started using Start-Process and the error handling has been improved.
- Robocopy now removes files at the destination path if they no longer exists at the source.
- Robocopy copies using unbuffered I/O when available (recommended for large files).
- Changes to unit tests for resource
- xSQLServerSetup
- Added test coverage for helper function Copy-ItemWithRoboCopy
Fixes #185
Fixes #278
Fixes #286 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/282)
=> xSQLServerSetup: Changes to the helper function Copy-ItemWithRoboCopy

CHANGELOG.md, DSCResources/MSFT_xSQLServerLogin/MSFT_xSQLServerLogin.psm1, DSCResources/MSFT_xSQLServerLogin/MSFT_xSQLServerLogin.schema.mof, Examples/Resources/xSQLServerLogin/1-AddLogin.ps1, Examples/Resources/xSQLServerLogin/2-RemoveLogin.ps1, README.md, Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1, Tests/Unit/Stubs/SMO.cs, en-US/xSQLServer.strings.psd1
Updated the xSQLServerLogin resource to remove all references to the ShouldProcess cmdlet. Added the following parameters for the SqlLogin type:
- LoginMustChangePassword
- LoginPasswordExpirationEnabled
- LoginPasswordPolicyEnforced
Updated the examples and unit tests.
Remove ShouldProcess: Fixes #240 
Add SqlLogin Password Requirements: Fixes #251 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/249)
=> xSQLServerLogin: Removed ShouldProcess; Added Parameters

.gitignore, .markdownlint.json, CHANGELOG.md, CONTRIBUTING.md, Examples/Resources/xSQLServerAlias/1-AddSQLServerAlias.ps1, Examples/Resources/xSQLServerDatabaseOwner/1-SetDatabaseOwner.ps1, Examples/Resources/xSQLServerRole/1-AddServerRole.ps1, Examples/Resources/xSQLServerRole/2-RemoveServerRole.ps1, Examples/Resources/xSQLServerScript/1-RunScriptUsingSQLAuthentication.ps1, Examples/Resources/xSQLServerScript/2-RunScriptUsingWindowsAuthentication.ps1, Tests/xSQLServerCommon.Tests.ps1, appveyor.yml, gulpfile.js
Changes to tests in xSQLServer module
- Added common test xSQLServerCommon.Tests for xSQLServer module
- Now all markdown files will be style checked when tests are running in AppVeyor after sending in a pull request.
- Now all [Examples](/Examples/Resources) will be tested by compiling to a .mof file after sending in a pull request.
- Changes to xSQLServerDatabaseOwner
- The example 'SetDatabaseOwner' can now compile, it wrongly had a `DependsOn` in the example.
- Changes to SQLServerRole
- The examples 'AddServerRole' and 'RemoveServerRole' can now compile, it wrongly had a `DependsOn` in the example.
- Changes to xSQLServerScript
- The examples 'AddServerRole' and 'RemoveServerRole' can now compile correctly.
- Changes to CONTRIBUTING.md
- Added section 'Tests for examples files'
- …
=> Changes to tests in xSQLServer module

appveyor.yml
- Changes to AppVeyor
- After the tests has ran, code coverage from Pester will be written to AppVeyor Console
n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/309)
=> AppVeyor: Adding codecoverage after tests are ran

CHANGELOG.md, DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1
- Code cleanup. A function was used, that wasn't needed. And change a variable name to align more against HQRM.
- Changes to CHANGELOG.md
- A duplicated and out of order row was removed.
n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/312)
=> xSQLServerSetup: Some code cleanup, and misplaced entry in the CHANGELOG.md 

README.md
Changed anchor link for xSQLServerDatabaseRecoveryModel to lower-case.
I missed this in the review before I merged the recent pull request. This will make the link work.
n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/318)
=> Changes to README.md for xSQLServerDatabaseRecoveryModel

CHANGELOG.md, DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.schema.mof, README.md, Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1, en-US/xSQLServer.strings.psd1
Added support to xSQLServerSetup for clustered installations. Ported code from existing xSQLServerFailoverCluster resource and updated to correct issues and add additional functionality.
- Added support for multi-subnet clusters
- Corrected clustered disk detection issue with asymmetric storage
- Removed Get-WmiObject calls
- Added localized error messages
Fixes #227 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/326)
=> xSQLServerSetup: Add support for clustered installations (Fixes #227)

CHANGELOG.md, xSQLServerHelper.psm1
The parameter name in Confirm-SqlServerRoleMember is LoginName but when used in the function it is referenced as $Name.  Not sure how this is working for anyone as written.
Fixes #355
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/349)
=> xSQLServerHelper: Confirm-SqlServerRoleMember has parameter name LoginName but uses variable Name where it should be using LoginName

CHANGELOG.md, DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1
[The code for $SQLSysAdminAccounts being checked in PSBoundParameters is updated to use .ContainsKey method instead of -contains]
Fixes #371
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/370)
=> xSQLServerSetup: $SQLSysAdminAccounts never added to list 

CHANGELOG.md, Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1
The test now properly evaluates the setup argument for SQLSysAdminAccounts. This is for PR #370 
n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/382)
=> xSQLServerSetup: Fixes tests for SQLSysAdminAccounts

CHANGELOG.md, DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, README.md, Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1
This pull request includes multiple fixes and enhancements to allow for clustered installations (currently only fully tested the InstallFailoverCluster action, but all unit tests for others were successful). The AddNode action is the only one I know will not work due to some complexities with checking desired state. I'll open a separate issue for that.
Fixes #362 
Fixes #353 
Fixes #352 
Fixes #345 
Fixes #344 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/363)
=> xSQLServerSetup: fixes and enhancements for supporting clustered installations

CHANGELOG.md, DSCResources/MSFT_xSQLServerMaxDop/MSFT_xSQLServerMaxDop.psm1, DSCResources/MSFT_xSQLServerMaxDop/MSFT_xSQLServerMaxDop.schema.mof, Examples/Resources/xSQLServerMaxDop/1-SetMaxDopToOne.ps1, Examples/Resources/xSQLServerMaxDop/2-SetMaxDopToAuto.ps1, Examples/Resources/xSQLServerMaxDop/3-SetMaxDopToDefault.ps1, README.md, Tests/Unit/MSFT_xSQLServerMaxDop.Tests.ps1, en-US/xSQLServer.strings.psd1
Changes to xSQLServerMaxDop
- Added Pester Test
Fixes #292 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/317)
=> Changes to xSQLServerMaxDop

CHANGELOG.md, DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1
It now detects that feature Client Connectivity Tools (CONN) and Client Connectivity Backwards Compatibility Tools (BC) is installed. This is based on the work of @joshan1120 in PR #163. This resolved issue #159 and might also resolve #142.
Fixes #159 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/383)
=> xSQLServerSetup: Support feature CONN and BC

CHANGELOG.md, DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.schema.mof, README.md, Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1
Changes to xSQLServerSetup
- Now it can correctly determine the right cluster when only parameter InstallSQLDataDir is assigned a path (issue #401).
- Now the only mandatory path parameter is InstallSQLDataDir when installing Database Engine (issue #400).
- It now can handle mandatory parameters, and are not using wildcards to find the variables containing paths (issue #394).
Fixes #394 
Fixes #400 
Fixes #401
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/404)
=> xSQLServerSetup: Fixes failover cluster bugs with shared disks

CHANGELOG.md, DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1
- Changed to that instead of connection to localhost it is using `$env:COMPUTERNAME` as the host name to which it connects. And for cluster installation it uses the parameter `FailoverClusterNetworkName` as the host name to which it connects. Resolves issue #407.
Fixes #407 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/415)
=> xSQLServerSetup: Use the correct hostname for cluster installs

CHANGELOG.md, DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1
This includes fixes for when the xSQLServerSetup resource is called and has a value of PrepareFailoverCluster specified for the Action parameter.
Fixes #410 
Fixes #411 
- [ x] Change details added to Unreleased section of CHANGELOG.md?
- [ x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/421)
=> xSQLServerSetup: fixes for PrepareFailoverCluster action

CHANGELOG.md, DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1
- Solved the problem that InstanceDir and InstallSQLDataDir could not be set to just a qualifier (i.e. 'E:').
- Improved the mock that tests the setup arguments.
Fixes #418 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/419)
=> xSQLServerSetup: Paths can be set to just the qualifier

.codecov.yml, CHANGELOG.md
Raised the CodeCov target to 70% which is the minimum and required target for HQRM resource.
_We limited it until we reache 70% so that it would no fail on the PR's. But now we have reached that target! Many thanks to @luigilink for going back and fixing already present test to get more coverage!_ 👍 😃   
n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/439)
=> xSQLServer: Raised the codecov target to 70%

CHANGELOG.md, DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, README.md, Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1, Tests/Unit/xSQLServerHelper.Tests.ps1, en-US/xSQLServer.strings.psd1, xSQLServerHelper.psm1
- Added a note to the README.md saying that it is not possible to add or remove features from a SQL Server failover cluster (issue #433).
- Changed so that it reports false if the desired state is not correct (issue #432).
- Added a test to make sure we always return false if a SQL Server failover cluster is missing features.
- Helper function Connect-SQLAnalysis
- Now has correct error handling, and throw does not used the unknown named parameter '-Message' (issue #436)
- Added tests for Connect-SQLAnalysis
- Changed to localized error messages.
- Minor changes to error handling.
Fixes #432 
Fixes #433 
Fixes #436 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> xSQLServerSetup: Minor fixes for Analysis Services in Failover Cluster

CHANGELOG.md, DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, Examples/Resources/xSQLServerSetup/1-InstallDefaultInstanceSingleServer.ps1, Examples/Resources/xSQLServerSetup/2-InstallNamedInstanceSingleServer.ps1, Examples/Resources/xSQLServerSetup/3-InstallNamedInstanceSingleServerFromUncPathUsingSourceCredential.ps1, Examples/Resources/xSQLServerSetup/4-InstallNamedInstanceInFailoverClusterFirstNode.ps1, Examples/Resources/xSQLServerSetup/5-InstallNamedInstanceInFailoverClusterSecondNode.ps1, README.md, Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1
- This adds better support for Addnode (issue #369).
- Now it skips cluster validation för add node (issue #442).
- Now it ignores parameters that are not allowed for action Addnode (issue #441).
- Added examples for installing single server instances.  
- Added examples for installing a Failover Cluster.
Fixes #369 (partly, issues are submitted for known bugs)
Fixes #441 
Fixes #442 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/445)
=> xSQLServerSetup: Adds better support for action 'Addnode'

CHANGELOG.md, DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroup/MSFT_xSQLServerAlwaysOnAvailabilityGroup.psm1
Exit the permissions check loop when the script verifies the required cluster permissions are present.
Fixes xSQLServerAlwaysOnAvailabilityGroup: Reports wrongly that 'NT AUTHORITY\SYSTEM' is missing even if it is not #467 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/470)
=> xSQLServerAlwaysOnAvailabilityGroup: Fixed permissions checking loop

CHANGELOG.md, DSCResources/MSFT_xSQLServerAvailabilityGroupListener/MSFT_xSQLServerAvailabilityGroupListener.psm1, DSCResources/MSFT_xSQLServerAvailabilityGroupListener/MSFT_xSQLServerAvailabilityGroupListener.schema.mof, README.md, Tests/Unit/MSFT_xSQLServerAvailabilityGroupListener.Tests.ps1, en-US/xSQLServer.strings.psd1
- Changes to xSQLServerAvailabilityGroupListener
- Removed the dependency of SQLPS provider (issue #460).
- Cleaned up code.
- Cleaned up tests somewhat.
- Fixed PSSA rule warnings (issue #255).
- Parameter Ensure now defaults to 'Present' (issue #450).
Fixes #460
Fixes #255 
Fixes #450 
Fixes #233 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/469)
=> xSQLServerAvailabilityGroupListener: Removed the dependency of SQLPS provider

CHANGELOG.md, DSCResources/MSFT_xSQLServerFirewall/MSFT_xSQLServerFirewall.psm1, Tests/Unit/MSFT_xSQLServerFirewall.Tests.ps1
- Changes to xSQLServerFirewall
- Now it will correctly create rules when the resource is used for two or more instances on the same server (issue #461).
Fixes #461 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/479)
=> xSQLServerFirewall: Now works on two or more instances on the same server

CHANGELOG.md, README.md
- Adding deprecated tag to xSQLServerFailoverClusterSetup, xSQLAOGroupEnsure and xSQLAOGroupJoin in README.md so it it more clear that these resources has been replaced by xSQLServerSetup, xSQLServerAlwaysOnAvailabilityGroup and xSQLServerAlwaysOnAvailabilityGroupReplica respectively.
Fixes #494 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/496)
=> README.md: Adding deprecated tag to deprecated resources

CHANGELOG.md, DSCResources/MSFT_xSQLServerEndpoint/MSFT_xSQLServerEndpoint.psm1, DSCResources/MSFT_xSQLServerEndpoint/MSFT_xSQLServerEndpoint.schema.mof, Examples/Resources/xSQLServerAlwaysOnAvailabilityGroup/1-CreateAvailabilityGroup.ps1, Examples/Resources/xSQLServerAlwaysOnAvailabilityGroupReplica/1-CreateAvailabilityGroupReplica.ps1, Examples/Resources/xSQLServerAlwaysOnAvailabilityGroupReplica/2-RemoveAvailabilityGroupReplica.ps1, Examples/Resources/xSQLServerEndpoint/1-CreateEndpointWithDefaultValues.ps1, Examples/Resources/xSQLServerEndpoint/2-CreateEndpointWithSpecificPortAndIPAddress.ps1, Examples/Resources/xSQLServerEndpoint/3-RemoveEndpoint.ps1, README.md, Tests/Unit/MSFT_xSQLServerEndpoint.Tests.ps1, Tests/Unit/Stubs/SMO.cs, en-US/xSQLServer.strings.psd1
- Changes to xSQLServerEndpoint
- BREAKING CHANGE: Now SQLInstanceName is mandatory, and is a key, so SQLInstanceName has no longer a default value (issue #279).
- BREAKING CHANGE: Parameter AutorizedUser has been removed (issue #466, issue #275 and issue #80). Connect permissons can be set using the resource xSQLServerEndpointPermission.
- Optional parameter IpAddress has been added. Default is to listen on any valid IP-address. (issue #232)
- Parameter Port now has a default value of 5022.
- Parameter Ensure now defaults to 'Present'.
- Resource now supports changing IP address and changing port.
- Added unit tests (issue #289)
- Added examples.
This resource is dependent on that PR #485 is merged before this one, so there is not a problem setting …
=> BREAKING CHANGE: xSQLServerEndpoint: Refactored this resource

CHANGELOG.md, DSCResources/MSFT_xSQLServerEndpointState/MSFT_xSQLServerEndpointState.psm1, DSCResources/MSFT_xSQLServerEndpointState/MSFT_xSQLServerEndpointState.schema.mof, Examples/Resources/xSQLServerEndpointState/1-MakeSureEndpointIsStarted.ps1, README.md, Tests/Unit/MSFT_xSQLServerEndpointState.Tests.ps1
- Changes to xSQLServerEndpointState
- Cleaned up code, removed `SupportsShouldProcess` and fixed PSSA rules warnings (issue #258 and issue #230).
- Now the defult value for the parameter `State` is 'Started'.
- Updated README.md with a description for the resources and revised the parameter descriptions.
- Removed dependency of SQLPS provider (issue #481).
Fixes #481 
Fixes #258 
Fixes #230 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/497)
=> xSQLServerEndpointState: Removed dependency of SQLPS provider

CHANGELOG.md, xSQLServerHelper.psm1
- Changes to xSQLServerHelper module
- Removing helper function Get-SQLAlwaysOnEndpoint becuase there is no resource using it any longer.
Fixes #499
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/500)
=> xSQLServerHelper: Removing helper function Get-SQLAlwaysOnEndpoint

CHANGELOG.md, DSCResources/MSFT_xWaitForAvailabilityGroup/MSFT_xWaitForAvailabilityGroup.psm1, DSCResources/MSFT_xWaitForAvailabilityGroup/MSFT_xWaitForAvailabilityGroup.schema.mof, Examples/Resources/xWaitForAvailabilityGroup/1-WaitForASingleClusterGroup.ps1, Examples/Resources/xWaitForAvailabilityGroup/2-WaitForMultipleClusterGroups.ps1, README.md, Tests/Unit/MSFT_xWaitForAvailabilityGroup.Tests.ps1
- Changes to xWaitForAvailabilityGroup
- Updated README.md with a description for the resources and revised the parameter descriptions.
- The default value for RetryIntervalSec is now 20 seconds and the default value for RetryCount is now 30 times (issue #505).
- Cleaned up code and fixed PSSA rules warnings (issue #268).
- Added unit tests (issue #297).
- Added descriptive text to README.md that the account that runs the resource must have permission to run the cmdlet Get-ClusterGroup (issue #307).
- Added read-only parameter GroupExist which will return $true if the cluster role/group exist, otherwise it returns $false (issue #510).
- Added examples.
Fixes #505 
Fixes #268 
Fixes #297 
Fixes #307 …
=> xWaitForAvailabilityGroup:  Added tests and fixed some issues

CHANGELOG.md, DSCResources/MSFT_xSQLServerAlwaysOnService/MSFT_xSQLServerAlwaysOnService.psm1, Tests/Unit/MSFT_xSQLServerAlwaysOnService.Tests.ps1, en-US/xSQLServer.strings.psd1
- Changes to xSQLServerAlwaysOnService
- Get-TargetResource should no longer fail silently with error 'Index operation failed; the array index evaluated to null.'. Now if the Server.IsHadrEnabled property return neither $true or $false the Get-TargetResource function will throw an error.
Fixes #519 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/524)
=> xSQLServerAlwaysOnService: Fix for issue #519

CHANGELOG.md, DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1
Updated xSQLServerSetup module Get-Resource method to detect DQ, DQC, BOL, SDK features.
**Tested with following DSC:**
```
xSQLServerSetup Instance
{
Action = "Install"
InstanceName = $SqlInstanceName
SetupCredential = $DeployServiceAccount
SourcePath = "C:\Media"
Features = "FULLTEXT,BC,DQ,BOL,SSMS,DQC,ADV_SSMS,AS,SDK,SQLENGINE,CONN,RS"
ProductKey = $ProductKey
}
```
Fixes #516 
Fixes #490 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/521)
=> xSQLServerSetup: Updated xSQLServerSetup module Get-Resource method to detect DQ, DQC, BOL, SDK features.

CHANGELOG.md, DSCResources/MSFT_xSQLServerLogin/MSFT_xSQLServerLogin.psm1, DSCResources/MSFT_xSQLServerLogin/MSFT_xSQLServerLogin.schema.mof, Examples/Resources/xSQLServerLogin/1-AddLogin.ps1, README.md, Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1, Tests/Unit/Stubs/SMO.cs
This patch adds _Disable_ parameter to xSQLServerLogin resource. The default value is $false. If set to $true, an existing login will be disabled. If creating a new login, it will be created as disabled.
I'm not really familiar with Pester tests, could use some help to update the unit tests :-)
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/531)
=> xSQLServerLogin: Disable login parameter

CHANGELOG.md, DSCResources/MSFT_xSQLServerDatabaseRole/MSFT_xSQLServerDatabaseRole.psm1
Updated creation of smo.user object, fixes #530 
Wrong variable used in smo.user object creation, updated variable.
Fixes #530 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/544)
=> xSQLServerDatabaseRole: Updated variable passed to constructor

CHANGELOG.md, DSCResources/MSFT_xSQLServerNetwork/MSFT_xSQLServerNetwork.psm1, DSCResources/MSFT_xSQLServerNetwork/MSFT_xSQLServerNetwork.schema.mof, Examples/Resources/xSQLServerNetwork/1-EnableTcpIpOnCustomStaticPort.ps1, Examples/Resources/xSQLServerNetwork/1-EnableTcpIpWithStaticPort.ps1, Examples/Resources/xSQLServerNetwork/2-EnableTcpIpWithDynamicPort.ps1, README.md, Tests/Unit/MSFT_xSQLServerNetwork.Tests.ps1, Tests/Unit/xSQLServerHelper.Tests.ps1, en-US/xSQLServer.strings.psd1, xSQLServerHelper.psm1
- Changes to xSQLServerNetwork
- Added optional parameter SQLServer with default value of $env:COMPUTERNAME (issue #528).
- Added optional parameter RestartTimeout with default value of 120 seconds.
- Now the resource supports restarting a sql server in a cluster (issue #527 and issue #455).
- Now the resource allows to set the parameter TcpDynamicPorts to a blank value (partly fixes issue #534). Setting a blank value for parameter TcpDynamicPorts together with a value for parameter TcpPort means that static port will be used.
- Now the resource will not call Alter() in the Set-TargetResource when there is no change necessary (issue #537).
- Updated example 1-EnableTcpIpOnCustomStaticPort.
- Added unit tests (issue #294).
- Refactored some of the code, …
=> xSQLServerNetwork: Refactored this resource and added tests

CHANGELOG.md, DSCResources/MSFT_xSQLServerMaxDop/MSFT_xSQLServerMaxDop.psm1, DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1, Tests/Unit/MSFT_xSQLServerMaxDop.Tests.ps1, Tests/Unit/MSFT_xSQLServerMemory.Tests.ps1
This issue affects two resources - xSQLServerMaxDop and xSQLServerMemory.
This fixes an issue with the SQLServer property not assuming the default value when no value is passed.
Fixes #576 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/577)
=> xSQLServerMaxDop & xSQLServerMemory: Fixed issue with SQLServer parameter not assuming the default value.

CHANGELOG.md, DSCResources/MSFT_xSQLServerRSConfig/MSFT_xSQLServerRSConfig.psm1
Replaced two sqlcmd.exe executions with Invoke-Sqlcmd calls.
A small code cleanup as the result of the above change.
Removed the conditional use of $RSConfig.MachineAccountIdentity as
$RSSvcAccountUsername, since it was always empty (tested on SQL2014
only). Need to double-check this.
Fixes #567
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/571)
=> xSQLServerRSConfig: Replaced sqlcmd.exe with Invoke-Sqlcmd

CHANGELOG.md, README.md
Changed the documenation for the xSQLServerDatabase, there was an error in there because the sqlinstance should be sqlinstancename.
checked the code for this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/579)
=> xSQLServerDatabase: Changed SQLInstance to SQLInstanceName

CHANGELOG.md, DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1
Get-TargetResource was only checking for Conn, BC and other features if the SQL service was found, There are use cases for installing these tools without installing SQL Engine. This moves them outside that scope and updates the tests to reflect this change. 
Fixes #591 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/595)
=> xSQLServerSetup: Move checking for Tools features to not depend on SQLEngine - Fixes #591

CHANGELOG.md, DSCResources/MSFT_xSQLServerRSConfig/MSFT_xSQLServerRSConfig.psm1, Tests/Unit/MSFT_xSQLServerRSConfig.Tests.ps1
A fix for web portal application name change introduced in SQL Server 2016.
Fixes #569
Fixes #295 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/575)
=> xSQLServerRSConfig: Virtual directory creation for SQL 2016

CHANGELOG.md, DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1
* Changes to xSQLServerSetup
* Now all major version uses the same identifier to evaluate InstallSharedDir and InstallSharedWOWDir (issue #420).
Fixes #420 
Fixes #639 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/599)
=> xSQLServerSetup: Now uses same identifier for InstallSharedDir

CHANGELOG.md, DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroup/MSFT_xSQLServerAlwaysOnAvailabilityGroup.psm1
Instead of applying the value of the 'FailoverMode' DSC parameter to the
AvailabilityMode property of the SQL AG, which results in an error message that
e.g. 'Automatic' cannot be converted to the SMO AvailabilityMode enumeration,
the value of the 'FailoverMode' DSC parameter must instead be applied to the
FailoverMode property of the SQL AG.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/650)
=> xSQLServerAlwaysOnAvailabilityGroup: Fix incorrect utilization of 'FailoverMode'

CHANGELOG.md, DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1, DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/en-US/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.strings.psd1, Tests/Unit/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.Tests.ps1, en-US/xSQLServerHelper.strings.psd1
Updated localization for xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.
Fixes #660 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/663)
=> xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership: Localization updates

.vscode/settings.json, CHANGELOG.md
- Added powershell.codeFormatting.preset with a value of 'Custom' so that workspace formatting settings are honored (issue #665).
Fixes #665 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/666)
=> xSQLServer: Update VS Code formatting settings

CHANGELOG.md, DSCResources/MSFT_xSQLServerAlwaysOnService/MSFT_xSQLServerAlwaysOnService.psm1, DSCResources/MSFT_xSQLServerAlwaysOnService/MSFT_xSQLServerAlwaysOnService.schema.mof, Examples/Resources/xSQLServerAlwaysOnService/1-EnableAlwaysOn.ps1, Examples/Resources/xSQLServerAlwaysOnService/2-DisableAlwaysOn.ps1, README.md
- Changes to xSQLServerAlwaysOnService
- Added resource description in README.md.
- Updated parameters descriptions in comment-based help, schema.mof and README.md.
- Changed the datatype of the parameter to Uint32 so the same datatype is used
in both the Get-/Test-/Set-TargetResource functions as in the schema.mof
(issue #688).
- Added read-only property IsHadrEnabled to schema.mof and the README.md
(issue #687).
- Minor cleanup of code.
- Added examples (issue #633)
- 1-EnableAlwaysOn.ps1
- 2-DisableAlwaysOn.ps1
Fixes #633 
Fixes #687 
Fixes #688 
**Task list:**
--- …
=> xSQLServerAlwaysOnService: Added missing read property, fixed types, and added examples

CHANGELOG.md, DSCResources/CommonResourceHelper.psm1, Tests/Unit/CommonResourceHelper.Tests.ps1
- Minor style change in CommonResourceHelper. Added missing [Parameter()] on three parameters.
n/a
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/693)
=> xSQLServer: Minor style change in CommonResourceHelper

.MetaTestOptIn.json, CHANGELOG.md, DSCResources/CommonResourceHelper.psm1, DSCResources/MSFT_xSQLServerAvailabilityGroupListener/MSFT_xSQLServerAvailabilityGroupListener.psm1, DSCResources/MSFT_xSQLServerConfiguration/MSFT_xSQLServerConfiguration.psm1, DSCResources/MSFT_xSQLServerEndpointPermission/MSFT_xSQLServerEndpointPermission.psm1, DSCResources/MSFT_xSQLServerEndpointState/MSFT_xSQLServerEndpointState.psm1, DSCResources/MSFT_xSQLServerNetwork/MSFT_xSQLServerNetwork.psm1, DSCResources/MSFT_xSQLServerPermission/MSFT_xSQLServerPermission.psm1, DSCResources/MSFT_xSQLServerReplication/MSFT_xSQLServerReplication.psm1, DSCResources/MSFT_xSQLServerScript/MSFT_xSQLServerScript.psm1, Tests/Unit/CommonResourceHelper.Tests.ps1, Tests/Unit/Stubs/SQLPSStub.psm1, Tests/Unit/Stubs/SQLServerStub.psm1
- Opt-in for module files common tests (issue #702).
- Removed Byte Order Mark (BOM) from the files; CommonResourceHelper.psm1,
MSFT_xSQLServerAvailabilityGroupListener.psm1, MSFT_xSQLServerConfiguration.psm1, 
MSFT_xSQLServerEndpointPermission.psm1, MSFT_xSQLServerEndpointState.psm1, 
MSFT_xSQLServerNetwork.psm1, MSFT_xSQLServerPermission.psm1, 
MSFT_xSQLServerReplication.psm1, MSFT_xSQLServerScript.psm1, SQLPSStub.psm1, 
SQLServerStub.psm1.
Fixers #702 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/704)
=> xSQLServer: Opt-in for module files common tests

CHANGELOG.md, DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1
- Now Get-TargetResource correctly returns an array for property ASSysAdminAccounts,
and no longer throws an error when there is just one Analysis Services
administrator (issue #691).
- Fixed typo in variable $fullTextServiceAccountUsername.
Fixes #691 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/715)
=> xSQLServerSetup: Fixed bug with ASSysAdminAccounts

CHANGELOG.md, DSCResources/MSFT_xSQLServerScript/MSFT_xSQLServerScript.psm1
As raised in #728 there are various ScriptAnalyzer errors from the parameters being marked as Mandatory = $false, this resolves those errors.
Fixes #728 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/764)
=> xSQLServerScript: Fixing PSSA errors

CHANGELOG.md, DSCResources/MSFT_xSQLServerAlwaysOnService/MSFT_xSQLServerAlwaysOnService.psm1, Tests/Unit/MSFT_xSQLServerAlwaysOnService.Tests.ps1
- Changes to xSQLServerAlwaysOnService
- Casting the result of the property IsHadrEnabled to [System.Boolean] so that   $null is never returned, 
which resulted in an exception (issue #763).
Fixes #763 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/768)
=> xSQLServerAlwaysOnService: IsHadrEnabled is cast to [System.Boolean] 

CHANGELOG.md, Tests/Unit/MSFT_xSQLServerAlias.Tests.ps1, Tests/Unit/MSFT_xSQLServerAlwaysOnAvailabilityGroup.Tests.ps1, Tests/Unit/MSFT_xSQLServerAlwaysOnAvailabilityGroupReplica.Tests.ps1, Tests/Unit/MSFT_xSQLServerAvailabilityGroupListener.Tests.ps1, Tests/Unit/MSFT_xSQLServerConfiguration.Tests.ps1, Tests/Unit/MSFT_xSQLServerDatabase.Tests.ps1, Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1, Tests/Unit/MSFT_xSQLServerDatabaseRecoveryModel.Tests.ps1, Tests/Unit/MSFT_xSQLServerDatabaseRole.Tests.ps1, Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1, Tests/Unit/MSFT_xSQLServerMaxDop.Tests.ps1, Tests/Unit/MSFT_xSQLServerMemory.Tests.ps1, Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1, Tests/Unit/MSFT_xSQLServerRole.Tests.ps1, Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1
- Fixed typos and the use of wrong parameters in unit tests which was
found after release of new version of Pester (issue #773).
Fixes #773 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/777)
=> xSQLServer: Fixed typos and the use of wrong parameters in unit tests

CHANGELOG.md, Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1, Tests/Integration/MSFT_xSQLServerSetup.config.ps1, Tests/Unit/xSQLServerHelper.Tests.ps1, appveyor.yml, xSQLServerHelper.psm1
- Updated appveyor.yml so that integration tests run in order and so that
the SQLPS module folders are renamed to not disturb the units test, but
can be renamed back by the integration tests xSQLServerSetup so that the
integration tests can run successfully.
(issue #774).
- Changes to xSQLServerHelper
- Changes to Connect-SQL and Import-SQLPSModule
- Now it correctly loads the correct assemblies when SqlServer module is
present (issue #649).
- Now SQLPS module will be correctly loaded (discovered) after installation
of SQL Server. Previously resources depending on SQLPS module could fail
because SQLPS was not found after installation because the PSModulePath
environment variable in the (LCM) PowerShell session did not contain the …
=> xSQLServer: Using correct assemblies for module SqlServer 

CHANGELOG.md, DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupReplica/MSFT_xSQLServerAlwaysOnAvailabilityGroupReplica.schema.mof, README.md
Added EndpointPort and EndpointUrl as read-only properties to the schema.
Fixes: #477 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/803)
=> xSQLServerAlwaysOnAvailabilityGroupReplica: Added EndpointPort and EndpointUrl as read-only properties to the schema

CHANGELOG.md, DSCResources/MSFT_xSQLServerMaxDop/MSFT_xSQLServerMaxDop.psm1
- Changes to xSqlServerMaxDop
- Fixed error where Measure-Object cmdlet would fail claiming it could not
find the specified property ([issue #801](https://github.com/PowerShell/xSQLServer/issues/801))
Fixes #801 
Fixes #805 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/802)
=> xSqlServerMaxDop: Measure-Resource value of Property is not valid

CHANGELOG.md, appveyor.yml
- Changed so the maximum version to be installed is 4.0.6.0. Quick fix until we
can resolve the unit tests (see issue #807).
This does not fix the issue - just a workaround until we fix the problems in the unit tests.
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/813)
=> xSQLServer: Quick fix for breaking changes in Pester

CHANGELOG.md, Tests/Unit/xSQLServerHelper.Tests.ps1, xSQLServerHelper.psm1
Fixed Connect-SQL by ensuring the Status property returns 'Online' prior to returning the SQL Server object.
Fixes #333 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/799)
=> xSQLServerHelper: Connect-SQL: Throw on failed connection

CHANGELOG.md, Tests/Integration/MSFT_xSQLServerAlwaysOnService.Integration.Tests.ps1, Tests/Integration/MSFT_xSQLServerAlwaysOnService.config.ps1, Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1, Tests/Integration/MSFT_xSQLServerSetup.config.ps1, appveyor.yml
- Moved the code block, that contains workarounds in appveyor.yml, so it is run
during the install phase instead of the test phase.
- Changes to integration tests.
- Moved the configuration block from the MSFT\_xSQLServerSetup.Integration.Tests.ps1
to the MSFT\_xSQLServerSetup.config.ps1 to align with the other integration
test. And also get most of the configuration in one place.
- Changed the tests so that the local SqlInstall account is added as a member
of the local administrators group.
- Changed the tests so that the local SqlInstall account is added as a member
of the system administrators in SQL Server (Database Engine) - needed for the
xSQLServerAlwaysOnService integration tests.
- Changed so …
=> xSQLServerAlwaysOnService: Adding integration tests

CHANGELOG.md, DSCResources/MSFT_xSQLServerServiceAccount/MSFT_xSQLServerServiceAccount.psm1, DSCResources/MSFT_xSQLServerServiceAccount/MSFT_xSQLServerServiceAccount.schema.mof, DSCResources/MSFT_xSQLServerServiceAccount/en-US/MSFT_xSQLServerServiceAccount.strings.psd1, Examples/Resources/xSQLServerServiceAccount/1-ConfigureServiceAccount-UserAccount.ps1, Examples/Resources/xSQLServerServiceAccount/2-ConfigureServiceAccount-VirtualAccount.ps1, README.md, Tests/Unit/MSFT_xSQLServerServiceAccount.Tests.ps1, Tests/Unit/Stubs/SMO.cs
Added new resource `xSQLServerServiceAccount` with examples and localization information.
Fixes #706 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/795)
=> xSQLServerServiceAccount: New Resource Added

CHANGELOG.md, Tests/Integration/MSFT_xSQLServerSetup.config.ps1
- Changes to integration tests.
- Fixed wrong variable name for SQL service credential. It was using the
integration test variable name instead of the parameter name.
n/a
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/821)
=> xSQLServerSetup: Used wrong variable in integration test

CHANGELOG.md, DSCResources/MSFT_xSQLServerRSConfig/MSFT_xSQLServerRSConfig.psm1, Tests/Unit/MSFT_xSQLServerRSConfig.Tests.ps1
- Changes to xSQLServerRSConfig
- No longer returns a null value from Test-TargetResource when Reporting
Services has not been initialized (issue #822).
Fixes #822 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/825)
=> xSQLServerRSConfig: No longer returns a null value from Test-TargetResource

CHANGELOG.md, Tests/Integration/MSFT_xSQLServerAlwaysOnService.Integration.Tests.ps1, Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1
- Changes to xSQLServerAlwaysOnService
- Fix integration tests. Added ErrorAction 'Stop' to the cmdlet Start-DscConfiguration (issue #824]).
- Fix integration tests. Added ErrorAction 'Stop' to the cmdlet Start-DscConfiguration (issue #824]).
Fixes #824 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/826)
=> xSQLServer: Fix integration tests. Added ErrorAction 'Stop' to the cmdlet Start-DscConfiguration

CHANGELOG.md, DSCResources/MSFT_xSQLServerRSConfig/MSFT_xSQLServerRSConfig.psm1, Tests/Unit/MSFT_xSQLServerRSConfig.Tests.ps1
- Changes to xSQLServerRSConfig
- Fixed so that when two Reporting Services are installed for the same major
version the resource does not throw an error (issue #819).
Fixes #819 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/827)
=> xSQLServerRSConfig: Throws for two Reporting Services with same major version

CHANGELOG.md, DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroup/MSFT_xSQLServerAlwaysOnAvailabilityGroup.psm1, DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupReplica/MSFT_xSQLServerAlwaysOnAvailabilityGroupReplica.psm1, Tests/Unit/MSFT_xSQLServerAlwaysOnAvailabilityGroup.Tests.ps1, Tests/Unit/MSFT_xSQLServerAlwaysOnAvailabilityGroupReplica.Tests.ps1, Tests/Unit/Stubs/SMO.cs, Tests/Unit/xSQLServerHelper.Tests.ps1, en-US/xSQLServerHelper.strings.psd1, xSQLServerHelper.psm1
- Added new helper function "Test-ClusterPermissions".
- Changes to xSQLServerAlwaysOnAvailabilityGroup
- Use the new helper function "Test-ClusterPermissions".
- Refactored the unit tests to allow them to be more user friendly.
- Changes to xSQLServerAlwaysOnAvailabilityGroupReplica
- Use the new helper function "Test-ClusterPermissions".
- Changes to SMO.cs
- Added default properties to the Server class
- AvailabilityGroups
- Databases
- EndpointCollection
- Added a new overload to the Login class
- Added default properties to the AvailabilityReplicas class
- AvailabilityDatabases
- AvailabilityReplicas
Fixes #446 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" …
=> xSQLServerHelper: Create helper function Test-ClusterPermissions

CHANGELOG.md, DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroup/MSFT_xSQLServerAlwaysOnAvailabilityGroup.schema.mof, README.md
Added missing read-only properties to the xSQLServerAlwaysOnAvailabilityGroup schema.
Fixes #787 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/838)
=> xSQLServerAlwaysOnAvailabilityGroup: Added missing read-only properties

CHANGELOG.md, DSCResources/MSFT_xSQLServerRSConfig/MSFT_xSQLServerRSConfig.psm1, Tests/Unit/MSFT_xSQLServerRSConfig.Tests.ps1, Tests/Unit/xSQLServerHelper.Tests.ps1, en-US/xSQLServerHelper.strings.psd1, xSQLServerHelper.psm1
- Changes to xSQLServerRSConfig
- Now the resource will restart the Reporting Services service after
initializing (issue #592). This will enable the Reports site to work.
Fixes #592 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/837)
=> xSQLServerRSConfig: Restart Reporting Services after initialize

CHANGELOG.md, Tests/Integration/MSFT_xSQLServerRSConfig.Integration.Tests.ps1, Tests/Integration/MSFT_xSQLServerRSConfig.config.ps1
- Changes to xSQLServerRSConfig
- Added integration test (issue #753).
Fixes #753 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/834)
=> xSQLServerRSConfig: Added integration test

CHANGELOG.md, DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroup/MSFT_xSQLServerAlwaysOnAvailabilityGroup.psm1, DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupReplica/MSFT_xSQLServerAlwaysOnAvailabilityGroupReplica.psm1, Tests/Unit/MSFT_xSQLServerAlwaysOnAvailabilityGroup.Tests.ps1, Tests/Unit/MSFT_xSQLServerAlwaysOnAvailabilityGroupReplica.Tests.ps1
Updated xSQLServerAlwaysOnAvailabilityGroup and xSQLServerAlwaysOnAvailabilityGroupReplica to utilize the Get-PrimaryReplicaServerObject helper function.
Fixes #630 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/842)
=> xSQLServerAlwaysOnAvailabilityGroup\Replica: Utilize the Get-PrimaryReplicaServerObject helper function

CHANGELOG.md, DSCResources/MSFT_xSQLServerRSConfig/MSFT_xSQLServerRSConfig.psm1, DSCResources/MSFT_xSQLServerRSConfig/MSFT_xSQLServerRSConfig.schema.mof, README.md, Tests/Unit/MSFT_xSQLServerRSConfig.Tests.ps1
Added support for customising SSRS virtual server names.
Fixes #570 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/638)
=> xSQLServerRSConfig: Virtual directories and URL reservations

CHANGELOG.md, DSCResources/MSFT_xSQLServerDatabase/MSFT_xSQLServerDatabase.psm1, DSCResources/MSFT_xSQLServerDatabase/MSFT_xSQLServerDatabase.schema.mof, Examples/Resources/xSQLServerDatabase/1-CreateDatabase.ps1, README.md, Tests/Unit/MSFT_xSQLServerDatabase.Tests.ps1, en-US/xSQLServerHelper.strings.psd1
Setting collation of a database to be different to the server is sometimes necessary. This adds that functionality and also fixes an issue with the Get-TargetResource tests that was incorrectly doing `$null | should be $null` (#849).
Fixes #767 
Fixes #849
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/850)
=> xSQLServerDatabase: Add Collation as a property when defining a Database

CHANGELOG.md, DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroup/MSFT_xSQLServerAlwaysOnAvailabilityGroup.psm1, Tests/TestHelpers/CommonTestHelper.psm1, Tests/Unit/MSFT_xSQLServerAlwaysOnAvailabilityGroup.Tests.ps1
- Changes to xSQLServerAlwaysOnAvailabilityGroup
- Refactored the unit tests to allow them to be more user friendly and to test
additional SQLServer variations.
- Each test will utilize the Import-SQLModuleStub to ensure the correct module is loaded.
- Fixed an issue when setting the SQLServer parameter to a Fully Qualified Domain Name (FQDN).
- Fixed the logic so that if a parameter is not supplied to the resource, the resource will not attempt to apply the defaults on subsequent checks.
- Added the CommonTestHelper.psm1 to store common testing functions.
- Added the Import-SQLModuleStub function to ensure the correct version of the module stubs are loaded.
Fixes #468 
Fixes #784 
Fixes some of #517 …
=> xSQLServerAlwaysOnAvailabilityGroup: Resolved FQDN and Logic Bugs

CHANGELOG.md, DSCResources/MSFT_xSQLServerNetwork/MSFT_xSQLServerNetwork.psm1, DSCResources/MSFT_xSQLServerNetwork/MSFT_xSQLServerNetwork.schema.mof, DSCResources/MSFT_xSQLServerNetwork/en-US/MSFT_xSQLServerNetwork.strings.psd1, Examples/Resources/xSQLServerNetwork/1-EnableTcpIpWithStaticPort.ps1, Examples/Resources/xSQLServerNetwork/2-EnableTcpIpWithDynamicPort.ps1, README.md, Tests/Unit/MSFT_xSQLServerNetwork.Tests.ps1
Corrects an issue where changing from a dynamic to a static TCP port is not possible. This PR renamed the parameter TcpDynamicPorts to TcpDynamicPort and changed its type to Boolean. Additionally, localization for en-US was added in support of the ([localization project](https://github.com/PowerShell/xSQLServer/projects/3)).
- Fixes #534
- Fixes #618 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/887)
=> BREAKING CHANGE: xSQLServerNetwork: Support for configuring SQL Server to use a static port

CHANGELOG.md, Examples/Resources/xSQLServerRSConfig/1-DefaultConfiguration.ps1, Examples/Resources/xSQLServerRSConfig/2-CustomConfiguration.ps1, README.md
Added examples for xSQLServerRSConfig resource.
Fixes #844
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/852)
=> xSQLServerRSConfig: Adding examples

CHANGELOG.md, DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroup/MSFT_xSQLServerAlwaysOnAvailabilityGroup.psm1, DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroup/MSFT_xSQLServerAlwaysOnAvailabilityGroup.schema.mof, Examples/Resources/xSQLServerAlwaysOnAvailabilityGroup/3-CreateAvailabilityGroupDetailed.ps1, README.md, Tests/Unit/MSFT_xSQLServerAlwaysOnAvailabilityGroup.Tests.ps1, Tests/Unit/Stubs/SMO.cs, Tests/Unit/xSQLServerHelper.Tests.ps1, appveyor.yml, xSQLServerHelper.psm1
Added the parameter `ProcessOnlyOnActiveNode` to allow the end user to specify that the resource should not attempt to run if the current node is not actively hosting the SQL Instance.
Fixes #868
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/890)
=> xSQLServerAlwaysOnAvailabilityGroup: Make Cluster Aware

CHANGELOG.md, DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupReplica/MSFT_xSQLServerAlwaysOnAvailabilityGroupReplica.psm1, DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupReplica/MSFT_xSQLServerAlwaysOnAvailabilityGroupReplica.schema.mof, Examples/Resources/xSQLServerAlwaysOnAvailabilityGroupReplica/1-CreateAvailabilityGroupReplica.ps1, README.md, Tests/Unit/MSFT_xSQLServerAlwaysOnAvailabilityGroupReplica.Tests.ps1
Added the parameter `ProcessOnlyOnActiveNode` to allow the end user to specify that the resource should not attempt to run if the current node is not actively hosting the SQL Instance.
Fixes #870 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/892)
=> xSQLServerAlwaysOnAvailabilityGroupReplica: Make Cluster Aware

CHANGELOG.md, DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1, DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.schema.mof, Examples/Resources/xSQLServerMemory/2-SetMaxMemoryToAuto.ps1, README.md, Tests/Unit/MSFT_xSQLServerMemory.Tests.ps1
Made the resource cluster aware. When ProcessOnlyOnActiveNode is specified, the resource will only determine if a change is needed if the target node is the active host of the SQL Server instance
Fixes #867 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/896)
=> xSQLServerMemory: Make Cluster Aware

CHANGELOG.md, Tests/Unit/MSFT_xSQLServerAvailabilityGroupListener.Tests.ps1, Tests/Unit/MSFT_xSQLServerEndpointPermission.Tests.ps1
- Changes to xSQLServerEndpointPermission
- Fixed a problem when running the tests locally in a PowerShell console it
would ask for parameters (issue #897).
- Changes to xSQLServerAvailabilityGroupListener
- Fixed a problem when running the tests locally in a PowerShell console it
would ask for parameters (issue #897).
Fixes #897 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/898)
=> xSQLServer: Fix running tests locally in PowerShell console

CHANGELOG.md, DSCResources/MSFT_xSQLServerMaxDop/MSFT_xSQLServerMaxDop.psm1, DSCResources/MSFT_xSQLServerMaxDop/MSFT_xSQLServerMaxDop.schema.mof, Examples/Resources/xSQLServerMaxDop/2-SetMaxDopToAuto.ps1, README.md, Tests/Unit/MSFT_xSQLServerMaxDop.Tests.ps1
Made the resource cluster aware. When ProcessOnlyOnActiveNode is specified, the resource will only determine if a change is needed if the target node is the active host of the SQL Server instance
Fixes #882 
**Task List:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/901)
=> xSQLServerMaxDop: Added Cluster Aware code

CHANGELOG.md
- BREAKING CHANGE: Resource module has been renamed to SqlServerDsc (issue #916).
Fixes #916 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/919)
=> SqlServerDsc: Fix CHANGELOG.md after resource module rename

CHANGELOG.md, Examples/DSCClusterSqlBuild.ps1, Examples/DSCFCISqlBuild.ps1, Examples/DSCSQLBuildEncrypted.ps1, Examples/DSCSqlBuild.ps1, Examples/SQL-ClusterDB.ps1, Examples/SQL-Standalone.ps1, Examples/SQLPush_SingleServer.ps1
- The examples in the root of the Examples folder are obsolete. Those examples
now have a note saying so, in the comment-based help, until they can be replaced (issue #904).
Fixes #904 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/920)
=> SqlServerDsc: Adding note to obsolete examples

CHANGELOG.md, DSCResources/MSFT_SqlAGReplica/MSFT_SqlAGReplica.psm1, DSCResources/MSFT_SqlAGReplica/MSFT_SqlAGReplica.schema.mof, DSCResources/MSFT_SqlRS/MSFT_SqlRS.psm1, DSCResources/MSFT_SqlRS/MSFT_SqlRS.schema.mof, Examples/Resources/SqlAGDatabase/1-AddDatabaseToAvailabilityGroup.ps1, Examples/Resources/SqlAGDatabase/2-RemoveDatabaseFromAvailabilityGroup.ps1, Examples/Resources/SqlAGDatabase/3-MatchDefinedDatabaseInAvailabilityGroup.ps1, Examples/Resources/SqlAGReplica/1-CreateAvailabilityGroupReplica.ps1, Examples/Resources/SqlAGReplica/2-RemoveAvailabilityGroupReplica.ps1, Examples/Resources/SqlRS/1-DefaultConfiguration.ps1, Examples/Resources/SqlRS/2-CustomConfiguration.ps1, README.md, Tests/Integration/MSFT_SqlRS.Integration.Tests.ps1, Tests/Integration/MSFT_SqlRS.config.ps1, Tests/Unit/MSFT_SqlAGReplica.Tests.ps1, Tests/Unit/MSFT_SqlRS.Tests.ps1
- BREAKING CHANGE: Parameters RSSQLServer and RSSQLInstanceName has been renamed
to DatabaseServerName and DatabaseInstanceName respectively (issue #923).
- BREAKING CHANGE: Parameters PrimaryReplicaSQLServer and PrimaryReplicaSQLInstanceName
has been renamed to PrimaryReplicaServerName and PrimaryReplicaInstanceName
respectively (issue #922).
Fixes #922 
Fixes #923 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/932)
=> BREAKING CHANGE: Rename parameters for SqlRS and SqlAGReplica

CHANGELOG.md, DSCResources/MSFT_SqlAG/MSFT_SqlAG.psm1, DSCResources/MSFT_SqlAG/MSFT_SqlAG.schema.mof, DSCResources/MSFT_SqlAGReplica/MSFT_SqlAGReplica.psm1, DSCResources/MSFT_SqlAGReplica/MSFT_SqlAGReplica.schema.mof, README.md, Tests/Unit/MSFT_SqlAGReplica.Tests.ps1
- Changes to SqlAG
- BREAKING CHANGE: The read-only property SQLServerNetName was removed in favor of EndpointHostName (issue #924). Get-TargetResource will return the value of property [NetName](https://technet.microsoft.com/en-us/library/microsoft.sqlserver.management.smo.server.netname(v=sql.105).aspx)
as the default value if EndpointHostName parameter is not assigned a value.
- BREAKING CHANGE: The read-only property SQLServerNetName was removed in favor of EndpointHostName (issue #924). Get-TargetResource will return the value of property [NetName](https://technet.microsoft.com/en-us/library/microsoft.sqlserver.management.smo.server.netname(v=sql.105).aspx)
as the default value if EndpointHostName parameter is not assigned a …
=> SqlAg & SqlReplica: Removes SQLServerNetName in favor of EndpointHostName

CHANGELOG.md, Examples/Resources/SqlServerNetwork/1-EnableTcpIpWithStaticPort.ps1, Examples/Resources/SqlServerNetwork/2-EnableTcpIpWithDynamicPort.ps1
- Changes to SqlServerNetwork
- Added sysadmin account parameter usage to the examples.
***Note:** This continues the work that @pesetskyps started in PR #840.*
None
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/963)
=> SqlServerNetwork: Add PsDscRunAsCredential parameter to examples

CHANGELOG.md, Tests/Unit/MSFT_SqlAGListener.Tests.ps1, Tests/Unit/MSFT_SqlAlias.Tests.ps1, Tests/Unit/MSFT_SqlAlwaysOnService.Tests.ps1, Tests/Unit/MSFT_SqlDatabase.Tests.ps1, Tests/Unit/MSFT_SqlDatabaseDefaultLocation.Tests.ps1, Tests/Unit/MSFT_SqlDatabaseOwner.Tests.ps1, Tests/Unit/MSFT_SqlDatabasePermission.Tests.ps1, Tests/Unit/MSFT_SqlDatabaseRecoveryModel.Tests.ps1, Tests/Unit/MSFT_SqlDatabaseRole.Tests.ps1, Tests/Unit/MSFT_SqlRS.Tests.ps1, Tests/Unit/MSFT_SqlServerConfiguration.Tests.ps1, Tests/Unit/MSFT_SqlServerEndpoint.Tests.ps1, Tests/Unit/MSFT_SqlServerEndpointPermission.Tests.ps1, Tests/Unit/MSFT_SqlServerEndpointState.Tests.ps1, Tests/Unit/MSFT_SqlServerLogin.Tests.ps1, Tests/Unit/MSFT_SqlServerMaxDop.Tests.ps1, Tests/Unit/MSFT_SqlServerMemory.Tests.ps1, Tests/Unit/MSFT_SqlServerNetwork.Tests.ps1, Tests/Unit/MSFT_SqlServerRole.Tests.ps1, Tests/Unit/MSFT_SqlSetup.Tests.ps1, Tests/Unit/MSFT_SqlWindowsFirewall.Tests.ps1, Tests/Unit/SqlServerDSCHelper.Tests.ps1
- Changes to SqlServer
- Updated so that named parameters are used for New-Object cmdlet. This was
done to follow the style guideline.
n/a
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/974)
=> xSQLServer: Named parameters for New-Object cmdlet

CHANGELOG.md, LICENSE, SQLServerDsc.psd1
- Updated manifest and license to reflect the new year (issue #965).
Fixes #965 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/989)
=> SqlServerDsc: Update manifest and license to reflect new year

CHANGELOG.md, DSCResources/MSFT_SqlRS/MSFT_SqlRS.psm1, README.md, Tests/Unit/MSFT_SqlRS.Tests.ps1
- Replaced Get-WmiObject with Get-CimInstance to fix Script Analyzer warnings (issue #264).
- Refactored the resource to use Invoke-CimMethod.
Fixes #264 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/988)
=> SqlRS: Fix Script Analyzer warnings

CHANGELOG.md, CONTRIBUTING.md, DSCResources/MSFT_SqlServiceAccount/MSFT_SqlServiceAccount.psm1, DSCResources/MSFT_SqlServiceAccount/MSFT_SqlServiceAccount.schema.mof, DSCResources/MSFT_SqlServiceAccount/en-US/MSFT_SqlServiceAccount.strings.psd1, README.md, Tests/Integration/MSFT_SqlServiceAccount.Integration.Tests.ps1, Tests/Integration/MSFT_SqlServiceAccount.config.ps1, Tests/Integration/MSFT_SqlSetup.Integration.Tests.ps1, Tests/Integration/MSFT_SqlSetup.config.ps1, Tests/Integration/README.md, Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1
- Added a README.md under Tests\Integration to help contributors to write
integration tests.
- Added 'Integration tests' section in the CONTRIBUTING.md.
- Added a read-only parameter ServiceAccountName so that the service account
name is correctly returned as a string (issue #982).
- Added integration tests (issue #980).
- Cleaned up integration tests.
- Added integration tests for installing a default instance of Database Engine.
Fixes #980 
Fixes #982 
**Task list:**
--- …
=> SqlServiceAccount: Added integration tests (plus other changes)

CHANGELOG.md, README.md
- Updated README.md with known issue section for each resource.
- Resources that did not have a description in the README.md now has one.
- Resources that missed links to the examples in the README.md now has those
links.
- Changes to SqlServerEndpoint
- Updated README.md with links to the examples (issue #504).
Fixes #504 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/995)
=> SqlServerDsc: Updated README.md with a known issue section

CHANGELOG.md, DSCResources/MSFT_SqlServerRole/MSFT_SqlServerRole.psm1, DSCResources/MSFT_SqlServerRole/en-US/MSFT_SqlServerRole.strings.psd1, Tests/Integration/MSFT_SqlServerLogin.config.ps1, Tests/Integration/MSFT_SqlServerRole.Integration.Tests.ps1, Tests/Integration/MSFT_SqlServerRole.config.ps1, Tests/Integration/README.md, Tests/Unit/MSFT_SqlServerRole.Tests.ps1, en-US/SqlServerDscHelper.strings.psd1, sv-SE/SqlServerDscHelper.strings.psd1
- Changes to SqlServerRole
- Added localization (issue #621).
- Added integration tests (issue #756)
Fixes #621 
Fixes #756 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/996)
=> SqlServerRole: Added localization and integration tests

CHANGELOG.md, DSCResources/MSFT_SqlServerConfiguration/MSFT_SqlServerConfiguration.psm1, DSCResources/MSFT_SqlServerConfiguration/MSFT_SqlServerConfiguration.schema.mof, DSCResources/MSFT_SqlServerConfiguration/en-US/MSFT_SqlServerConfiguration.strings.psd1, README.md, Tests/Unit/MSFT_SqlServerConfiguration.Tests.ps1, en-US/SqlServerDscHelper.strings.psd1
- Changes to SqlServerConfiguration
- Now the verbose message say what option is changing and to what value (issue #1014).
- Changed the RestartTimeout parameter from type SInt32 to type UInt32.
- Added localization (issue #605).
Fixes #1014 
Fixes #605 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1021)
=> SqlServerConfiguration: Added localization and improved verbose messages

CHANGELOG.md, SqlServerDscHelper.psm1, Tests/Unit/SqlServerDSCHelper.Tests.ps1, en-US/SqlServerDscHelper.strings.psd1
- Now the helper function Restart-SqlService, after restarting the SQL Server
service, does not return until it can connect to the SQL Server instance, and
the instance returns status 'Online' (issue #1008).
If it fails to connect within the timeout period (defaults to 120 seconds) it
throws an error.
- The timing issue that the resource returned before SQL Server service was
actually restarted has been solved by a change in the helper function
Restart-SqlService ([issue #1008](https://github.com/PowerShell/SqlServerDsc/issues/1008)).
Now Restart-SqlService waits for the instance to return status 'Online' or
throws an error saying it failed to connect within the timeout period.
**This Pull Request …
=> SqlServerDsc: Fixes the timing issue with SqlServiceAccount

CHANGELOG.md, DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.psm1, README.md, Tests/Unit/MSFT_SqlSetup.Tests.ps1
- Now accounts containing '$' will be able to be used for installing
SQL Server. Although, if the account ends with '$' it is considered a
Managed Service Account (issue #1055).
Fixes #1055
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1060)
=> SqlSetup: Accounts containing '$' will be able to be used

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md
- Updated the PULL_REQUEST_TEMPLATE with an improved task list and
modified some text to be clearer (issue #973).
Fixes #973 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1062)
=> SqlServerDsc: Updated the PULL_REQUEST_TEMPLATE with an improved task list

.github/ISSUE_TEMPLATE.md, CHANGELOG.md
- Updated the ISSUE_TEMPLATE to hopefully be more intuitive and easier
to use.
- Added information to ISSUE_TEMPLATE that issues must be reproducible
in SqlServerDsc resource module (if running the older xSQLServer
resource module (issue #1036).
Fixes #1036 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1061)
=> SqlServerDsc: Updated ISSUE_TEMPLATE to hopefully be more intuitive

CHANGELOG.md, Tests/Unit/MSFT_SqlWaitForAG.Tests.ps1
Updated SqlWaitForAg unit tests to used latest unit test template.
Fixes #1088 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1100)
=> SqlWaitForAg: Updated unit tests to use latest unit test template

CHANGELOG.md, DSCResources/MSFT_SqlRS/MSFT_SqlRS.psm1, SqlServerDscHelper.psm1, Tests/Integration/MSFT_SqlAlwaysOnService.Integration.Tests.ps1, Tests/Integration/MSFT_SqlRS.Integration.Tests.ps1, Tests/Integration/MSFT_SqlRS.config.ps1, Tests/Integration/MSFT_SqlServiceAccount.Integration.Tests.ps1, Tests/Integration/MSFT_SqlServiceAccount.config.ps1, Tests/Integration/MSFT_SqlSetup.Integration.Tests.ps1, Tests/Integration/MSFT_SqlSetup.config.ps1, Tests/Integration/README.md, Tests/Unit/SqlServerDSCHelper.Tests.ps1, appveyor.yml, en-US/SqlServerDscHelper.strings.psd1
- Minor code cleanup in integration test, fixed the scope on variable.
- Updated the integration tests to stop some services after each integration test.
This is to save memory on the AppVeyor build worker.
- Updated the integration tests to use a SQL Server 2016 Service Pack 1.
- Updated the integration tests to stop the Reporting Services service after
the integration test. This is to save memory on the AppVeyor build worker.
- The helper function `Restart-ReportingServicesService` should no longer timeout
when restarting the service ([issue #1114](https://github.com/PowerShell/SqlServerDsc/issues/1114)).
- Updated the integration tests to stop some services after each integration …
=> SqlServerDsc: Stop instances in integration tests

CHANGELOG.md, CODE_OF_CONDUCT.md, README.md
- Added a CODE\_OF\_CONDUCT.md with the same content as in the README.md (issue #939).
Fixes #939 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/940)
=> SqlServerDsc: Add a CODE_OF_CONDUCT.md

CHANGELOG.md, DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.psm1, Tests/Unit/MSFT_SqlSetup.Tests.ps1
Enabling Robocopy to use paths containing spaces (https://github.com/PowerShell/SqlServerDsc/issues/779)
SqlSetup: MSFT_SqlSetup.psm1 enable Robocopy to use paths containing spaces
Fixes #779 
- [x ] New/changed code adheres to
---
This change is [<img …
=> SqlSetup: MSFT_SqlSetup.psm1 enable Robocopy to use paths containing spaces

CHANGELOG.md, Tests/Integration/MSFT_SqlAlwaysOnService.config.ps1
- Integration tests was updated to handle new IPv6 addresses on the AppVeyor
build worker (issue #1155)
Fixes #1155
--- …
=> SqlAlwaysOnService: Resolve failing integration test

CHANGELOG.md, DSCResources/MSFT_SqlServerNetwork/MSFT_SqlServerNetwork.psm1, SqlServerDscHelper.psm1, Tests/Integration/MSFT_SqlServerNetwork.Integration.Tests.ps1, Tests/Integration/MSFT_SqlServerNetwork.config.ps1, Tests/Unit/MSFT_SqlServerNetwork.Tests.ps1, Tests/Unit/SqlServerDSCHelper.Tests.ps1, en-US/SqlServerDscHelper.strings.psd1, sv-SE/SqlServerDscHelper.strings.psd1
- Updated helper function Restart-SqlService to have to new optional parameters
`SkipClusterCheck` and `SkipWaitForOnline`. This was to support more aspects
of the resource SqlServerNetwork.
- Changes to SqlServerNetwork
- Refactor SqlServerNetwork to not load assembly from GAC (issue #1151).
- The resource now supports restarting the SQL Server service when both
enabling and disabling the protocol.
- Added integration tests for this resource
(issue #751).
Helps with issue #1151
Fixes #1051 (closing this since the issue is around code that has been removed).
Fixes #751 
Fixes #581 (closing this since the issue is around code that has been removed).
See [DSC Resource …
=> SqlServerNetwork: Refactored to not load assembly from GAC

CHANGELOG.md, DSCResources/MSFT_SqlAG/MSFT_SqlAG.psm1, DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.psm1, SqlServerDscHelper.psm1, Tests/Unit/MSFT_SqlAG.Tests.ps1, Tests/Unit/MSFT_SqlSetup.Tests.ps1, Tests/Unit/SqlServerDSCHelper.Tests.ps1, en-US/SqlServerDscHelper.strings.psd1, sv-SE/SqlServerDscHelper.strings.psd1
- Updated helper function `Import-SQLPSModule`
- To only import module if the
module does not exist in the session.
- To always import the latest version of 'SqlServer' or 'SQLPS' module, if
more than one version exist on the target node. It will still prefer to
use 'SqlServer' module.
- Changes to SqlAG
- Removed excess `Import-SQLPSModule` call.
- Now after a successful install the "SQL PowerShell module" is reevaluated and
forced to be reimported into the session. This is to support that a never
version of SQL Server was installed side-by-side so that SQLPS module should
be used instead.
Helps with issue #1151 
See [DSC Resource Testing …
=> SqlServerDsc: Improvement to how Import-SQLPSModule import module

CHANGELOG.md, Examples/Resources/SqlAG/1-CreateAvailabilityGroup.ps1, Examples/Resources/SqlAG/2-RemoveAvailabilityGroup.ps1, Examples/Resources/SqlAG/3-CreateAvailabilityGroupDetailed.ps1, Examples/Resources/SqlAGDatabase/1-AddDatabaseToAvailabilityGroup.ps1, Examples/Resources/SqlAGDatabase/2-RemoveDatabaseFromAvailabilityGroup.ps1, Examples/Resources/SqlAGDatabase/3-MatchDefinedDatabaseInAvailabilityGroup.ps1, Examples/Resources/SqlAGReplica/1-CreateAvailabilityGroupReplica.ps1, Examples/Resources/SqlAGReplica/2-RemoveAvailabilityGroupReplica.ps1, Examples/Resources/SqlRS/4-CompleteWithTwoInstances.ps1, Examples/Resources/SqlScript/3-RunScriptCompleteExample.ps1, Examples/Resources/SqlScriptQuery/3-RunScriptCompleteExample.ps1, Examples/Resources/SqlServerDatabaseMail/1-EnableDatabaseMail.ps1, Examples/Resources/SqlServerDatabaseMail/2-DisableDatabaseMail.ps1, Examples/Resources/SqlServerEndpointPermission/3-AddConnectPermissionToTwoReplicasEachWithDifferentServiceAccount.ps1, Examples/Resources/SqlServerEndpointPermission/4-RemoveConnectPermissionForTwoReplicasEachWithDifferentServiceAccount.ps1, Tests/Integration/MSFT_SqlAlwaysOnService.config.ps1, Tests/Integration/MSFT_SqlDatabaseDefaultLocation.config.ps1, Tests/Integration/MSFT_SqlRS.config.ps1, Tests/Integration/MSFT_SqlScript.config.ps1, Tests/Integration/MSFT_SqlScriptQuery.config.ps1, Tests/Integration/MSFT_SqlServerDatabaseMail.config.ps1, Tests/Integration/MSFT_SqlServerLogin.config.ps1, Tests/Integration/MSFT_SqlServerNetwork.config.ps1, Tests/Integration/MSFT_SqlServerRole.config.ps1, Tests/Integration/MSFT_SqlServiceAccount.config.ps1, Tests/Integration/MSFT_SqlSetup.config.ps1
- Updated all the examples and integration tests to not use `PSDscAllowPlainTextPassword`,
so examples using credentials or passwords by default are secure.
n/a
--- …
=> SqlServerDsc: Configurations are no longer using PSDscAllowPlainTextPassword

CHANGELOG.md, DSCResources/MSFT_SqlDatabaseOwner/MSFT_SqlDatabaseOwner.psm1, DSCResources/MSFT_SqlDatabaseOwner/MSFT_SqlDatabaseOwner.schema.mof, Examples/Resources/SqlDatabaseOwner/1-SetDatabaseOwner.ps1, README.md, Tests/Unit/MSFT_SqlDatabaseOwner.Tests.ps1
Support multi-instances
Fixes #1197
- [ x ] Added an entry under the Unreleased section in the CHANGELOG.md? Entry
- [ x ] Resource parameter descriptions added/updated in README.md, schema.mof
---
This change is [<img src="https://reviewable.io/review_button.svg" …
=> BREAKING CHANGE: SqlDatabaseOwner: Support multi-instances

CHANGELOG.md, DSCResources/MSFT_SqlServerDatabaseMail/MSFT_SqlServerDatabaseMail.psm1, DSCResources/MSFT_SqlServerDatabaseMail/MSFT_SqlServerDatabaseMail.schema.mof, README.md
DisplayName is used for the display name of the email address, for example, the "SQL Server" part of a `From: "SQL Server" <mssql@example.com>` header. This was incorrectly indicated to be a display name for the mail server FQDN.
Also clarified some description and name fields. Tried to catch this in the psm1 file as well as the readme.
I also reordered the parameters listed in the readme for this resource since they seemed a bit random before.
[DSC Resource Style …
=> SqlServerDatabaseMail: Corrected and reorganized documentation

CHANGELOG.md, Examples/Resources/SqlAG/1-CreateAvailabilityGroup.ps1, Examples/Resources/SqlAG/3-CreateAvailabilityGroupDetailed.ps1, Examples/Resources/SqlAGDatabase/1-AddDatabaseToAvailabilityGroup.ps1, Examples/Resources/SqlAGDatabase/3-MatchDefinedDatabaseInAvailabilityGroup.ps1, Examples/Resources/SqlAGReplica/1-CreateAvailabilityGroupReplica.ps1, Examples/Resources/SqlAGReplica/2-RemoveAvailabilityGroupReplica.ps1
Updating examples to include enabling the HADR option for SQL Server.
Fixes #1182 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1208)
=> SqlAG/SqlAGDatabase/SqlAGReplica - Updating examples to include enable HADR option

CHANGELOG.md, Tests/Unit/Stubs/Write-ModuleStubFile.ps1
When a stub file is created for a module, also create the aliases for the cmdlets within the module.
Fixes #1224
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1225)
=> Write-ModuleStubFile: Add Aliases for Functions

CHANGELOG.md, Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1
- Fix unit tests that didn't mock some of the calls. It no longer fail
when a SQL Server installation is not present on the node running the
unit test (issue #983).
- Fixes #983 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1235)
=> SqlServiceAccount: Fix unit tests that didn't mock some of the calls

CHANGELOG.md, appveyor.yml
- During testing in AppVeyor the Build Worker is restarted in the install
step to make sure the are no residual changes left from a previous SQL
Server install on the Build Worker done by the AppVeyor Team (issue #1260).
- Fixes #1260 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1262)
=> SqlServerDsc: Fixes integration test fail to install default instance

CHANGELOG.md, DSCResources/MSFT_SqlServerLogin/MSFT_SqlServerLogin.psm1, Tests/Unit/MSFT_SqlServerLogin.Tests.ps1
Addresses issue #1096 where when a login doesn't exist there are null values in the verbose output from the test function by skipping that output if the login is absent and expected to be present.
Fixes #1096 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1240)
=> SqlServerLogin: Addresses issue #1096 - doesn't check properties if login is not present on server

CHANGELOG.md, DSCResources/MSFT_SqlServerLogin/MSFT_SqlServerLogin.psm1, README.md, Tests/Unit/MSFT_SqlServerLogin.Tests.ps1
- Changes to SqlServerLogin
- Now when adding a login of type SqlLogin, and the SQL Server login mode
is set to `'Integrated'`, an error is correctly thrown
([issue #1179](https://github.com/PowerShell/SqlServerDsc/issues/1179)).
- Fixes #1179
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1266)
=> SqlServerLogin: Error is thrown when SqlLogin is run in Integrated mode

CHANGELOG.md, DSCResources/MSFT_SqlServerMemory/MSFT_SqlServerMemory.psm1, Tests/Unit/MSFT_SqlServerMemory.Tests.ps1
Updated Cim Class to Win32_ComputerSystem (instead of Win32_PhysicalMemory) because the correct memory size was not being detected correctly on Azure VMs
Fixes #914
Fixes #1154
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1285)
=> SqlServerMemory: Fix so auto memory on Azure VMs is reported correctly

CHANGELOG.md, DSCResources/MSFT_SqlAG/MSFT_SqlAG.psm1, DSCResources/MSFT_SqlAGReplica/MSFT_SqlAGReplica.psm1, DSCResources/MSFT_SqlServerEndpointPermission/MSFT_SqlServerEndpointPermission.psm1, Examples/Resources/SqlAG/3-CreateAvailabilityGroupDetailed.ps1, Tests/Unit/MSFT_SqlAGReplica.Tests.ps1, Tests/Unit/MSFT_SqlServerPermission.Tests.ps1, Tests/Unit/MSFT_SqlServerSecureConnection.Tests.ps1
This fixes the Test-Resource portion of SqlAGReplica so that it compares read only routing lists properly. This allows desired state to be reached.
I added no entry in CHANGELOG as it's fixing the unreleased feature.
In the unit tests I modified the read only routing list defaults. Using an array instead of a single server name here causes the tests to fail on the old code (as they should) and pass on the new code (as they should). 
In the unit tests I also added another section to confirm that the test resource passes when nothing has changed. This also picked up the old bad code and passes on the new code.
Finally I did a search replace of $True and $False.
- Fixes #1305
---
This …
=> SqlAGReplica: Fix read-only routing list reaching desired state

CHANGELOG.md, DSCResources/MSFT_SqlServerMemory/MSFT_SqlServerMemory.psm1, DSCResources/MSFT_SqlServerMemory/en-US/MSFT_SqlServerMemory.strings.psd1, Modules/DscResource.Common/en-US/DscResource.Common.strings.psd1, Modules/DscResource.Common/sv-SE/DscResource.Common.strings.psd1, Tests/Unit/MSFT_SqlServerMemory.Tests.ps1
- Changes to SqlServerMemory
- Added en-US localization (issue #617).
- No longer will the resource set the MinMemory value if it was provided
in a configuration that also set the `Ensure` parameter to 'Absent' (issue #1329).
- Refactored unit tests to simplify them add add slightly more code
coverage.
- Fixes #617
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1330)
=> SqlServerMemory: Localization, unit tests and fix bug

CHANGELOG.md, DSCResources/MSFT_SqlRS/MSFT_SqlRS.psm1, DSCResources/MSFT_SqlRS/en-US/MSFT_SqlRS.strings.psd1, DSCResources/MSFT_SqlRS/en-US/MSFT_SqlRSSetup.strings.psd1, DSCResources/MSFT_SqlRSSetup/en-US/MSFT_SqlRSSetup.strings.psd1, DSCResources/MSFT_SqlSetup/en-US/MSFT_SqlSetup.strings.psd1, DSCResources/MSFT_SqlSetup/sv-SE/MSFT_SqlSetup.strings.psd1, DSCResources/MSFT_SqlWindowsFirewall/MSFT_SqlWindowsFirewall.psm1, DSCResources/MSFT_SqlWindowsFirewall/en-US/MSFT_SqlWindowsFirewall.strings.psd1, Modules/DscResource.Common/en-US/DscResource.Common.strings.psd1, Modules/DscResource.Common/sv-SE/DscResource.Common.strings.psd1, Tests/Unit/MSFT_SqlRS.Tests.ps1, Tests/Unit/MSFT_SqlWindowsFirewall.Tests.ps1
- Made the error message more descriptive when the Set-TargetResource
function calls the Test-TargetResource function to verify the desired
state.
- Changes to SqlWindowsFirewall
- Added en-US localization (issue #614).
- Fixed one of the error handling to use localization, and made the
error message more descriptive when the Set-TargetResource function
calls the Test-TargetResource function to verify the desired
state. *This was done prior to adding full en-US localization.*
- Fixes #614 
--- …
=> SqlWindowsFirewall: Added localization

CHANGELOG.md, DSCResources/MSFT_SqlDatabaseRecoveryModel/MSFT_SqlDatabaseRecoveryModel.psm1, DSCResources/MSFT_SqlDatabaseRecoveryModel/en-US/MSFT_SqlDatabaseRecoveryModel.strings.psd1, Tests/Unit/MSFT_SqlDatabaseRecoveryModel.Tests.ps1
- Changes to SqlDatabaseRecoveryModel
- Added en-US localization (issue #609).
- Fixes #609 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1340)
=> SqlDatabaseRecoveryModel: Added localization

CHANGELOG.md, DSCResources/MSFT_SqlDatabasePermission/MSFT_SqlDatabasePermission.psm1, DSCResources/MSFT_SqlDatabasePermission/en-US/MSFT_SqlDatabasePermission.strings.psd1, Modules/DscResource.Common/en-US/DscResource.Common.strings.psd1, Modules/DscResource.Common/sv-SE/DscResource.Common.strings.psd1, Tests/Unit/MSFT_SqlDatabasePermission.Tests.ps1
- Changes to SqlDatabasePermission
- Added en-US localization (issue #608).
- Fixes #608 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1341)
=> SqlDatabasePermission: Added localization

CHANGELOG.md, DSCResources/MSFT_SqlDatabase/MSFT_SqlDatabase.psm1, DSCResources/MSFT_SqlDatabase/en-US/MSFT_SqlDatabase.strings.psd1, Modules/DscResource.Common/en-US/DscResource.Common.strings.psd1, Modules/DscResource.Common/sv-SE/DscResource.Common.strings.psd1, Tests/Unit/MSFT_SqlDatabase.Tests.ps1
- Changes to SqlDatabase
- Added en-US localization (issue #606).
- Fixes #606
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1345)
=> SqlDatabase: Added localization

CHANGELOG.md, DSCResources/MSFT_SqlServerReplication/MSFT_SqlServerReplication.psm1, DSCResources/MSFT_SqlServerReplication/en-US/MSFT_SqlServerReplication.strings.psd1, Tests/Unit/MSFT_SqlServerReplication.Tests.ps1
- Changes to SqlServerReplication
- Added en-US localization (issue #620).
- Fixes #620 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1327)
=> SqlServerReplication: Added localization

CHANGELOG.md, DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.psm1, DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.schema.mof, README.md, Tests/Unit/MSFT_SqlSetup.Tests.ps1
Added RSInstallMode parameter, to support RSINSTALLMODE SQL Setup config option.
- Fixes a part of #1163 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1361)
=> SqlSetup: Added support for RSINSTALLMODE parameter

CHANGELOG.md, Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1, Tests/Unit/SqlServerDsc.Common.Tests.ps1
Fixes #1355
Closes #1356
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1380)
=> Invoke-query updated to allow smo object

CHANGELOG.md, Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1, Modules/SqlServerDsc.Common/en-US/SqlServerDsc.Common.strings.psd1, Modules/SqlServerDsc.Common/sv-SE/SqlServerDsc.Common.strings.psd1, Tests/Unit/SqlServerDsc.Common.Tests.ps1
- Changes to helper function Invoke-Query
- Now it will output verbose messages of the query that is run, so it
not as quiet of what it is doing when a user asks for verbose output (issue #1404).
- It is possible to redact text in the verbose output by providing
strings in the new parameter `RedactText`.
- Fixes #1404 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1407)
=> SqlServerDsc: Changes to Invoke-Query

CHANGELOG.md, DSCResources/MSFT_SqlAGDatabase/MSFT_SqlAGDatabase.psm1, DSCResources/MSFT_SqlAlwaysOnService/MSFT_SqlAlwaysOnService.psm1, DSCResources/MSFT_SqlDatabaseDefaultLocation/MSFT_SqlDatabaseDefaultLocation.psm1, DSCResources/MSFT_SqlRS/MSFT_SqlRS.psm1, DSCResources/MSFT_SqlServerConfiguration/MSFT_SqlServerConfiguration.psm1, DSCResources/MSFT_SqlServerNetwork/MSFT_SqlServerNetwork.psm1, DSCResources/MSFT_SqlServerSecureConnection/MSFT_SqlServerSecureConnection.psm1, DSCResources/MSFT_SqlServiceAccount/MSFT_SqlServiceAccount.psm1, DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.psm1, Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1, Tests/Unit/SqlServerDsc.Common.Tests.ps1
- Changes to helper function Invoke-Query
- Parameters now match that of Connect-SQL (issue #1392).
- Changes to helper function Connect-SQLAnalysis
- Parameters now match that of Connect-SQL (issue #1392).
- Changes to helper function Restart-SqlService
- Parameters now match that of Connect-SQL (issue #1392).
- Changes to helper function Restart-ReportingServicesService
- Parameters now match that of Connect-SQL (issue #1392).
- Changes to helper function Split-FullSqlInstanceName
- Parameters and function name changed to use correct casing.
- Changes to helper function Get-SqlInstanceMajorVersion
- Parameters now match that of Connect-SQL (issue #1392).
- Changes to helper function Test-LoginEffectivePermissions
- Parameters now match that of Connect-SQL …
=> SqlServerDsc: Consequently use parameters ServerName and InstanceName

CHANGELOG.md, DSCResources/MSFT_SqlAgentFailsafe/MSFT_SqlAgentFailsafe.psm1, DSCResources/MSFT_SqlAgentFailsafe/MSFT_SqlAgentFailsafe.schema.mof, DSCResources/MSFT_SqlAgentFailsafe/en-US/MSFT_SqlAgentFailsafe.strings.psd1, Examples/Resources/SqlAgentFailsafe/1-AddFailsafe.ps1, Examples/Resources/SqlAgentFailsafe/2-RemoveFailsafe.ps1, README.md, Tests/Integration/MSFT_SqlAgentFailsafe.Integration.Tests.ps1, Tests/Integration/MSFT_SqlAgentFailsafe.config.ps1, Tests/Unit/MSFT_SqlAgentFailsafe.Tests.ps1
Adds the `SqlAgentFailsafe` resource, to allow you to manage adding a failsafe operator to the agent alert system, and choosing the notification:
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1414)
=> SqlAgentFailsafe: Adding resource to manage Agent Failsafe Operator

CHANGELOG.md, source/DSCResources/MSFT_SqlAGListener/MSFT_SqlAGListener.psm1, tests/Unit/MSFT_SqlAGListener.Tests.ps1
This fixes Get-TargetResource to correctly format IPv4 and IPv6 addresses in Test-TargetResource.
Because v6 addresses are input without a subnet mask, any v6 addresses had '/' appended to the end of the address with an empty subnet.
DSC would fail any run after the listener was created as the desired v6 IP would be 'f000::ba7' but the test would be expecting 'f000::ba7/'
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1444)
=> SqlAgListener: Fix v6 IPs failing Test-TargetResource

CHANGELOG.md, source/DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.psm1, tests/Unit/MSFT_SqlSetup.Tests.ps1
…resolve setup.exe path
Execute `Get-PSDrive` to refresh PowerShell drive list before attempting to resolve full path to `setup.exe`.
- Fixes #1482 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1483)
=> SqlSetup: Refresh PowerShell drive list before resolving setup.exe path

CHANGELOG.md, GitVersion.yml, README.md, RequiredModules.psd1, azure-pipelines.yml, source/DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.psm1, source/DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.schema.mof, source/DSCResources/MSFT_SqlSetup/en-US/MSFT_SqlSetup.strings.psd1, source/DSCResources/MSFT_SqlSetup/sv-SE/MSFT_SqlSetup.strings.psd1, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1, tests/Integration/MSFT_SqlSetup.Integration.Tests.ps1, tests/Unit/MSFT_SqlSetup.Tests.ps1
- SqlServerDsc
- The regular expression for `minor-version-bump-message` in the file
`GitVersion.yml` was changed to only raise minor version when the
commit message contain the word `add`, `adds`, `minor`, `feature`,
or `features`.
- SqlSetup
- BREAKING CHANGE: Logic that was under feature flag `DetectionSharedFeatures`
was made the default and old logic that was used to detect shared features
was removed ([issue #1290](https://github.com/dsccommunity/SqlServerDsc/issues/1290)).
This was implemented because the previous implementation did not work
fully with SQL Server 2017.
- Much of the code was refactored into units (functions) to be easier to test.
Due to the size of the code the unit tests ran for an abnormal long time,
after this refactoring the unit tests runs much quicker.
- The …
=> BREAKING CHANGE: SqlSetup: Refactored to speed up testing

.github/stale.yml, CHANGELOG.md, README.md, azure-pipelines.yml, source/DSCResources/DSC_SqlServerProtocol/DSC_SqlServerProtocol.psm1, source/DSCResources/DSC_SqlServerProtocol/DSC_SqlServerProtocol.schema.mof, source/DSCResources/DSC_SqlServerProtocol/README.md, source/DSCResources/DSC_SqlServerProtocol/en-US/DSC_SqlServerProtocol.strings.psd1, source/Examples/Resources/SqlServerProtocol/1-EnableTcpIp.ps1, source/Examples/Resources/SqlServerProtocol/2-EnableNamedPipes.ps1, source/Examples/Resources/SqlServerProtocol/3-EnableSharedMemory.ps1, source/Examples/Resources/SqlServerProtocol/4-DisableTcpIp.ps1, source/Examples/Resources/SqlServerProtocol/5-DisableNamedPipes.ps1, source/Examples/Resources/SqlServerProtocol/6-DisableSharedMemory.ps1, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psd1, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1, source/Modules/SqlServerDsc.Common/en-US/SqlServerDsc.Common.strings.psd1, source/Modules/SqlServerDsc.Common/sv-SE/SqlServerDsc.Common.strings.psd1, source/SqlServerDsc.psd1, tests/Integration/DSC_SqlServerProtocol.Integration.Tests.ps1, tests/Integration/DSC_SqlServerProtocol.config.ps1, tests/Integration/MSFT_SqlServerProtocol.Integration.Tests.ps1, tests/Integration/MSFT_SqlServerProtocol.config.ps1, tests/Unit/DSC_SqlServerProtocol.Tests.ps1, tests/Unit/SqlServerDsc.Common.Tests.ps1
- SqlServerDsc
- Added new resource SqlServerProtocol (issue #1377).
- When a PR is labelled with 'ready for merge' it is no longer being
marked as stale if the PR is not merged for 30 days (for example it is
dependent on something else) (issue #1504).
- Updated the CI pipeline to use latest version of the module ModuleBuilder.
- The helper function `Restart-SqlService` was improved to handle Failover
Clusters better. Now the SQL Server service will only be taken offline
and back online again if the service is online to begin with.
- The helper function `Restart-SqlServer` learned the new parameter
`OwnerNode`. The parameter `OwnerNode` takes an array of Cluster node
names. Using this parameter the cluster group will only be taken
offline and back online if the …
=> SqlServerProtocol: New resource proposal

CHANGELOG.md, azure-pipelines.yml, source/DSCResources/DSC_SqlServerReplication/DSC_SqlServerReplication.psm1, source/DSCResources/DSC_SqlServerReplication/en-US/DSC_SqlServerReplication.strings.psd1, source/Examples/Resources/SqlServerReplication/1-ConfigureInstanceAsDistributor.ps1, source/Examples/Resources/SqlServerReplication/2-ConfigureInstanceAsPublisher.ps1, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1, tests/Integration/DSC_SqlServerReplication.Integration.Tests.ps1, tests/Integration/DSC_SqlServerReplication.config.ps1, tests/Integration/DSC_SqlSetup.config.ps1, tests/Integration/README.md, tests/Unit/SqlServerDsc.Common.Tests.ps1
- SqlServerDsc
- The CI pipeline now uses the latest version of the module ModuleBuilder.
- The unit tests now run on PowerShell 7 to optimize the total run time.
- Fixes #755 
- Fixes #1513 
- Fixes #1530
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1524)
=> SqlServerDsc: Unit tests run in PowerShell 7

CHANGELOG.md, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1
- Removed the local helper function `Set-PSModulePath` as it was
implemented in the module DscResource.Common.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1551)
=> SqlServerDsc: Remove function Set-PSModulePath

CHANGELOG.md, README.md, azure-pipelines.yml, source/DSCResources/DSC_SqlDatabasePermission/DSC_SqlDatabasePermission.psm1, source/DSCResources/DSC_SqlDatabasePermission/en-US/DSC_SqlDatabasePermission.strings.psd1, source/Examples/Resources/SqlDatabasePermission/1-GrantDatabasePermissions.ps1, source/Examples/Resources/SqlDatabasePermission/2-RevokeDatabasePermissions.ps1, source/Examples/Resources/SqlDatabasePermission/3-DenyDatabasePermissions.ps1, tests/Integration/DSC_SqlDatabasePermission.Integration.Tests.ps1, tests/Integration/DSC_SqlDatabasePermission.config.ps1, tests/Integration/DSC_SqlServerProtocolTcpIp.config.ps1, tests/Integration/README.md, tests/Unit/DSC_SqlDatabasePermission.Tests.ps1
- SqlDatabasePermission
- BREAKING CHANGE: The resource no longer create the database user if
it does not exist. Use the resource _SqlDatabaseUser_ to enforce that
the database user exist in the database prior to setting permissions
using this resource (issue #848).
- BREAKING CHANGE: The resource no longer checks if a login exist so that
it is possible to set permissions for database users that does not
have a login, e.g. the database user 'guest' (issue #1134).
- Updated examples.
- Added integration tests (issue #741).
- Get-TargetResource will no longer throw an exception if the database
does not exist.
- Fixes #741
- Fixes #848
- Fixes #1134
(if …
=> BREAKING CHANGE: SqlDatabasePermission: Remove create user

CHANGELOG.md, README.md, source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.psm1, source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.schema.mof, source/Examples/Resources/SqlSetup/8-UsingSkipRuleDuringInstall.ps1, tests/Integration/DSC_SqlSetup.config.ps1, tests/TestHelpers/CommonTestHelper.psm1, tests/Unit/DSC_SqlSetup.Tests.ps1
- SqlSetup
- BREAKING CHANGE: When installing a failover cluster the cluster
validation is no longer skipped by default. To skip cluster validation
the configuration must opt-in by specifying the following
`SkipRule = 'Cluster_VerifyForErrors'` (issue #335).
- Fixes #335
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1554)
=> BREAKING CHANGE: SqlSetup: Remove default skip cluster validation

.vscode/analyzersettings.psd1, CHANGELOG.md, README.md, azure-pipelines.yml, source/DSCResources/DSC_SqlDatabaseObjectPermission/DSC_SqlDatabaseObjectPermission.psm1, source/DSCResources/DSC_SqlDatabaseObjectPermission/DSC_SqlDatabaseObjectPermission.schema.mof, source/DSCResources/DSC_SqlDatabaseObjectPermission/README.md, source/DSCResources/DSC_SqlDatabaseObjectPermission/en-US/DSC_SqlDatabaseObjectPermission.strings.psd1, source/Examples/Resources/SqlDatabaseObjectPermission/1-AddDatabaseObjectPermissions.ps1, source/Examples/Resources/SqlDatabaseObjectPermission/2-RemoveDatabaseObjectPermissions.ps1, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1, source/Modules/SqlServerDsc.Common/en-US/SqlServerDsc.Common.strings.psd1, source/Modules/SqlServerDsc.Common/sv-SE/SqlServerDsc.Common.strings.psd1, tests/Integration/DSC_SqlDatabaseObjectPermission.Integration.Tests.ps1, tests/Integration/DSC_SqlDatabaseObjectPermission.config.ps1, tests/Integration/README.md, tests/Unit/DSC_SqlDatabaseObjectPermission.Tests.ps1, tests/Unit/DSC_SqlProtocolTcpIp.Tests.ps1, tests/Unit/SqlServerDsc.Common.Tests.ps1
- SqlServerDsc
- Added new resource SqlDatabaseObjectPermission (issue #1119).
- The helper function `Compare-ResourcePropertyState` was improved to
handle embedded instances by adding a parameter `CimInstanceKeyProperties`
that can be used to identify the unique parameter for each embedded
instance in a collection.
- The helper function `Test-DscPropertyState` was improved to evaluate
the properties in a single CIM instance or a collection of CIM instances
by recursively call itself.
- When the helper function `Test-DscPropertyState` evaluated an array
the verbose messages was not very descriptive. Instead of outputting
the side indicator from the compare it now outputs a descriptive
message.
- Fixes #1119
file CHANGELOG.md. Entry should say what was changed and how …
=> SqlDatabaseObjectPermission: New resource

CHANGELOG.md, source/DSCResources/DSC_SqlWindowsFirewall/DSC_SqlWindowsFirewall.psm1, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1, tests/Unit/DSC_SqlWindowsFirewall.Tests.ps1, tests/Unit/SqlServerDsc.Common.Tests.ps1
- Connect-UncPath
- Now support to authenticate using both NetBIOS domain and Fully Qualified
Domain Name (FQDN) (issue #1223).
- Connect-SQL
- Now support to authenticate using both NetBIOS domain and Fully Qualified
Domain Name (FQDN) (issue #1223).
- Connect-SQLAnalysis
- Now support to authenticate using both NetBIOS domain and Fully Qualified
Domain Name (FQDN) (issue #1223).
- SqlWindowsFirewall
- Now support to authenticate using both NetBIOS domain and Fully Qualified
Domain Name (FQDN) (issue #1223).
- Fixes #1223
---
This change is [<img src="https://reviewable.io/review_button.svg" …
=> SqlServerDsc: Supports authenticate using both NetBIOS and FQDN

CHANGELOG.md, source/DSCResources/DSC_SqlSetup/README.md
- SqlSetup
- Documented that on certain operating systems, when using least privilege
for the service account, the security policy setting _Network access: Restrict_
_clients allowed to make remote calls to SAM_ can result in a access denied
error during install of the _SQL Server Database Engine_ (issue #1559).
- Fixes #1559
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1591)
=> SqlSetup: Update requirements section

CHANGELOG.md, source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1
Fixed: 
* The `ServerName` paramer is optional and defaults to `$env:COMPUTERNAME`, but `Test-TargetResource` uses the `$PSBoundParameters` automatic variable which ignores default values for parameters. Looks like this was fixed by #1503 in several other places such as `SqlDatabasePermission` but was missed here.
- Fixes #1592
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1597)
=> SqlRole: Fix default for ServerName

CHANGELOG.md, build.yaml, source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.psm1, source/DSCResources/DSC_SqlWindowsFirewall/DSC_SqlWindowsFirewall.psm1, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psd1, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1, tests/Unit/DSC_SqlSetup.Tests.ps1, tests/Unit/DSC_SqlWindowsFirewall.Tests.ps1, tests/Unit/SqlServerDsc.Common.Tests.ps1
- SqlServerDsc
- Document changes in the file `build.yml`.
- SqlSetup
- Duplicate function Get-SqlMajorVersion was removed and instead the
helper function Get-FilePathMajorVersion from the helper module
SqlServerDsc.Common is used (issue #1178).
- SqlWindowsFirewall
- Duplicate function Get-SqlMajorVersion was removed and instead the
helper function Get-FilePathMajorVersio` from the helper module
SqlServerDsc.Common is used (issue #1178).
- Function Get-FilePathMajorVersion was added. The function Get-SqlMajorVersion
from the resources SqlSetup and SqlWindowsFirewall was moved and
renamed without any functional changes (issue #1178).
- Fixes #1178
affects users (if applicable), and reference the issue …
=> SqlSetup,SqlWindowsFirewall: Fix duplicate function

CHANGELOG.md, source/Examples/Resources/SqlSetup/4-InstallNamedInstanceInFailoverClusterFirstNode.ps1
- SqlSetup
- The example `4-InstallNamedInstanceInFailoverClusterFirstNode.ps1` was
updated to no longer reference the issue #405 and issue #444 in the
comment-based help. The issues was fixed a while back and _SqlSetup_
now supports the built-in parameter `PsDscRunAsCredential` (issue #975).
- Fixes #975
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1609)
=> SqlSetup: Update comment-based help in example

CHANGELOG.md, source/DSCResources/DSC_SqlDatabaseObjectPermission/DSC_SqlDatabaseObjectPermission.psm1, source/DSCResources/DSC_SqlDatabaseObjectPermission/DSC_SqlDatabaseObjectPermission.schema.mof, source/DSCResources/DSC_SqlDatabaseObjectPermission/en-US/DSC_SqlDatabaseObjectPermission.strings.psd1, tests/Integration/DSC_SqlDatabaseObjectPermission.Integration.Tests.ps1, tests/Integration/DSC_SqlDatabaseObjectPermission.config.ps1, tests/Unit/DSC_SqlDatabaseObjectPermission.Tests.ps1
SqlDatabaseObjectPermission
Setting table permission from "GrantWithGrant" to "Grant" still results in "GrantWithGrant" permissions configured
Fixes #1602  
- [X ] Added an entry to the change log under the Unreleased section of the
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1603)
=> SqlDatabaseObjectPermission: Fix transition "GrantWithGrant" to "Grant"

CHANGELOG.md, source/DSCResources/DSC_SqlReplication/DSC_SqlReplication.psm1, source/DSCResources/DSC_SqlReplication/en-US/DSC_SqlReplication.strings.psd1, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1, tests/Unit/DSC_SqlReplication.Tests.ps1
- SqlServerDsc
- Updated code formatting using latest release of PSScriptAnalyzer.
- The URLs in the CHANGELOG.md that was pointing to issues is now
referencing the new repository name and URL.
- The helper function `Get-SqlInstanceMajorVersion` no longer have a default
value for parameter **InstanceName** since the parameter is mandatory
and it was never used.
- SqlReplication
- The resource are now using the helper function `Get-SqlInstanceMajorVersion`
(issue #1408).
- Fixes #1408
--- …
=> SqlReplication: Remove duplicate function

CHANGELOG.md, tests/Unit/DSC_SqlDatabaseRole.Tests.ps1
Adds a test to ensure Add-SqlDscDatabaseRoleMember throws the expected error. 
- Fixes #1620 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1626)
=> DSC_SqlDatabaseRole: Add a test to check error message on helper function

CHANGELOG.md, source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1, source/DSCResources/DSC_SqlRole/README.md, source/DSCResources/DSC_SqlRole/en-US/DSC_SqlRole.strings.psd1, tests/Integration/DSC_SqlRole.Integration.Tests.ps1, tests/Unit/DSC_SqlRole.Tests.ps1
Major overhaul of SQLRole, added tests, and fix for issue #550
some remodeling of SqlRole.
lots of extra tests,
fix for #550 
Fixes #550 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1631)
=> BREAKING CHANGE: SqlRole: Resource overhaul for tests

CHANGELOG.md, source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.psm1, source/DSCResources/DSC_SqlSetup/README.md, tests/Unit/DSC_SqlSetup.Tests.ps1
- SqlSetup
- Added a note to the documentation that the parameter `BrowserSvcStartupType`
cannot be used for configurations that utilize the `'InstallFailoverCluster'`
action (issue #1627).
- Minor change to the evaluation of the parameter `BrowserSvcStartupType`,
if it has an assigned a value or not.
- Fixes #1627
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1635)
=> SqlSetup: Updated documentation for BrowserSvcStartupType

CHANGELOG.md, source/DSCResources/DSC_SqlMaxDop/DSC_SqlMaxDop.psm1, tests/Unit/DSC_SqlMaxDop.Tests.ps1
Added three return values for Get-TargetResource and tests 
- Fixes #396
- [X ] Added an entry to the change log under the Unreleased section of the
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1644)
=> SqlServerMaxDop Fix for #396

CHANGELOG.md, tests/Unit/DSC_SqlDatabaseObjectPermission.Tests.ps1
Updated unit tests for `SqlDatabaseObjectPermission` resource to replace use of `.Where` with `Where-Object` to remove following error...
`Method invocation failed because [Microsoft.Management.Infrastructure.CimInstance] does not contain a method named 'Where'`
... raised in #1648
- Fixes #1648
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1649)
=> SqlDatabaseObjectPermission: Updated unit tests to remove missing `Where()` method error

CHANGELOG.md, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1, source/Modules/SqlServerDsc.Common/en-US/SqlServerDsc.Common.strings.psd1, source/Modules/SqlServerDsc.Common/sv-SE/SqlServerDsc.Common.strings.psd1, tests/Unit/SqlServerDsc.Common.Tests.ps1
Updated `Get-ServerProtocolObject`, helper function in `SqlServerDsc.Common`, helper module to ensure that if there are no instances returned in the `ServerInstances` property's array, an error/exception is thrown (to fix issue #1628).
Fixes #1628
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1651)
=> SqlServerDsc.Common\Get-ServerProtocolObject: Updated to throw error/exception if no 'ServerInstances' returned (Fixes #1628)

CHANGELOG.md, source/DSCResources/DSC_SqlProtocol/DSC_SqlProtocol.psm1, source/DSCResources/DSC_SqlProtocol/en-US/DSC_SqlProtocol.strings.psd1, source/DSCResources/DSC_SqlProtocolTcpIp/DSC_SqlProtocolTcpIp.psm1, source/DSCResources/DSC_SqlProtocolTcpIp/en-US/DSC_SqlProtocolTcpIp.strings.psd1
- SqlProtocol
- The verbose messages now correctly show that `$env:COMPUTERNAME` is used
to get or set the configuration, while parameter **ServerName** is used
to restart the instance.
- SqlProtocolTcpIp
- The verbose messages now correctly show that `$env:COMPUTERNAME` is used
to get or set the configuration, while parameter **ServerName** is used
to restart the instance.
There are already unit and integration tests that covers this change.
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1658)
=> SqlProtocol/SqlProtocolTcpIp: Fix verbose messages

CHANGELOG.md, source/DSCResources/DSC_SqlDatabaseMail/DSC_SqlDatabaseMail.psm1
- SqlDatabaseMail
- Now if a non-mandatory property is not part of the configuration it will
not be enforced (issue #1661).
The unit tests covers this change. The unit test that is converted for Pester 5 will make the tests more obvious.
- Fixes #1661
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1662)
=> SqlDatabaseMail: Do not enforce parameters not part of configuration

CHANGELOG.md, source/DSCResources/DSC_SqlSetup/en-US/DSC_SqlSetup.strings.psd1, source/DSCResources/DSC_SqlSetup/sv-SE/DSC_SqlSetup.strings.psd1
- SqlSetup
- When the SqlSetup detects that the expected components was not installed
and consequently throws an exception, that exception message now presents
a link to an article on how to find the SQL Server setup logs (issue #1420).
- Fixes #1420
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1664)
=> SqlSetup: Fix error message how to find setup logs

CHANGELOG.md, source/DSCResources/DSC_SqlRSSetup/DSC_SqlRSSetup.psm1, tests/Unit/DSC_SqlRSSetup.Tests.ps1
- SqlRSSetup
- If parameter `EditionUpgrade` is set to `$false` the `/EditionUpgrade`
argument is no longer wrongly added (issue #1398).
- Fixes #1398 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1665)
=> SqlRSSetup: Fix EditionUpgrade set to $false

CHANGELOG.md, GitVersion.yml
- SqlServerDsc
- The component `gitversion` that is used in the pipeline was wrongly configured
when the repository moved to the new default branch `main`. It no longer throws
an error when using newer versions of GitVersion (issue #1674),
- Fixes #1674
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1675)
=> SqlServerDsc: Fix gitversion in pipeline

CHANGELOG.md, source/DSCResources/DSC_SqlRSSetup/DSC_SqlRSSetup.psm1, tests/Unit/DSC_SqlRSSetup.Tests.ps1
- SqlRSSetup
- If parameter `SuppressRestart` is set to `$false` the `/norestart`
argument is no longer wrongly added (issue #1401).
- Fixes #1401
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1673)
=> SqlRSSetup: Fix SuppressRestart to not be added when $false

CHANGELOG.md, source/DSCResources/DSC_SqlDatabaseUser/DSC_SqlDatabaseUser.psm1, tests/Unit/DSC_SqlDatabaseUser.Tests.ps1
Added -ServerName to Assert-SqlLogin. @PSBoundParameters doesn't capture $ServerName when it is not explicitly set by the caller.
Fixes #1647
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1681)
=> SqlDatabaseUser: Pass parameter ServerName to Assert-SqlLogin

CHANGELOG.md, RequiredModules.psd1, source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.psm1, source/DSCResources/DSC_SqlSetup/README.md, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psd1, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1, source/Modules/SqlServerDsc.Common/en-US/SqlServerDsc.Common.strings.psd1, tests/Integration/DSC_SqlSetup.Integration.Tests.ps1, tests/Integration/DSC_SqlSetup.config.ps1, tests/Integration/README.md, tests/Unit/SqlServerDsc.Common.Tests.ps1
- SqlSetup
- The helper function `Connect-SqlAnalysis` was using `LoadWithPartial()`
to load the assembly _Microsoft.AnalysisServices_. On a node where multiple
instances with different versions of SQL Server (regardless of features)
is installed, this will result in the first assembly found in the
GAC will be loaded into the session, not taking versions into account.
This can result in an assembly version being loaded that is not compatible
with the version of SQL Server it was meant to be used with.
A new method of loading the assembly _Microsoft.AnalysisServices_ was
introduced under a feature flag; `'AnalysisServicesConnection'`.
This new functionality depends on the [SqlServer](https://www.powershellgallery.com/packages/SqlServer)
module, and must be present on the node. The …
=> SqlSetup: Connect-SQLAnalysis no longer using LoadWithPartialName()

CHANGELOG.md, azure-pipelines.yml, source/DSCResources/DSC_SqlRS/DSC_SqlRS.psm1, source/DSCResources/DSC_SqlRS/en-US/DSC_SqlRS.strings.psd1, tests/Integration/DSC_SqlRS.Integration.Tests.ps1, tests/Integration/DSC_SqlRS.config.ps1, tests/Integration/README.md, tests/Unit/DSC_SqlRS.Tests.ps1
- SqlRS
- Integration tests now configures _Microsoft SQL Server 2019 Reporting Services_.
- Fixed SSRS 2019 initialization ([issue #1509](https://github.com/dsccommunity/SqlServerDsc/issues/1509)).
- Fix a problem that did not correctly evaluate the `UseSSL` property against
the current state.
- Fixes #1509
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1719)
=> SqlRs: Integration test configures SSRS 2019

CHANGELOG.md, source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1, source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.schema.mof, tests/Integration/DSC_SqlLogin.Integration.Tests.ps1, tests/Integration/DSC_SqlLogin.config.ps1, tests/Unit/DSC_SqlLogin.Tests.ps1
- SqlLogin
- `LoginMustChangePassword`, `LoginPasswordExpirationEnabled` and `LoginPasswordPolicyEnforced`
parameters no longer enforce default values (issue #1669).
- Fixes #1669 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1696)
=> BREAKING CHANGE: SqlLogin: Parameters no longer enforce default values

CHANGELOG.md, source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1, source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.schema.mof, source/DSCResources/DSC_SqlAGDatabase/en-US/about_SqlAGDatabase.help.txt, source/Examples/Resources/SqlAGDatabase/1-AddDatabaseToAvailabilityGroup.ps1, source/Examples/Resources/SqlAGDatabase/3-MatchDefinedDatabaseInAvailabilityGroup.ps1
- Changes to SqlAGDatabase
- Added StatementTimeout parameter with value 0 (no timeout) to Connect-SQL invocation in Set-TargetResource function to fix Issue#1743
This prevents timeout during backup operation on secondary.
- Fixes #1743
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1744)
=> SqlAgDatabase: Fixes Issue #1743

CHANGELOG.md, source/DSCResources/DSC_SqlDatabaseUser/DSC_SqlDatabaseUser.psm1, source/DSCResources/DSC_SqlDatabaseUser/DSC_SqlDatabaseUser.schema.mof, source/DSCResources/DSC_SqlDatabaseUser/README.md, tests/Unit/DSC_SqlDatabaseUser.Tests.ps1
Retrieved the `IsUpdateable` property from the database object. If `IsUpdateable` is `$false`, then `Test-TargetResource` returns `$true`
- Fixes #1748
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1749)
=> SqlDatabaseUser: Execute Set-TargetResource when database IsUpdateable is $true

CHANGELOG.md, source/DSCResources/DSC_SqlDatabaseRole/DSC_SqlDatabaseRole.psm1, source/DSCResources/DSC_SqlDatabaseRole/DSC_SqlDatabaseRole.schema.mof, source/DSCResources/DSC_SqlDatabaseRole/README.md, tests/Unit/DSC_SqlDatabaseRole.Tests.ps1
Retrieved the `IsUpdateable` property from the database object. If `IsUpdateable` is `$false`, then `Test-TargetResource` returns `$true`.
- Fixes #1750
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1751)
=> SqlDatabaseRole: Execute Set-TargetResource when database IsUpdateable is $true

CHANGELOG.md, source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.psm1, source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.schema.mof
SourcePath should be a mandatory parameter on the *-TargetResource
functions, as an exception is thrown if the parameter is not passed.
- Fixes #1755 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1756)
=> SqlSetup: SourcePath should be a mandatory parameter

CHANGELOG.md, source/DSCResources/DSC_SqlAlwaysOnService/DSC_SqlAlwaysOnService.psm1, source/DSCResources/DSC_SqlAlwaysOnService/DSC_SqlAlwaysOnService.schema.mof, tests/Integration/DSC_SqlAlwaysOnService.Integration.Tests.ps1, tests/Unit/DSC_SqlAlwaysOnService.Tests.ps1
Remove IsHadrEnabled and return the state in Ensure.
Update Test-TargetResource to look at Ensure instead of IsHadrEnabled.
Update Tests to match.
- Fixes #1759
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1760)
=> BREAKING CHANGE: SQLAlwaysOnService: Get-TargetResource should return Ensure=Absent

CHANGELOG.md, source/DSCResources/DSC_SqlPermission/DSC_SqlPermission.psm1, source/DSCResources/DSC_SqlPermission/DSC_SqlPermission.schema.mof
Permission parameter within SqlPermission should be mandatory, otherwise get-targetresource throws an exception.
- Fixes #1761
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1762)
=> SqlPermission: Permission parameter should be mandatory

CHANGELOG.md, source/Classes/010.ResourceBase.ps1, source/Classes/020.SqlAudit.ps1, source/Classes/020.SqlDatabasePermission.ps1, source/Classes/020.SqlPermission.ps1, source/Public/Invoke-SqlDscQuery.ps1, tests/Unit/Classes/ResourceBase.Tests.ps1
- SqlDatabasePermission
- Made the resource derive from `SqlResourceBase` to clean up the code
a bit.
- SqlPermission
- Made the resource derive from `SqlResourceBase` to clean up the code
a bit.
- Class `ResourceBase`
- Renamed the hidden property that derived classes can specify which properties
to not enforce when comparing desired state against current state. New name
of the hidden property is `ExcludeDscProperties`.
None
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1780)
=> SqlServerDsc: Make class-based resources derive from `SqlResourceBase`

CHANGELOG.md, source/en-US/SqlServerDsc.strings.psd1
- SqlServerDsc
- Localized strings file `en-US/SqlServerDsc.strings.psd1` no longer
referencing the wrong module in a comment.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1791)
=> SqlServerDsc: Fix comment in localized strings file

CHANGELOG.md, azure-pipelines.yml, source/DSCResources/DSC_SqlDatabase/DSC_SqlDatabase.psm1, source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.psm1, tests/Integration/DSC_SqlAgentAlert.Integration.Tests.ps1, tests/Integration/DSC_SqlAgentFailsafe.Integration.Tests.ps1, tests/Integration/DSC_SqlAgentOperator.Integration.Tests.ps1, tests/Integration/DSC_SqlAlwaysOnService.Integration.Tests.ps1, tests/Integration/DSC_SqlAudit.Integration.Tests.ps1, tests/Integration/DSC_SqlDatabase.Integration.Tests.ps1, tests/Integration/DSC_SqlDatabase.config.ps1, tests/Integration/DSC_SqlDatabaseDefaultLocation.Integration.Tests.ps1, tests/Integration/DSC_SqlDatabaseMail.Integration.Tests.ps1, tests/Integration/DSC_SqlDatabaseObjectPermission.Integration.Tests.ps1, tests/Integration/DSC_SqlDatabasePermission.Integration.Tests.ps1, tests/Integration/DSC_SqlDatabaseUser.Integration.Tests.ps1, tests/Integration/DSC_SqlEndpoint.Integration.Tests.ps1, tests/Integration/DSC_SqlLogin.Integration.Tests.ps1, tests/Integration/DSC_SqlPermission.Integration.Tests.ps1, tests/Integration/DSC_SqlProtocol.Integration.Tests.ps1, tests/Integration/DSC_SqlProtocolTcpIp.Integration.Tests.ps1, tests/Integration/DSC_SqlReplication.Integration.Tests.ps1, tests/Integration/DSC_SqlRole.Integration.Tests.ps1, tests/Integration/DSC_SqlScript.Integration.Tests.ps1, tests/Integration/DSC_SqlScriptQuery.Integration.Tests.ps1, tests/Integration/DSC_SqlSecureConnection.Integration.Tests.ps1, tests/Integration/DSC_SqlServiceAccount.Integration.Tests.ps1, tests/Integration/DSC_SqlSetup.Integration.Tests.ps1, tests/Integration/DSC_SqlSetup.config.ps1, tests/Integration/DSC_SqlWindowsFirewall.Integration.Tests.ps1
- SqlServerDsc
- Integration tests are now also run on SQL Server 2022.
- SqlDatabase
- Added compatibility levels for SQL Server 2022 (major version 16).
- SqlSetup
- Paths for SQL Server 2022 are correctly returned by Get.
None. But added a few new issues.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1803)
=> SqlServerDsc: Integration tests for SQL Server 2022

CHANGELOG.md, azure-pipelines.yml
- SqlServerDsc
- Moved the build step of the pipeline to a Windows build worker when
running in Azure DevOps.
- Fixes #1818
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1819)
=> SqlServerDsc: Use Windows build worker for build phase

CHANGELOG.md, source/DSCResources/DSC_SqlAGReplica/DSC_SqlAGReplica.psm1, tests/Unit/DSC_SqlAGReplica.Tests.ps1
- SqlAgReplica
- Converted unit test to Pester 5.
- No longer tries to enforce EndpointHostName when it is not part of the
configuration (issue #1821).
- Now `Get-TargetResource` always returns values for the properties `Name`
and `AvailabilityGroupName` (issue #1822).
- Now `Test-TargetResource` no longer test properties that cannot
be enforced (issue #1822).
- Fixes #1753 
- Fixes #1821
- Fixes #1822
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1820)
=> SqlAGReplica: Converted unit tests to Pester 5

CHANGELOG.md, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1, source/Modules/SqlServerDsc.Common/en-US/SqlServerDsc.Common.strings.psd1, source/Modules/SqlServerDsc.Common/sv-SE/SqlServerDsc.Common.strings.psd1
- `Connect-SQL`
- Now returns a more clear error message when the status of a database
instance is not `Online`.
None.
I saw that a pipeline build failed with `ScriptHalted` instead of a real message.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1841)
=> `Connect-SQL`: Returns clear error message when status is not Online

CHANGELOG.md, source/Public/Import-SqlDscPreferredModule.ps1
- `Import-SqlDscPreferredModule`
- No longer tries to get the environment variables from the machine state
when run on Linux or macOS. This will allow the unit tests to run
cross-plattform.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1852)
=> `Import-SqlDscPreferredModule`: Allow unit tests to run cross-plattform

CHANGELOG.md, build.yaml, source/Classes/002.DatabasePermission.ps1, source/Classes/002.ServerPermission.ps1, source/Classes/004.StartupParameters.ps1
- SqlServerDsc
- Add empty constructor to classes to be able to use Pester's new code
coverage method. See more information can be found in [pester/Pester#2306](https://github.com/pester/Pester/issues/2306).
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1857)
=> SqlServerDsc: Re-enable Pester's new code coverage method

CHANGELOG.md, source/Classes/001.SqlReason.ps1, source/Classes/011.SqlResourceBase.ps1, source/Classes/020.SqlAudit.ps1, tests/Unit/Classes/SqlReason.Tests.ps1
- SqlServerDsc
- Added class `SqlReason` to be used as the type of the DSC property `Reasons`
for class-based resources.
- The type of the property `Reasons` was changed in the class-based resources.
This resolves a problem when using two DSC resource modules that was
using the same class-type for the property `Reasons`.
- SqlAudit
- Return the correct type for parameter `LogType` when calling method `Get()`.
- Fixes #1831
- Fixes #1832
- Fixes #1833
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1858)
=> SqlServerDsc: Change type for property `Reasons`

CHANGELOG.md, source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1, source/DSCResources/DSC_SqlAGReplica/DSC_SqlAGReplica.psm1, source/DSCResources/DSC_SqlAlwaysOnService/DSC_SqlAlwaysOnService.psm1, source/DSCResources/DSC_SqlProtocol/DSC_SqlProtocol.psm1, source/DSCResources/DSC_SqlProtocolTcpIp/DSC_SqlProtocolTcpIp.psm1, source/DSCResources/DSC_SqlRS/DSC_SqlRS.psm1, source/DSCResources/DSC_SqlReplication/DSC_SqlReplication.psm1, source/DSCResources/DSC_SqlScript/DSC_SqlScript.psm1, source/DSCResources/DSC_SqlScriptQuery/DSC_SqlScriptQuery.psm1, source/DSCResources/DSC_SqlServiceAccount/DSC_SqlServiceAccount.psm1, source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.psm1, source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psd1, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1, tests/QA/AnalyzerRules/SqlServerDsc.AnalyzerRules.psm1, tests/Unit/DSC_SqlAGDatabase.Tests.ps1, tests/Unit/DSC_SqlAGReplica.Tests.ps1, tests/Unit/DSC_SqlAlwaysOnService.Tests.ps1, tests/Unit/DSC_SqlProtocol.Tests.ps1, tests/Unit/DSC_SqlProtocolTcpIp.Tests.ps1, tests/Unit/DSC_SqlRS.Tests.ps1, tests/Unit/DSC_SqlReplication.Tests.ps1, tests/Unit/DSC_SqlServiceAccount.Tests.ps1, tests/Unit/DSC_SqlSetup.Tests.ps1, tests/Unit/DSC_SqlTraceFlag.Tests.ps1, tests/Unit/SqlServerDsc.AnalyzerRules.Tests.ps1, tests/Unit/SqlServerDsc.Common.Tests.ps1
- SqlServerDsc
- The private function `Import-SQLPSModule` was replaced throughout with
the public command `Import-SqlDscPreferredModule` (issue #1848).
- Fixes #1848
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1862)
=> SqlServerDsc: Replace `Import-SQLPSModule`

CHANGELOG.md, GitVersion.yml
- SqlServerDsc
- Removed the regular expression `features?` from the GitVersion configuration.
Before, if a fix commit mentioned the word feature but means a SQL Server
feature GitVersion would bump minor instead of patch number.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1865)
=> SqlServerDsc: Fix GitVersion configuration

.github/workflows/code-analysis.yml, .vscode/analyzersettings.psd1, CHANGELOG.md, RequiredModules.psd1, tests/QA/ScriptAnalyzer.Tests.ps1
- SqlServerDsc
- New GitHub Actions workflow that run PSScriptAnalyzer for PRs so any
issues are shown directly in the PR's changed files (issue #1860).
- Fixes #1860 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1866)
=> SqlServerDsc: Add workflow that run PSScriptAnalyzer

CHANGELOG.md, source/Classes/020.SqlAudit.ps1, source/Public/Disable-SqlDscAudit.ps1, source/Public/Enable-SqlDscAudit.ps1, source/Public/Get-SqlDscAudit.ps1, source/Public/New-SqlDscAudit.ps1, source/Public/Remove-SqlDscAudit.ps1, source/Public/Set-SqlDscAudit.ps1, tests/Unit/Public/Get-SqlDscAudit.Tests.ps1
- `Get-SqlDscAudit`
- The parameter `Name` is no longer mandatory. When left out all the current
audits are returned.
- Fixes #1812
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1850)
=> `Get-SqlDscAudit`: `Name` no longer mandatory

.github/workflows/stale.yml, CHANGELOG.md
- SqlServerDsc
- Fix new Stale exempt label
- Fixes #1882
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1886)
=> SqlServerDsc: Fix Stale exempt label

CHANGELOG.md, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1
- The command `Restart-SqlService` was updated to correctly evaluate when
the timeout value is reached (issue #1889).
- Fixes #1889
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1890)
=> `Restart-SqlService`: Correctly evaluate timeout value

CHANGELOG.md, source/DSCResources/DSC_SqlSecureConnection/DSC_SqlSecureConnection.psm1, source/DSCResources/DSC_SqlSecureConnection/DSC_SqlSecureConnection.schema.mof, source/Examples/Resources/SqlSecureConnection/1-ForceSecureConnection.ps1, tests/Integration/DSC_SqlSecureConnection.Integration.Tests.ps1, tests/Integration/DSC_SqlSecureConnection.config.ps1, tests/Unit/DSC_SqlSecureConnection.Tests.ps1, tests/Unit/SqlServerDsc.Common.Tests.ps1
- `SqlSecureConnection`
- Added new parameter `ServerName` that will be used as the host name when
restarting the SQL Server instance. The specified value should be the same
name that is used in the certificate (issue #1888).
- Fixes #1888
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1892)
=> SqlSecureConnection: Added new parameter `ServerName`

CHANGELOG.md, source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.psm1, source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.schema.mof, tests/Unit/DSC_SqlSetup.Tests.ps1
- SqlSetup
- Added new parameter `ServerName` that will be used as the host name when
evaluating the SQL Server instance. If using a secure connection the
specified value should be the same name that is used in the certificate
(issue #1893).
- Fixes #1893
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1900)
=> SqlSetup: Add parameter ServerName

CHANGELOG.md, source/Public/Get-SqlDscPreferredModule.ps1, tests/Unit/Public/Get-SqlDscPreferredModule.Tests.ps1
- `Get-SqlDscPreferredModule`
- Re-using the command `Get-PSModulePath` from the module DscResource.Common.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1905)
=> `Get-SqlDscPreferredModule`: Using command `Get-PSModulePath`

CHANGELOG.md, GitVersion.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1913)
=> SqlServerDsc: Fix how major version is bumped

CHANGELOG.md, source/Private/Invoke-SetupAction.ps1
- Update private command:
- `Invoke-SetupAction` was changed to expand environment variables that
is passed as the media path.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1914)
=> `Invoke-SetupAction`: Expand environment variables

CHANGELOG.md, RequiredModules.psd1, source/DSCResources/DSC_SqlRS/DSC_SqlRS.psm1, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1, source/Public/Connect-SqlDscDatabaseEngine.ps1, source/Public/Invoke-SqlDscQuery.ps1, tests/Integration/DSC_SqlRS.config.ps1, tests/Integration/DSC_SqlRS_Default.config.ps1, tests/Unit/DSC_SqlRS.Tests.ps1, tests/Unit/Public/Connect-SqlDscDatabaseEngine.Tests.ps1, tests/Unit/Public/Invoke-SqlDscQuery.Tests.ps1, tests/Unit/SqlServerDsc.Common.Tests.ps1
- `Connect-SQL`.
- Add new parameter `Encrypt`.
- `Connect-SqlDscDatabaseEngine`
- Add new parameter `Encrypt`.
- `Invoke-SqlDscQuery`
- Add new parameter `Encrypt`.
- Now shows the correct instance name when called using a server object (issue #1918).
- SqlRS
- Now uses the command `Invoke-SqlDscQuery` instead of `Invoke-SqlCmd` (issue #1917).
- The parameter `Encrypt` has changed so that `Mandatory` or `Strict`
will turn on encryption when connecting to the database instance.
- Fixes #1917 
- Fixes #1918
- - - …
=> SqlRS: Using `Invoke-SqlDscQuery`

CHANGELOG.md, azure-pipelines.yml, source/Public/Get-SqlDscPreferredModule.ps1, source/Public/Import-SqlDscPreferredModule.ps1, source/WikiSource/Home.md, tests/Integration/DSC_SqlSetup.Integration.Tests.ps1, tests/Integration/DSC_SqlSetup.config.ps1
- SqlServerDsc
- Using dbatools as a preferred module.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1904)
=> SqlServerDsc: Using dbatools as a preferred module

CHANGELOG.md, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1, source/Modules/SqlServerDsc.Common/en-US/SqlServerDsc.Common.strings.psd1, source/Modules/SqlServerDsc.Common/sv-SE/SqlServerDsc.Common.strings.psd1, tests/Unit/SqlServerDsc.Common.Tests.ps1
- Fixes #1816 
- [ X] Added an entry to the change log under the Unreleased section of the
- [ X] Localization strings updated.
- [ X] Unit tests updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ X] Code changes adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1916)
=> Connect-SQL: Add Wait for Online SMO Status

CHANGELOG.md, source/Public/Import-SqlDscPreferredModule.ps1
- `Import-SqlDscPreferredModule`
- Now the command does not fail when checking if SQLPS is loaded into the
session (issue #1928).
- Fixes #1928
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1929)
=> `Import-SqlDscPreferredModule`: Fix checking that SQLPS is loaded

.vscode/settings.json, CHANGELOG.md, azure-pipelines.yml, tests/Integration/DSC_SqlSetup.config.ps1
- SqlServerDsc
- Bumped dbatools to v2.0.1 for the integration tests.
None. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1926)
=> Bump dbatools to v2.0.1

.vscode/settings.json, CHANGELOG.md, build.yaml, source/DSCResources/DSC_SqlConfiguration/README.md, source/Public/Get-SqlDscConfigurationOption.ps1, source/en-US/SqlServerDsc.strings.psd1, tests/Unit/Public/Get-SqlDscConfigurationOption.Tests.ps1, tests/Unit/Stubs/SMO.cs
- SqlServerDsc
- Added new public command:
- `Get-SqlDscConfigurationOption` - Returns the available configuration
options that can be used with the DSC resource _SqlConfiguration_.
- Helps with issue #1931 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1935)
=> SqlServerDsc: Add public command `Get-SqlDscConfigurationOption`

CHANGELOG.md, source/Public/Import-SqlDscPreferredModule.ps1, tests/Unit/Public/Import-SqlDscPreferredModule.Tests.ps1
- `Import-SqlDscPreferredModule`
- Now when parameter `Force` is passed the command correctly invoke
`Get-SqlDscPreferredModule` using the parameter `Refresh`.
None. But might be the reason PR #1932 fails.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1938)
=> `Import-SqlDscPreferredModule`: Fix re-evaluate PSModulePath

CHANGELOG.md, source/DSCResources/DSC_SqlMaxDop/README.md, source/DSCResources/DSC_SqlMemory/README.md
- SqlMemory
- Highlighted an important note in the README.md.
- SqlMaxDop
- Highlighted an important note in the README.md.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1959)
=> SqlServerDsc: Highlight important notes in markdown

CHANGELOG.md, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1, tests/Unit/SqlServerDsc.Common.Tests.ps1
Changes from string Exception to just Exception object so InnerException can be searched for error codes
- Fixes #1952 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1953)
=> SqlLogin: Attempting to disable and already disabled login throws an error #1952

CHANGELOG.md, source/Private/Invoke-SetupAction.ps1, source/Public/Install-SqlDscServer.ps1, tests/Unit/Private/Invoke-SetupAction.Tests.ps1, tests/Unit/Public/Install-SqlDscServer.Tests.ps1
- `Install-SqlDscServer`
- Now the parameter `InstanceName` can no longer be specified (as per
the SQL Server documentation) for the setup action `PrepareImage`
(issue #1960).
- Fixes #1960
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1961)
=> `Install-SqlDscServer`: Fix bug for `PrepareImage`

CHANGELOG.md, RequiredModules.psd1, Resolve-Dependency.ps1, build.ps1, source/Examples/Resources/SqlRS/4-CompleteWithTwoInstances.ps1, source/Examples/Resources/SqlScript/3-RunScriptCompleteExample.ps1, source/Examples/Resources/SqlScriptQuery/3-RunScriptCompleteExample.ps1, source/Examples/Resources/SqlSetup/1-InstallDefaultInstanceSingleServer.ps1, source/Examples/Resources/SqlSetup/2-InstallNamedInstanceSingleServer.ps1, source/Examples/Resources/SqlSetup/3-InstallNamedInstanceSingleServerFromUncPathUsingSourceCredential.ps1, source/Examples/Resources/SqlSetup/4-InstallNamedInstanceInFailoverClusterFirstNode.ps1, source/Examples/Resources/SqlSetup/5-InstallNamedInstanceInFailoverClusterSecondNode.ps1, source/Examples/Resources/SqlSetup/6-InstallNamedInstanceSingleServerWithAgtSvcStartupTypeDisabled.ps1, source/Examples/Resources/SqlSetup/7-InstallDefaultInstanceSingleServer2016OrLater.ps1, source/Examples/Resources/SqlSetup/8-UsingSkipRuleDuringInstall.ps1, tests/Integration/DSC_SqlAlwaysOnService.config.ps1, tests/Integration/DSC_SqlLogin.config.ps1, tests/Integration/DSC_SqlRS.config.ps1, tests/Integration/DSC_SqlRSSetup.config.ps1, tests/Integration/DSC_SqlRS_Default.config.ps1, tests/Integration/DSC_SqlReplication.config.ps1, tests/Integration/DSC_SqlScript.config.ps1, tests/Integration/DSC_SqlServiceAccount.config.ps1, tests/Integration/DSC_SqlSetup.config.ps1, tests/Integration/DSC_SqlWindowsFirewall.config.ps1
- SqlServerDsc
- Updated pipeline files to support ModuleFast.
- SqlRs
- Updated examples to use xPSDesiredStateConfiguration instead of PSDScResources.
- Updated integration tests to use xPSDesiredStateConfiguration instead of PSDScResources.
- SqlScript
- Updated examples to use xPSDesiredStateConfiguration instead of PSDScResources.
- Updated integration tests to use xPSDesiredStateConfiguration instead of PSDScResources.
- SqlScriptQuery
- Updated examples to use xPSDesiredStateConfiguration instead of PSDScResources.
- SqlSetup
- Updated examples to use xPSDesiredStateConfiguration instead of PSDScResources.
- Updated integration tests to use xPSDesiredStateConfiguration instead of PSDScResources.
- SqlAlwaysOnService
- Updated integration tests to use xPSDesiredStateConfiguration …
=> SqlServerDsc: Update pipeline files from Sampler

CHANGELOG.md, source/Private/Get-SMOModuleCalculatedVersion.ps1, source/Public/Get-SqlDscPreferredModule.ps1, source/Public/Import-SqlDscPreferredModule.ps1, source/en-US/SqlServerDsc.strings.psd1, tests/Unit/Private/Get-SMOModuleCalculatedVersion.Tests.ps1, tests/Unit/Public/Get-SqlDscPreferredModule.Tests.ps1, tests/Unit/Public/Import-SqlDscPreferredModule.Tests.ps1
Optionally set the `SMODefaultModuleVersion` environment variable for your preferred module.
For example:
- SqlServer: 22.0.49-preview 
- SQLPS: 130
- OtherModule: <maj.min.patch>
- Fixes #1965
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1966)
=> Get-SqlDscPreferredModule: Optionally specify which version of the SQL module is imported

CHANGELOG.md, build.yaml
- SqlServerDsc
- Now package the Wiki content and adds it as a GitHub Release asset so it
is simpler to get the documentation for a specific version.
- Closes #1968 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1970)
=> SqlServerDsc: Add release asset for Wiki documentation

CHANGELOG.md, source/DSCResources/DSC_SqlAGListener/DSC_SqlAGListener.psm1, source/DSCResources/DSC_SqlAGListener/DSC_SqlAGListener.schema.mof, source/Examples/Resources/SqlAGListener/1-AddAvailabilityGroupListenerWithSameNameAsVCO.ps1, source/Examples/Resources/SqlAGListener/2-AddAvailabilityGroupListenerWithDifferentNameAsVCO.ps1, source/Examples/Resources/SqlAGListener/5-AddAvailabilityGroupListenerUsingDHCPWithDefaultServerSubnet.ps1, source/Examples/Resources/SqlAGListener/6-AddAvailabilityGroupListenerUsingDHCPWithSpecificSubnet.ps1, tests/Unit/DSC_SqlAGListener.Tests.ps1
- Changes to SqlAGListener
- Made the resource cluster aware. When ProcessOnlyOnActiveNode is specified,
the resource will only determine if a change is needed if the target node
is the active host of the SQL Server instance ([issue #871](https://github.com/dsccommunity/SqlServerDsc/issues/871)).
- Fixes #871
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1783)
=> SqlAGListener: Add parameter `ProcessOnlyOnActiveNode` to make it cluster aware

CHANGELOG.md, source/DSCResources/DSC_SqlAG/DSC_SqlAG.psm1, tests/Unit/DSC_SqlAG.Tests.ps1, tests/Unit/DSC_SqlAGReplica.Tests.ps1
Convert SqlAG unit tests to Pester 5 plus add missed parameters to a SQLAG Test and Get functions.
Fix unit test for the SQLAGReplica
- Fixes #1752
- Fixes #1735
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1987)
=> SqlAG: unit tests converted to Pester 5

CHANGELOG.md, source/Private/Invoke-SetupAction.ps1, source/Public/Add-SqlDscTraceFlag.ps1, source/Public/Disable-SqlDscAudit.ps1, source/Public/Disconnect-SqlDscDatabaseEngine.ps1, source/Public/Enable-SqlDscAudit.ps1, source/Public/Import-SqlDscPreferredModule.ps1, source/Public/Invoke-SqlDscQuery.ps1, source/Public/New-SqlDscAudit.ps1, source/Public/Remove-SqlDscAudit.ps1, source/Public/Remove-SqlDscTraceFlag.ps1, source/Public/Set-SqlDscAudit.ps1, source/Public/Set-SqlDscDatabasePermission.ps1, source/Public/Set-SqlDscServerPermission.ps1, source/Public/Set-SqlDscStartupParameter.ps1, source/Public/Set-SqlDscTraceFlag.ps1
- SqlServerDsc
- Public commands no handles when both `-Force` and `-Confirm $true`
would be passed to command.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1994)
=> SqlServerDsc: Fix handling of `-Force` and `-Confirm $true` in commands

CHANGELOG.md, RequiredModules.psd1, azure-pipelines.yml, build.yaml, tests/QA/module.tests.ps1
- SqlServerDsc
- Added build tasks to generate Wiki documentation for public commands.
- Documentation is now built using a separate meta task `docs`.
It is run with the meta task `pack` which is run by the pipeline.
To run the meta task `docs` the SMO assemblies must be loaded into the
session, either by importing SqlServer module or loading SMO stubs.
- QA test improved to speed up quality testing.
_This PR is dependent on PR https://github.com/dsccommunity/DscResource.DocGenerator/pull/133 being merged._
- Fixes #1770 
- - - …
=> SqlServerDsc: Add markdown creation for public commands

CHANGELOG.md, source/DSCResources/DSC_SqlDatabaseMail/DSC_SqlDatabaseMail.psm1, source/DSCResources/DSC_SqlDatabaseMail/DSC_SqlDatabaseMail.schema.mof, source/DSCResources/DSC_SqlDatabaseMail/en-US/DSC_SqlDatabaseMail.strings.psd1, tests/Unit/DSC_SqlDatabaseMail.Tests.ps1
Added the parameter UseDefaultCredentials to the SqlDatabaseMailDsc resource to allow the DatabaseEngine service account to be used for SMTP server authentication.  Changes required to this resource to support configuration of the account and password for "basic" or "anonymous" SMTP access is not addressed by this PR.   
None
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2001)
=> SqlDatabaseMail: Add parameter UseDefaultCredentials

CHANGELOG.md, tests/Integration/DSC_SqlRS.Integration.Tests.ps1, tests/Integration/DSC_SqlRS_Default.Integration.Tests.ps1
This re-arranges the change log entries under the unreleased section.
None.
Helps to make releases work until issue #2009 is resolved.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2008)
=> SqlRS: Disable integration tests that causes tests to fail (issue #2009)

CHANGELOG.md, azure-pipelines.yml, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1, source/Private/Invoke-SetupAction.ps1, source/Public/Add-SqlDscNode.ps1, source/Public/Complete-SqlDscFailoverCluster.ps1, source/Public/Complete-SqlDscImage.ps1, source/Public/Initialize-SqlDscRebuildDatabase.ps1, source/Public/Install-SqlDscServer.ps1, source/Public/Remove-SqlDscNode.ps1, source/Public/Repair-SqlDscServer.ps1, source/Public/Save-SqlDscSqlServerMedia.ps1, source/Public/Save-SqlDscSqlServerMediaFile.ps1, source/Public/Uninstall-SqlDscServer.ps1, source/en-US/SqlServerDsc.strings.psd1, tests/Integration/Commands/Install-SqlDscServer.Integration.Tests.ps1, tests/Integration/Commands/Prerequisites.Integration.Tests.ps1, tests/Integration/Commands/README.md, tests/Unit/Public/Add-SqlDscNode.Tests.ps1, tests/Unit/Public/Complete-SqlDscFailoverCluster.Tests.ps1, tests/Unit/Public/Complete-SqlDscImage.Tests.ps1, tests/Unit/Public/Initialize-SqlDscRebuildDatabase.Tests.ps1, tests/Unit/Public/Install-SqlDscServer.Tests.ps1, tests/Unit/Public/Remove-SqlDscNode.Tests.ps1, tests/Unit/Public/Repair-SqlDscServer.Tests.ps1, tests/Unit/Public/Save-SqlDscSqlServerMedia.Tests.ps1, tests/Unit/Public/Save-SqlDscSqlServerMediaFile.Tests.ps1, tests/Unit/Public/Uninstall-SqlDscServer.Tests.ps1
- SqlServerDsc
- Initial integration tests for commands
- Fixes #1838
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2028)
=> SqlServerDsc: Initial integration tests for commands 

CHANGELOG.md, source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.psm1, source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.schema.mof, tests/Integration/Resources/DSC_SqlSetup.Integration.Tests.ps1, tests/Unit/DSC_SqlSetup.Tests.ps1
- SqlSetup
- The parameter `SecurityMode` now only (correctly) allows the value
`SQL` (issue #1185).
- Fixes #1185
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2032)
=> SqlSetup: Remove value `Windows` from parameter `SecurityMode`

CHANGELOG.md, tests/Unit/Classes/SqlAudit.Tests.ps1, tests/Unit/DSC_SqlDatabaseMail.Tests.ps1
- SqlAudit
- Fixed unit tests.
- Fixes #2002
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2038)
=> SqlAudit: Fix unit tests

CHANGELOG.md, source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.psm1, source/DSCResources/DSC_SqlSetup/README.md, tests/Unit/DSC_SqlSetup.Tests.ps1
As [documented](https://learn.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-from-the-command-prompt?view=sql-server-ver16#AddNode) by Microsoft, the "AddNode" action requires a value for the parameter `FailoverClusterIPAddresses`. The SqlServerDsc module was incorrectly excluding this property from the arguments passed to the setup program. This caused any DSC operations for "AddNode" to fail during the `Set-TargetResource` process. This PR makes a minor adjustment to allow the IP property to be emitted when `$Action` is set to "AddNode".
- Fixes #1171 
- - -
This change is [<img …
=> SqlSetup: Fix AddNode failing due to missing setup parameters

.github/workflows/code-analysis-built-module.yml, .github/workflows/code-analysis.yml, CHANGELOG.md, source/Classes/020.SqlAudit.ps1, source/DSCResources/DSC_SqlConfiguration/DSC_SqlConfiguration.psm1, source/DSCResources/DSC_SqlDatabaseUser/DSC_SqlDatabaseUser.psm1, source/DSCResources/DSC_SqlMaxDop/DSC_SqlMaxDop.psm1, source/DSCResources/DSC_SqlMemory/DSC_SqlMemory.psm1, source/DSCResources/DSC_SqlRSSetup/DSC_SqlRSSetup.psm1, source/DSCResources/DSC_SqlReplication/DSC_SqlReplication.psm1, source/DSCResources/DSC_SqlServiceAccount/DSC_SqlServiceAccount.psm1, source/Public/Save-SqlDscSqlServerMediaFile.ps1, tests/Unit/Classes/SqlAudit.Tests.ps1
- `SqlAudit`
- Fix localization strings in `Assert` method.
- `Save-SqlDscSqlServerMediaFile`
- Fix localizations strings that used wrong keys.
None. DUe to changes in DscResource.Test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2062)
=> Fix localization strings

CHANGELOG.md, source/Private/Invoke-ReportServerSetupAction.ps1, source/Private/Invoke-SetupAction.ps1, source/en-US/SqlServerDsc.strings.psd1, tests/Unit/Private/Invoke-ReportServerSetupAction.Tests.ps1, tests/Unit/Private/Invoke-SetupAction.Tests.ps1, tests/Unit/Public/Install-SqlDscServer.Tests.ps1, tests/Unit/Public/Save-SqlDscSqlServerMediaFile.Tests.ps1
- Private function:
- `Invoke-ReportServerSetupAction`
- `Save-SqlDscSqlServerMediaFile`
- Fix unit tests so the work cross-platform.
- `Install-SqlDscServer` and private function `Invoke-SetupAction`
- Fix localization string keys naming.
- Fix unit tests to use correct localization string names.
Ground work fo issue #2010.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2066)
=> `Invoke-ReportServerSetupAction`: Add private command

CHANGELOG.md, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psd1, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1, tests/Unit/SqlServerDsc.Common.Tests.ps1
- Removed the function `Get-RegistryPropertyValue` in favor of the command
with the same name in the module _DscResource.Common_.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2076)
=> Remove `Get-RegistryPropertyValue` function

CHANGELOG.md, source/Public/Test-SqlDscIsRole.ps1, tests/Unit/Public/Test-SqlDscIsRole.Tests.ps1
Added a public command that returns whether the server role exists.
Implemented new Test-SqlDscIsRole for testing whether a server principal is a Role. Fixed documentation in Test-SqlDscIsLogin
- Fixes #2058 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2060)
=> `Test-SqlDscIsRole`: New command

CHANGELOG.md, source/Public/Get-SqlDscRSSetupConfiguration.ps1, tests/Integration/Commands/Get-SqlDscRSSetupConfiguration.Integration.Tests.ps1, tests/Integration/Commands/Install-SqlDscBIReportServer.Integration.Tests.ps1, tests/Unit/Public/Get-SqlDscRSSetupConfiguration.Tests.ps1
- `Get-SqlDscRSSetupConfiguration`
- Add additional properties to `Get-SqlDscRSSetupConfiguration` output.
None. Needed for PR #2083 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2089)
=> `Get-SqlDscRSSetupConfiguration`: Add additional properties to output

CHANGELOG.md, source/Private/Invoke-ReportServerSetupAction.ps1, source/Public/Install-SqlDscBIReportServer.ps1, source/Public/Install-SqlDscReportingService.ps1, source/Public/Repair-SqlDscBIReportServer.ps1, source/Public/Repair-SqlDscReportingService.ps1, source/Public/Uninstall-SqlDscBIReportServer.ps1, source/Public/Uninstall-SqlDscReportingService.ps1, tests/Unit/Private/Invoke-ReportServerSetupAction.Tests.ps1, tests/Unit/Public/Install-SqlDscBIReportServer.Tests.ps1, tests/Unit/Public/Install-SqlDscReportingService.Tests.ps1, tests/Unit/Public/Repair-SqlDscBIReportServer.Tests.ps1, tests/Unit/Public/Repair-SqlDscReportingService.Tests.ps1, tests/Unit/Public/Uninstall-SqlDscBIReportServer.Tests.ps1, tests/Unit/Public/Uninstall-SqlDscReportingService.Tests.ps1
- `Install-SqlDscReportingService`
- Add `PassThru` parameter to return exit code.
- `Install-SqlDscBIReportServer`
- Add `PassThru` parameter to return exit code.
- `Repair-SqlDscReportingService`
- Add `PassThru` parameter to return exit code.
- `Repair-SqlDscBIReportServer`
- Add `PassThru` parameter to return exit code.
- `Uninstall-SqlDscReportingService`
- Add `PassThru` parameter to return exit code.
- `Uninstall-SqlDscBIReportServer`
- Add `PassThru` parameter to return exit code.
None.
- - - …
=> Add `PassThru` parameter to Install, Uninstall and Repair commands

CHANGELOG.md, source/DSCResources/DSC_SqlRSSetup/DSC_SqlRSSetup.psm1, source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.psm1, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psd1, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1, tests/Unit/DSC_SqlRSSetup.Tests.ps1, tests/Unit/DSC_SqlSetup.Tests.ps1, tests/Unit/SqlServerDsc.Common.Tests.ps1
- Removed the function `Test-PendingRestart` in favor of the commands with the same names in
the module _DscResource.Common_.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2098)
=> SqlServerDsc: Remove `Test-PendingRestart` function

CHANGELOG.md, azure-pipelines.yml
Windows 2019 pipeline image is going to be deprecated on 30/06/2025.
- Fixes #2106
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2107)
=> Remove windows-2019 image

.github/workflows/copilot-setup-steps.yml, CHANGELOG.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2118)
=> Switch copilot workflow to Linux

.github/workflows/copilot-setup-steps.yml, CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2122)
=> Hardcode module version to 0.0.1 in Copilot workflow

CHANGELOG.md, azure-pipelines.yml, source/Public/Get-SqlDscLogin.ps1, source/en-US/SqlServerDsc.strings.psd1, tests/Integration/Commands/Get-SqlDscLogin.Integration.Tests.ps1, tests/Unit/Public/Get-SqlDscLogin.Tests.ps1
- `Get-SqlDscLogin`
- Added new public command to get a SQL Server login from a Database Engine instance.
- Returns a `Microsoft.SqlServer.Management.Smo.Login` object that represents
the login.
- Supports getting a specific login by name or all logins if no name is specified.
- Includes a `-Refresh` parameter to refresh the server's login collection
before retrieval.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2134)
=> `Get-SqlDscLogin`: command to retrieve SQL Server logins

.build/Test-ShouldRunDscResourceIntegrationTests.ps1, .github/instructions/dsc-community-style-guidelines-markdown.instructions.md, .github/instructions/dsc-community-style-guidelines-powershell.instructions.md, .gitignore, .vscode/settings.json, .vscode/tasks.json, CHANGELOG.md, CONTRIBUTING.md, azure-pipelines.yml, source/Classes/002.DatabasePermission.ps1, source/Classes/002.ServerPermission.ps1, source/Classes/020.SqlAudit.ps1, source/Classes/020.SqlDatabasePermission.ps1, source/Classes/020.SqlPermission.ps1, source/Public/New-SqlDscLogin.ps1, source/en-US/SqlServerDsc.strings.psd1, tests/Integration/Commands/New-SqlDscLogin.Integration.Tests.ps1, tests/Integration/Commands/Prerequisites.Integration.Tests.ps1, tests/Integration/Commands/README.md, tests/Integration/Commands/Remove-SqlDscLogin.Integration.Tests.ps1, tests/Unit/Public/New-SqlDscLogin.Tests.ps1, tests/Unit/Stubs/SMO.cs
- `New-SqlDscLogin`
- Added new public command to create a new login on a SQL Server Database
Engine instance.
- Supports creating SQL Server logins, Windows user logins, Windows group
logins, certificate-based logins, and asymmetric key-based logins.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2132)
=> `New-SqlDscLogin`: command to create SQL Server logins

.build/README.md, .build/Test-ShouldRunDscResourceIntegrationTests.ps1, .github/instructions/dsc-community-style-guidelines-markdown.instructions.md, .vscode/settings.json, CHANGELOG.md, azure-pipelines.yml
- Update .build README
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2139)
=> Update .build README

.github/workflows/copilot-setup-steps.yml, .vscode/settings.json, CHANGELOG.md
- `.github/workflows/copilot-setup-steps.yml`
- Ensure full Git history/tags for GitVersion with a robust shallow check.
- Generalize workflow via `MODULE_NAME` env var and Linux‑friendly paths.
- Make .NET tool install idempotent and tighten module import verification.
- Fixes #2127 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2140)
=> Refactor Copilot setup workflow for improved clarity and functionality

.github/workflows/copilot-setup-steps.yml, CHANGELOG.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2145)
=> Fix environment variable persistence in Copilot setup workflow

CHANGELOG.md, RequiredModules.psd1, source/Examples/Resources/SqlSetup/5-InstallNamedInstanceInFailoverClusterSecondNode.ps1, source/Public/Get-SqlDscAudit.ps1, source/Public/Get-SqlDscConfigurationOption.ps1, source/Public/Get-SqlDscDatabasePermission.ps1, source/Public/Get-SqlDscServerPermission.ps1, source/Public/Get-SqlDscTraceFlag.ps1, source/Public/New-SqlDscDatabase.ps1, tests/Integration/Commands/Get-SqlDscServerPermission.Integration.Tests.ps1, tests/Unit/Public/Get-SqlDscTraceFlag.Tests.ps1
- Fixed incorrect array-return syntax in several public `Get-*` commands by
removing a leading comma in return statements which could cause incorrect
output and ScriptAnalyzer warnings: `Get-SqlDscAudit`,
`Get-SqlDscConfigurationOption`, `Get-SqlDscDatabasePermission`,
`Get-SqlDscServerPermission`, and `Get-SqlDscTraceFlag`.
- New-SqlDscDatabase: use `New-ArgumentException` instead of
`New-InvalidArgumentException` for parameter validation errors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2162)
=> Fix to be compliant with QA tests

.gitattributes, .github/instructions/dsc-community-style-guidelines-integration-tests.instructions.md, .github/instructions/dsc-community-style-guidelines-powershell.instructions.md, .github/instructions/dsc-community-style-guidelines-unit-tests.instructions.md, .github/workflows/copilot-setup-steps.yml, .vscode/tasks.json, CHANGELOG.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2243)
=> Update guidelines, workflows, and configurations

.github/workflows/copilot-setup-steps.yml, CHANGELOG.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2244)
=> Fix copilot setup step

CHANGELOG.md, source/Public/New-SqlDscAudit.ps1, tests/Unit/Public/New-SqlDscAudit.Tests.ps1
- `New-SqlDscAudit`
- Fixed parameter validation to prevent the `ReserveDiskSpace` parameter from
being used with the `FileWithMaxFiles` parameter set (when only `MaximumFiles`
is specified without `MaximumFileSize`). This combination always resulted in
a SQL Server error because `RESERVE_DISK_SPACE` cannot be specified when
`MAXSIZE = UNLIMITED`. The `ReserveDiskSpace` parameter now correctly requires
both `MaximumFiles` and `MaximumFileSize` to be specified
([issue #2289](https://github.com/dsccommunity/SqlServerDsc/issues/2289)).
- Fixes #2289
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> `New-SqlDscAudit`: Fix ReserveDiskSpace parameter requirements
