dsccommunity/SqlServerDsc

Examples/SQLServerNetwork.ps1, README.md
Hi,
As promised added example of new resource usage.
xSqlServerNetwork was added in #20;
=> xSqlServerNetwork example file

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/45)
=> Adding missing 1.5.0.0 release notes

Examples/SQL-ClusterDB.ps1, Examples/SQL-Standalone.ps1, Examples/SQLServerNetwork.ps1
This is a hotfix for release.
Attempting to suppress the PSSA errors in the examples that are crashing tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/71)
=> Supressing PSSA errors in examples.

Tests/Integration/integration_config_template.ps1, Tests/Integration/integration_template.ps1, Tests/Unit/unit_template.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/81)
=> adding test folder with template unit/integration files

Tests/Integration/integration_config_template.ps1, Tests/Integration/integration_template.ps1, Tests/Unit/unit_template.ps1
Reverts PowerShell/xSQLServer#82 - hoping that by deleting the files the folders would still be there, but they don't, so leaving the template files in for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/83)
=> Revert "deleting templates in folders"

DSCResources/MSFT_xSQLAOGroupEnsure/MSFT_xSQLAOGroupEnsure.psm1, DSCResources/MSFT_xSQLAOGroupEnsure/MSFT_xSQLAOGroupEnsure.schema.mof, README.md
Added the support for the parameter EndPointPort to control the TCP port
for the AG EndPoint. This removes the fact that this was previously hard
coded
This fixes Issue #51
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/55)
=> Fixes issue 51

DSCResources/MSFT_xSQLServerFirewall/MSFT_xSQLServerFirewall.schema.mof, DSCResources/xSQLServerReplication/xSQLServerReplication.psm1, DSCResources/xSQLServerReplication/xSQLServerReplication.schema.mof, Examples/SQL-ClusterDB.ps1, Examples/SQL-Standalone.ps1, Examples/SQLServerNetwork.ps1, Examples/xSQLServerReplication.ps1, README.md, Tests/Unit/xSQLServerReplication.Tests.ps1
Created new resource to manage replication configuration.
Supports local and remote distribution.
Supports removing replication configuration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/66)
=> new resource xSqlServerReplication

README.md
@kwirkykat This PR is to be compliant with the new guidance for breaking changes.
This will just change the Unreleased section to mention that the previously merged change for xSQLServerLogin is a breaking change. 
If you could merge this one if all looks good would be great! :)
=> BREAKING CHANGE: Changes to README.md for xSQLServerLogin

DSCResources/MSFT_xSQLServerMaxDop/MSFT_xSQLServerMaxDop.psm1, DSCResources/MSFT_xSQLServerMaxDop/MSFT_xSQLServerMaxDop.schema.mof, README.md
Changed SQLInstanceName MOF attribute to Key so that multiple instances
of this resource can be used.
Fixed code to properly handle parameters.
Added Get-MaxDopDynamic function to separate DynamicAlloc logic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/64)
=> BREAKING CHANGE: xSQLServerMaxDop: added key, fixed code

DSCResources/MSFT_xSQLServerDatabase/MSFT_xSQLServerDatabase.psm1, DSCResources/MSFT_xSQLServerDatabase/MSFT_xSQLServerDatabase.schema.mof, README.md, Tests/Unit/Stubs/SMO.cs, Tests/Unit/xSQLServerDatabase.Tests.ps1, xSQLServerHelper.psm1
Fix Issue #119
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/127)
=> BREAKING CHANGE: Changes to xSQLServerDatabase (fixes #119, #128 and #130)

README.md, appveyor.yml, xSQLServer.psd1
Release of version 3.0.0.0
There seems to have been a timing issue with the original release PR?
This is the one commit that was mysteriously missing from that PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/172)
=> Release of version 3.0.0.0 of xSQLServer

README.md
Moving items to Unreleased section that is not released.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/184)
=> Changes to README.md (fixing unreleased section)

CHANGELOG.md, README.md
Fixes #189 
Add Changelog.md file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/190)
=> Split README.md so the change log is in a new Changelog.md file (Fixes #189)

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md
Fixes #197 
Add template for Issue and Pull Request
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/191)
=> Add template for Issue and Pull Request (Fixes #197)

CONTRIBUTING.md, README.md
Adding specific guidelines for contributing to xSQLServer resource (resolves #158)
This is a proposal of how the specific guideline could look like and what it could contain. Please review and make comments and suggestions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/164)
=> Adding specific contributing guidelines (resolves #158)

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, README.md
- Changes to markdown files
- Fixed lint errors.
- Fixed smaller typos.
- Improved code blocks.
- Changed ISSUE_TEMPLATE.md and PULL_REQUEST_TEMPLATE.md to easily distingush from where to delete text.
- Rewrote some texts
This Pull Request fixes the following issues:
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/219)
=> Changes to README, CHANGELOG, ISSUE_TEMPLATE and PULL_REQUEST_TEMPLATE

CHANGELOG.md, DSCResources/MSFT_xSQLAOGroupJoin/MSFT_xSQLAOGroupJoin.psm1, DSCResources/MSFT_xSQLAOGroupJoin/MSFT_xSQLAOGroupJoin.schema.mof, README.md, Tests/Unit/MSFT_xSQLAOGroupJoin.Tests.ps1
Fixes #211 
Fixes #209 
Fixes #208
- Added test coverage
- Cleaned up the code
- Resolved an issue so that Get-TargetResource work with Get-DscConfiguration (issue #211. issue #209. issue #208)
**Note: The tests will fail until PR #192 is merged.**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/213)
=> xSQLAOGroupJoin: Added test coverage and fixed issues (Fixes #208, #209, #211)

CONTRIBUTING.md
Adding section describing the workaround needed to use SMO stub classes.
Fixes #204
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/228)
=> CONTRIBUTING.md: Adding section for SMO stub classes

CHANGELOG.md, README.md
Changes to README.md
- Changed the contributing section to help new contributors.
- Added links for each resource so it is easier to navigate to the parameter list for each resource.
- Moved the list of resources in alphabetical order.
- Moved each resource parameter list into alphabetical order.
- Removed old text mentioning System Center.
Fixes #222 
Fixes #218
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/281)
=> README.md: Changes to contributing and resource list section

CHANGELOG.md, README.md
- Now the correct product name is written in the installation section, and a typo was also fixed.
- Fixed a typo in the Requirements section.
- Added link to Examples folder in the Examples section.
Fixes #283 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/284)
=> README.md: Small fixes to sections and fixed wrong product name

CHANGELOG.md
Missed a typo in the last merge. This will solve that. 
n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/299)
=> README.md Typo in CHANGELOG.md after recent merge

CHANGELOG.md, README.md
- Change the layout of the README.md to closer match the one of PSDscResources
- Added more detailed text explaining what operating systemes WMF5.0 can be installed on.
- Fixed alphabetical order, one resource was not in the right order.
- Verified all resource schema files with the README.md and fixed any errors.
Fixes #221
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/298)
=> README.md: Changes the layout to match HQRM resources

README.md
The documentation doesn't match the schema for xSQLServerDatabase.
Fixes #302
=> Fixed params for xSQLServerDatabase in README.md.

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, README.md
Changes to PULL_REQUEST_TEMPLATE and ISSUE_TEMPLATE
Fixes #224 
Fixes #225 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/305)
=> Changes to PULL_REQUEST_TEMPLATE and ISSUE_TEMPLATE

CHANGELOG.md, README.md
- Added security requirements section for resource xSQLServerEndpoint (issue #271).
- Added security requirements section for resource xSQLAOGroupEnsure (issue #271).
Fixes #271
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/304)
=> README.md: Changes to README.md

Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1, Tests/Unit/MSFT_xSQLServerScript.Tests.ps1, Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1
Resolves the bugs in tests for Pester v4.0.2 RC
Fixes #320 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/321)
=> xSQLServer: Resolves the bugs in tests for Pester v4.0.2 RC

CHANGELOG.md, appveyor.yml
- Changes to AppVeyor
- Now the deploy step are no longer failing when merging code into Dev. Neither is the deploy step failing if a contributor had AppVeyor connected to the fork of xSQLServer and pushing code to the fork.
Fixes #324
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/325)
=> AppVeyor: Resolves deploy step failing

Tests/Unit/MSFT_xSQLServerScript.Tests.ps1, appveyor.yml
Resolved the problem with the new common tests.
Fixes #372 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/374)
=> Resolves the problem with the new common tests

Examples/Resources/xSQLServerAlwaysOnAvailabilityGroup/1-CreateAvailabilityGroup.ps1, Examples/Resources/xSQLServerAlwaysOnAvailabilityGroup/2-RemoveAvailabilityGroup.ps1
Removing certifcate thumbprint from tests which otherwise will make the example fail to compile when testing with the new common tests.
n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/384)
=> xSQLServerAlwaysOnAvailabilityGroup: Remove cert thumbprint from tests

.codecov.yml, CHANGELOG.md, appveyor.yml
Enable Codecov.io reporting
fixes #387 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/386)
=> Enable Codecov.io reporting

CHANGELOG.md, README.md
Added CodeCov.io badge. It will not start working until next release of xSQLServer.
Fixes #389
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/390)
=> README.md: Adding badge for CodeCov.io

.codecov.yml, README.md, appveyor.yml
- Typo in README.md for requirements.
- Removed positional parameter in appveyor.yml.
- Raised CodeCov target to 68 (target should be 70).
n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/402)
=> xSQLServer: Minor changes to README.md, appveyor.yml and .codecov.yml

README.md
- Added Codecov badge for dev branch
n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/422)
=> README.md: Added Codecov badge for dev branch

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
- Changes to the GitHub PR and Issue templates
- Commented out descriptive help texts so they don't get submitted by mistake.
- Minor style changes in the templates.
n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/465)
=> xSQLServer: Changes to the GitHub PR and Issue templates

CHANGELOG.md, DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1
- Added support for vNext CTP 1.4 (issue #472).
- Some minor style changes.
Fixes #472 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/474)
=> xSQLServerSetup: Added support for vNext CTP 1.4

CHANGELOG.md, Examples/Resources/xSQLServerAvailabilityGroupListener/5-AddAvailabilityGroupListenerUsingDHCPWithDefaultServerSubnet.ps1, Examples/Resources/xSQLServerAvailabilityGroupListener/6-AddAvailabilityGroupListenerUsingDHCPWithSpecificSubnet.ps1, README.md
- Adding two more examples for xSQLServerAvailabilityGroupListener
- Fixed types for parameters in README.md for xSQLServerAlwaysOnAvailabilityGroup and xSQLServerAlwaysOnAvailabilityGroupReplica
None.
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/478)
=> xSQLServer: Adding two more examples and fixing README.md

DSCResources/MSFT_xSQLServerAvailabilityGroupListener/MSFT_xSQLServerAvailabilityGroupListener.psm1
- Changes to xSQLServerAvailabilityGroupListener
- Remove a row that was missed when the dependency of SQLPS was removed in PR #469
n/a
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/480)
=> xSQLServerAvailabilityGroupListener: Missed a row in PR #469

CHANGELOG.md, DSCResources/MSFT_xSQLServerEndpointPermission/MSFT_xSQLServerEndpointPermission.psm1, DSCResources/MSFT_xSQLServerEndpointPermission/MSFT_xSQLServerEndpointPermission.schema.mof, README.md, Tests/Unit/MSFT_xSQLServerEndpointPermission.Tests.ps1
- Changes to xSQLServerEndpointPermission
- Added description to the README.md
- Cleaned up code (issue #257 and issue #231)
- Now the default value for Ensure is 'Present'.
- Removed dependency of SQLPS provider (issue #483).
- Refactored tests so they use less code.
Fixes #257 
Fixes #231 
Fixes #483 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/485)
=> xSQLServerEndpointPermission: Removed dependency of SQLPS provider

CHANGELOG.md
Fixed typos in CHANGELOG.md before release.
n/a
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/515)
=> CHANGELOG.md: Fixed typos in 7.0.0.0 section

.github/ISSUE_TEMPLATE.md, CHANGELOG.md, CONTRIBUTING.md, README.md
Fixed typos in markdown files; CHANGELOG, CONTRIBUTING, README and ISSUE_TEMPLATE.
n/a
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/522)
=> xSQLServer: Fixed typos in markdown files

CHANGELOG.md, DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroup/MSFT_xSQLServerAlwaysOnAvailabilityGroup.psm1, DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupReplica/MSFT_xSQLServerAlwaysOnAvailabilityGroupReplica.psm1, en-US/xSQLServer.strings.psd1
Updated to return the exception raised when an error is thrown.
Fixes #542 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/543)
=> xSQLServerAlwaysOnAvailabilityGroup\Replica: Clarify error messages

CHANGELOG.md, README.md
- Changes to xSQLServerPermission
- Updated note in resource description to also mention ConnectSql permission.
n/a
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/561)
=> xSQLServerPermission: Updated note in resource description

CHANGELOG.md, DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupReplica/MSFT_xSQLServerAlwaysOnAvailabilityGroupReplica.schema.mof, README.md
Updated parameter description for parameter Name, so that it says it must be in the format SQLServer\InstanceName for named instance (issue #548).
- Changes to xSQLServerAlwaysOnAvailabilityGroupReplica
- Updated parameter description for parameter Name, so that it says it must be in the format SQLServer\InstanceName for named instance (issue #548).
Fixes #548
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/590)
=> xSQLServerAlwaysOnAvailabilityGroupReplica: Update description for parameter Name

CHANGELOG.md, DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1
* Changes to xSQLServerSetup
* Now it can detect Documentation Components correctly after the change in issue #591 (issue #628)
Fixes #628
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/629)
=> xSQLServerSetup: Fixes problem after merging PR #595

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md
* Changes to xSQLServer
* Updated PULL_REQUEST_TEMPLATE adding comment block around text. Also rearranged and updated texts (issue #572).
Fixes #572 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/600)
=> xSQLServer: Updated PULL_REQUEST_TEMPLATE

CHANGELOG.md, README.md
- Fixed CodeCov badge links in README.md.
None
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/640)
=> xSQLServer: Fixed CodeCov badge links in README.md

README.md
- Fixes codcov badge link that has a typo.
This is a fix for the previous merged PR #640. 😞  
None
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/644)
=> README.md: Fixes codcov badge link that has a typo

.gitignore, .vscode/settings.json, CHANGELOG.md, CONTRIBUTING.md
- Added VS Code workspace settings file with formatting settings matching the Style Guideline (issue #645). That will make it possible inside VS Code to press SHIFT+ALT+F, or press F1 and choose 'Format document' in the list. The PowerShell code will then be formatted according to the Style Guideline (although maybe not complete, but would help a long way).
Fixes #645 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/646)
=> xSQLServer: Added VS Code workspace settings file

CHANGELOG.md, Tests/Unit/xSQLServerHelper.Tests.ps1, xSQLServerHelper.psm1
- Changes to xSQLServerHelper
- Added tests for those helper functions that did not have tests.
None
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/643)
=> xSQLServerHelper: Added test for the rest of the helper functions

.vscode/settings.json, CHANGELOG.md
- Changes to VS Code workspace settings file
- Removed alignPropertyValuePairs setting since it does not align with the style guideline.
FIxes #648 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/647)
=> xSQLServer: Changes to VS Code workspace settings file

CHANGELOG.md, DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1
Adding MDS support for xSQLServerSetup by detecting feature configuration state from registry.
Fixes #486
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/488)
=> xSQLServerSetup: Add MDS feature detection to Get-TargetResource

CHANGELOG.md, DSCResources/MSFT_xSQLServerScript/MSFT_xSQLServerScript.psm1, DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1
Bug fixes that prevented Get-DscConfiguration to execute properly
Fixes #393 
Fixes #661 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/658)
=> xSQLServerSetup: Bug fixes that prevented Get-DscConfiguration to execute properly

.markdownlint.json, CHANGELOG.md, CONTRIBUTING.md, README.md, appveyor.yml
- Fixed lint error MD013 and MD036 in README.md.
- Updated .markdownlint.json to enable rule MD013.
- Fixed lint error MD013 in CHANGELOG.md.
- Fixed lint error MD013 in CONTRIBUTING.md.
This is the first step to opt-in for the common test for markdown files.
n/a
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/670)
=> xSQLServer: Fixed lint errors MD013 and MD036 in markdown files

CHANGELOG.md, README.md
- Added code block around types in README.md.
n/a
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/667)
=> README.md: Added code block around types in README.md

CHANGELOG.md, DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, DSCResources/MSFT_xSQLServerSetup/en-US/MSFT_xSQLServerSetup.strings.psd1
- Fixed localization support for MDS feature (issue #671).
Fixes #671 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/672)
=> xSQLServerSetup: Fixed localization support for MDS feature

CHANGELOG.md, xSQLServer.psd1
- Updated copyright information in xSQLServer.psd1.
This is from a issue in DscResources.
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/676)
=> xSQLServer: Updated copyright information in xSQLServer.psd1

CHANGELOG.md
- Changes to CHANGELOG.md
- Reordered the entries in the change log.
Fixes #674 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/677)
=> CHANGELOG.md: Reordered the entries in the change log.

CHANGELOG.md, DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1, DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.schema.mof, Examples/Resources/xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/1-AddDatabasesToAvailabilityGroup.ps1, Examples/Resources/xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/2-RemoveDatabasesFromAvailabilityGroup.ps1, Examples/Resources/xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/3-MatchDefinedDatabasesInAvailabilityGroup.ps1, Tests/Unit/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.Tests.ps1, xSQLServer.psd1
Refactored as a MOF based resource due to issues with testing in Pester on PowerShell 5.
Fixes #673 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/682)
=> xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership: Refactored as a MOF based resource

.markdownlint.json, CHANGELOG.md
- Added back .markdownlint.json so that lint rule MD013 is enforced.
n/a
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/684)
=> xSQLServer: Added back .markdownlint.json so that lint rule MD013 is enforced

CHANGELOG.md, LICENSE
Updated year to 2017 in license file (issue #711).
- Updated year to 2017 in license file (issue #711).
Fixes #711 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/712)
=> xSQLServer: Updated year to 2017 in license file

CHANGELOG.md, Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1, Tests/Integration/MSFT_xSQLServerSetup.config.ps1
- Added a simple integration test (issue #709).
Fixes #709 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/710)
=> xSQLServerSetup: Adds a simple integration test

CHANGELOG.md, DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1
Adds the whitespace needed for the rules to pass on xSqlServerSetup.
Fixes #729 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/762)
=> xSQLServerSetup: Fix PSSA Rules

CHANGELOG.md, DSCResources/MSFT_xSQLServerDatabasePermission/MSFT_xSQLServerDatabasePermission.psm1
As raised in #725 there are PSSA errors due to Mandatory parameters having values specified for them in the param block. This removes that and fixes the error.
Fixes #725 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/766)
=> xSQLServerDatabasePermission: Fix PSSA issues

CHANGELOG.md, DSCResources/MSFT_xSQLServerAlwaysOnService/MSFT_xSQLServerAlwaysOnService.psm1
As raised in #724 there are PSSA errors caused by $null comparison being the wrong way round.
Fixes #724
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/765)
=> xSQLServerAlwaysOnService: Fix PSSA rules

CHANGELOG.md
- Fix issues found in CHANGELOG.md from merged PRs.
I messed up and missed some minor issues in the CHANGELOG.md in the last two PR's. Sorry about that.
n/a
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/794)
=> xSQLServer: Fix issues found in CHANGELOG.md from merged PRs

CHANGELOG.md, DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupReplica/MSFT_xSQLServerAlwaysOnAvailabilityGroupReplica.psm1
Fixed the formatting for the AvailabilityGroupNotFound error message.
Fixes #793
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/797)
=> xSQLServerAlwaysOnAvailabilityGroupReplica: Fixed AvailabilityGroupNotFound Formatting

CHANGELOG.md
- Fix minor typos in CHANGELOG.md
n/a
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/815)
=> xSQLServer: Fix minor typos in CHANGELOG.md

CHANGELOG.md, Tests/Unit/CommonResourceHelper.Tests.ps1, Tests/Unit/MSFT_xSQLServerAlias.Tests.ps1, Tests/Unit/MSFT_xSQLServerAvailabilityGroupListener.Tests.ps1, Tests/Unit/MSFT_xSQLServerDatabase.Tests.ps1, Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1, Tests/Unit/MSFT_xSQLServerDatabasePermission.Tests.ps1, Tests/Unit/MSFT_xSQLServerDatabaseRecoveryModel.Tests.ps1, Tests/Unit/MSFT_xSQLServerDatabaseRole.Tests.ps1, Tests/Unit/MSFT_xSQLServerEndpoint.Tests.ps1, Tests/Unit/MSFT_xSQLServerEndpointPermission.Tests.ps1, Tests/Unit/MSFT_xSQLServerEndpointState.Tests.ps1, Tests/Unit/MSFT_xSQLServerMaxDop.Tests.ps1, Tests/Unit/MSFT_xSQLServerMemory.Tests.ps1, Tests/Unit/MSFT_xSQLServerNetwork.Tests.ps1, Tests/Unit/MSFT_xSQLServerPermission.Tests.ps1, Tests/Unit/MSFT_xSQLServerRSConfig.Tests.ps1, Tests/Unit/MSFT_xSQLServerRole.Tests.ps1, Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1, Tests/Unit/MSFT_xWaitForAvailabilityGroup.Tests.ps1, Tests/Unit/xSQLServerHelper.Tests.ps1, appveyor.yml
- Fix problem with tests breaking with Pester 4.0.7 (issue #807).
Fixes #807 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/828)
=> xSQLServer: Fix problem with tests breaking with Pester 4.0.7

CHANGELOG.md
- Fix CHANGELOG.md after recent merge.
n/a
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/889)
=> xSQLServer: Fix CHANGELOG.md after recent merge

CHANGELOG.md
- Fixes broken links to issues in the CHANGELOG.md.
n/a
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsqlserver/894)
=> xSQLServer: Fixes broken links to issues in the CHANGELOG.md

CHANGELOG.md, CONTRIBUTING.md
Added additional details about the naming convention for SqlServerDsc.
Fixes #909
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/918)
=> CONTRIBUTING: Explain naming convention

CHANGELOG.md, DSCResources/MSFT_SqlAGDatabase/MSFT_SqlAGDatabase.psm1, Tests/Unit/MSFT_SqlAGDatabase.Tests.ps1
Updated SqlAGDatabase to ensure the database name matching is case insensitive.
Fixes #912 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/921)
=> SqlAGDatabase: Case Sensitivity

CHANGELOG.md, Tests/SqlServerDscCommon.Tests.ps1
- Added new common test (regression test) for validating the long path
issue for compiling resources in Azure Automation.
This test should be moved to DscResource.Tests in the future (see issue https://github.com/PowerShell/DscResource.Tests/issues/188).
n/a
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/937)
=> SqlServerDsc: Regression test for validating the long path issue

CHANGELOG.md
- Changes to CHANGELOG.md
- Fix order and typo.
Fixes #942 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/944)
=> CHANGELOG.md: Fix order and typo

CHANGELOG.md, README.md
- Fix resources in alphabetical order in README.md (issue #908).
Fixes #908 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/945)
=> README.md: Fix resources in alphabetical order

CHANGELOG.md, DSCResources/MSFT_SqlAlias/MSFT_SqlAlias.psm1
Fix for issue #949 where creation of the alias failed if the reg keys did not exist
Fixes #949 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/950)
=> SQLAlias: Fix for issue 949

CHANGELOG.md, DSCResources/MSFT_SqlServiceAccount/MSFT_SqlServiceAccount.psm1, DSCResources/MSFT_SqlServiceAccount/en-US/MSFT_SqlServiceAccount.strings.psd1, Tests/Unit/MSFT_SqlServiceAccount.Tests.ps1
Corrected an issue with `SqlServiceAccount` where default services were not properly detected.
Fixes #930 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/947)
=> SqlServiceAccount: Corrected issue with detecting service names

CHANGELOG.md, DSCResources/MSFT_SqlServiceAccount/MSFT_SqlServiceAccount.psm1, DSCResources/MSFT_SqlServiceAccount/MSFT_SqlServiceAccount.schema.mof, Examples/Resources/SqlServiceAccount/1-ConfigureServiceAccount-UserAccount.ps1, Examples/Resources/SqlServiceAccount/2-ConfigureServiceAccount-VirtualAccount.ps1, README.md
- Made the description of parameter RestartService more descriptive (issue #960).
Fixes #960 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/962)
=>  SqlServiceAccount: Parameter RestartService more descriptive in README.md

CHANGELOG.md, DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.psm1, DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.schema.mof, Examples/Resources/SqlSetup/1-InstallDefaultInstanceSingleServer.ps1, README.md, Tests/Integration/MSFT_SqlSetup.Integration.Tests.ps1, Tests/Integration/MSFT_SqlSetup.config.ps1, Tests/Unit/MSFT_SqlSetup.Tests.ps1
- Added parameter `ASServerMode` to support installing Analysis Services in
Multidimensional mode, Tabular mode and PowerPivot mode.
- Added integration tests for testing Analysis Services Multidimensional mode
and Tabular mode.
***Note:** This continues the work by @craigofnz in PR #391.*
Fixes #388 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/964)
=> SqlSetup: Added ASServerMode parameter

CHANGELOG.md, DSCResources/MSFT_SqlDatabase/MSFT_SqlDatabase.psm1, DSCResources/MSFT_SqlServerReplication/MSFT_SqlServerReplication.psm1
- Changes to SqlDatabase
- Fix minor Script Analyzer warning.
- Changes to SqlServerReplication
- Fix Script Analyzer warning (issue #263).
FIxes #263 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/969)
=> SqlServerDsc: Fix PSSA rule warnings

CHANGELOG.md, Tests/Integration/MSFT_SqlServerLogin.Integration.Tests.ps1, Tests/Integration/MSFT_SqlServerLogin.config.ps1, Tests/Integration/README.md
- Changes to xSqlServerLogin
- Added integration tests (issue #748).
Fixes #748 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/998)
=> SqlServerLogin: Added integration tests

CHANGELOG.md, Tests/Integration/MSFT_SqlAlwaysOnService.Integration.Tests.ps1, Tests/Integration/MSFT_SqlAlwaysOnService.config.ps1, Tests/Integration/MSFT_SqlDatabaseDefaultLocation.Integration.Tests.ps1, Tests/Integration/MSFT_SqlRS.Integration.Tests.ps1, Tests/Integration/MSFT_SqlRS.config.ps1, Tests/Integration/MSFT_SqlServerDatabaseMail.Integration.Tests.ps1, Tests/Integration/MSFT_SqlServerLogin.Integration.Tests.ps1, Tests/Integration/MSFT_SqlServiceAccount.Integration.Tests.ps1, Tests/Integration/MSFT_SqlSetup.Integration.Tests.ps1, Tests/Integration/MSFT_SqlSetup.config.ps1
- Refactor integration tests slightly to improve run time performance (issue #1001).
- Changes to SqlDatabaseDefaultLocation
- Refactor integration tests slightly to improve run time performance (issue #1001).
- Refactor integration tests slightly to improve run time performance (issue #1001).
- Refactor integration tests slightly to improve run time performance (issue #1001).
- Refactor integration tests slightly to improve run time performance (issue #1001).
- Changes to SqlServerLogin
- Refactor integration tests slightly to improve run time performance (issue #1001).
- Changes to SqlServerDatabaseMail
- Refactor integration tests slightly to improve …
=> SqlServerDsc: Refactor integration tests to improve run time performance

CHANGELOG.md, Examples/Resources/SqlServerRole/1-AddServerRole.ps1
- Changes to SqlServerRole
- Updated example to add two server roles in the same configuration.
n/a
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1004)
=> SqlServerRole: Updated example to add two server roles in the same configuration

CHANGELOG.md, README.md
- Updated the security token for AppVeyor status badge in README.md. When we
renamed the repository the security token was changed (issue #1012).
Fixes #1012 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1013)
=> SqlServerDsc: Updated the security token for AppVeyor status badge

DSCResources/MSFT_SqlServerDatabaseMail/MSFT_SqlServerDatabaseMail.psm1, DSCResources/MSFT_SqlServerDatabaseMail/en-US/MSFT_SqlServerDatabaseMail.strings.psd1, Examples/Resources/SqlServerDatabaseMail/1-EnableDatabaseMail.ps1, Examples/Resources/SqlServerDatabaseMail/2-DisableDatabaseMail.ps1, README.md, Tests/Integration/MSFT_SqlServerDatabaseMail.config.ps1, Tests/Unit/MSFT_SqlServerDatabaseMail.Tests.ps1
- Changes to SqlServerDatabaseMail
- Removed the enabling and disabling of Database Mail XPs and instead let
the resource SqlServerConfiguration do that configuration (issue #1011).
*Did not add this change to the change log since I thought this issue is covered by an other entry.*
Fixes #1011 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1016)
=> SqlServerDatabaseMail: Removed the enabling and disabling of Database Mail XPs

CHANGELOG.md, DSCResources/MSFT_SqlAGListener/MSFT_SqlAGListener.psm1, DSCResources/MSFT_SqlAGReplica/MSFT_SqlAGReplica.psm1, DSCResources/MSFT_SqlScript/MSFT_SqlScript.psm1, DSCResources/MSFT_SqlServerConfiguration/MSFT_SqlServerConfiguration.psm1, DSCResources/MSFT_SqlServerLogin/MSFT_SqlServerLogin.psm1, DSCResources/MSFT_SqlServerMaxDop/MSFT_SqlServerMaxDop.psm1, DSCResources/MSFT_SqlServerMemory/MSFT_SqlServerMemory.psm1, DSCResources/MSFT_SqlServerPermission/MSFT_SqlServerPermission.psm1, DSCResources/MSFT_SqlServerReplication/MSFT_SqlServerReplication.psm1, DSCResources/MSFT_SqlServiceAccount/MSFT_SqlServiceAccount.psm1, DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.psm1, DSCResources/MSFT_SqlWindowsFirewall/MSFT_SqlWindowsFirewall.psm1, SqlServerDscHelper.psm1, Tests/Unit/MSFT_SqlDatabaseDefaultLocation.Tests.ps1, Tests/Unit/MSFT_SqlServerMemory.Tests.ps1
- Added PSSA rule 'PSUseDeclaredVarsMoreThanAssignments' override in the
function Set-TargetResource for the variable $global:DSCMachineStatus.
- Style cleanup in helper function ConvertTo-Decimal.
- Changes to SqlServerDscHelper
- Fixed typo in comment-base help for helper function Test-AvailabilityReplicaSeedingModeAutomatic.
- Changes to SqlServerMemory
- Minor style cleanup of code in tests.
- Changes to SqlDatabaseDefaultLocation
- Minor style cleanup of code in tests.
- Changes to SqlServerMemory
- Minor style cleanup of code in tests.
- Changes to SqlAGListener
- Fixed typo in comment-based help.
- Minor code style cleanup. Removed unused variable and instead piped the cmdlet
Join-SqlAvailabilityGroup …
=> SqlServerDsc: Minor style cleanup of code and typos

CHANGELOG.md, Tests/Unit/MSFT_SqlAG.Tests.ps1, Tests/Unit/MSFT_SqlAGDatabase.Tests.ps1, Tests/Unit/MSFT_SqlAGListener.Tests.ps1, Tests/Unit/MSFT_SqlAGReplica.Tests.ps1, Tests/Unit/MSFT_SqlAlias.Tests.ps1, Tests/Unit/MSFT_SqlAlwaysOnService.Tests.ps1, Tests/Unit/MSFT_SqlScript.Tests.ps1, Tests/Unit/MSFT_SqlServerConfiguration.Tests.ps1, Tests/Unit/MSFT_SqlServerEndpoint.Tests.ps1, Tests/Unit/MSFT_SqlServerLogin.Tests.ps1, Tests/Unit/MSFT_SqlSetup.Tests.ps1, Tests/Unit/SqlServerDSCHelper.Tests.ps1
- Style cleanup in helper function tests.
- Changes to SqlAG
- Fixed typos in tests.
- Style cleanup in tests.
- Changes to SqlAGDatabase
- Style cleanup in tests.
- Changes to SqlAGListener
- Style cleanup in tests.
- Style cleanup in tests.
- Changes to SqlAlias
- Style cleanup in tests
- Style cleanup in tests
- Changes to SqlScript
- Style cleanup in tests
- Changes to SqlServerConfiguration
- Style cleanup in tests
- Changes to SqlServerEndpoint
- Style cleanup in tests
- Changes to SqlServerLogin
- Style cleanup in tests
- Style cleanup in tests
n/a
**Task list:**
---
This change is [<img …
=> SqlServerDsc: style cleanup in tests

DSCResources/MSFT_SqlServerNetwork/MSFT_SqlServerNetwork.psm1, DSCResources/MSFT_SqlServiceAccount/MSFT_SqlServiceAccount.psm1, SqlServerDscHelper.psm1, Tests/Unit/CommonResourceHelper.Tests.ps1, Tests/Unit/MSFT_SqlAGDatabase.Tests.ps1, Tests/Unit/MSFT_SqlScript.Tests.ps1, Tests/Unit/MSFT_SqlServerLogin.Tests.ps1, Tests/Unit/MSFT_SqlServerPermission.Tests.ps1, Tests/Unit/MSFT_SqlServerReplication.Tests.ps1, Tests/Unit/MSFT_SqlSetup.Tests.ps1, Tests/Unit/MSFT_SqlWindowsFirewall.Tests.ps1, Tests/Unit/SqlServerDSCHelper.Tests.ps1
- Style cleanup of New-Object
*There are already appropriate entries in the CHANGELOG.md for this change.*
n/a
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1025)
=> SqlServerDsc: Style cleanup of New-Object

CHANGELOG.md, DSCResources/MSFT_SqlScript/MSFT_SqlScript.psm1, Examples/Resources/SqlScript/1-RunScriptUsingSQLAuthentication.ps1, Examples/Resources/SqlScript/2-RunScriptUsingWindowsAuthentication.ps1, Examples/Resources/SqlScript/3-RunScriptCompleteExample.ps1, README.md, Tests/Integration/MSFT_SqlScript.Integration.Tests.ps1, Tests/Integration/MSFT_SqlScript.config.ps1, Tests/Integration/MSFT_SqlSetup.Integration.Tests.ps1, Tests/Integration/MSFT_SqlSetup.config.ps1, Tests/Integration/README.md
- Changes to SqlScript
- Updated examples.
- Added integration tests.
Fixes #757
Fixes #547
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1027)
=> SqlScript: Added integration test

CHANGELOG.md, DSCResources/MSFT_SqlAGReplica/MSFT_SqlAGReplica.psm1, README.md
- Updated description for parameter Name in README.md and in comment-based help (issue #1034).
Fixes #1034 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1035)
=> SqlAGReplica: Updated description for parameter Name

CHANGELOG.md, Examples/Resources/SqlSetup/4-InstallNamedInstanceInFailoverClusterFirstNode.ps1, Tests/Integration/MSFT_SqlRS.config.ps1, Tests/Integration/MSFT_SqlSetup.config.ps1
Replace references of xStorage with the renamed StorageDsc dsc resource module.
Fixes #1038 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1056)
=> Replaced xStorage references with the HQ StorageDsc dsc resource module.

CHANGELOG.md, DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.psm1, DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.schema.mof, README.md
Clearly document and validate SecurityMode Parameter.
Fixes #1010 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1058)
=> SqlSetup: Clearly document and validate SecurityMode Parameter

CHANGELOG.md, Tests/Unit/MSFT_SqlAlias.Tests.ps1
Updating the Unit tests for DSC Resources to utilize Unit Test Template Version: 1.2.1
This will partly fix the issue #999 
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1063)
=> SqlAlias: Updated DSC Resource tests with Unit Test Template Version: 1.2.1

CHANGELOG.md, Tests/Unit/MSFT_SqlWindowsFirewall.Tests.ps1
This updates the SqlWindowsFirewall DSC Resources unit test to use the newest template.
Fixes #1089 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1091)
=> SqlWindowsFirewall: Unit test uses the latest unit test template

.github/ISSUE_TEMPLATE.md, CHANGELOG.md
- Updated ISSUE_TEMPLATE.md with a note about sensitive information (issue #1092).
Fixes #1092 
--- …
=> ISSUE_TEMPLATE: Updated with a note about sensitive information

CHANGELOG.md
To recognize our contributors that put in work to make the resources in this module better I suggest that from this release we add their name to the CHANGELOG.md before each entry that has been contributed.
Please see the correct rendering here: https://github.com/johlju/SqlServerDsc/blob/4ec390e739bdcebfc64c3eb0ae76548a87e4ca3b/CHANGELOG.md
This is discussed in issue https://github.com/PowerShell/DscResources/issues/295#issuecomment-373115320.
[DSC Resource Style …
=> SqlServerDsc: Add contributor names to CHANGELOG.md

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, DSCResources/MSFT_SqlServerLogin/MSFT_SqlServerLogin.psm1, DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.psm1, DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.schema.mof, Examples/Resources/SqlSetup/4-InstallNamedInstanceInFailoverClusterFirstNode.ps1, README.md, SQLServerDsc.psd1, SqlServerDscHelper.psm1, Tests/Integration/MSFT_SqlRS.config.ps1, Tests/Integration/MSFT_SqlSetup.config.ps1, Tests/Unit/MSFT_SqlAlias.Tests.ps1, Tests/Unit/MSFT_SqlSetup.Tests.ps1, Tests/Unit/MSFT_SqlWindowsFirewall.Tests.ps1, Tests/Unit/SqlServerDSCHelper.Tests.ps1
Releasing version 11.1.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1094)
=> Release of version 11.1.0.0 of SqlServerDsc

CHANGELOG.md, Tests/Integration/MSFT_SqlAlwaysOnService.Integration.Tests.ps1, Tests/Integration/MSFT_SqlAlwaysOnService.config.ps1, Tests/Integration/README.md, Tests/TestHelpers/CommonTestHelper.psm1
- Changes to CommonTestHelpers
- Added new test helper functions in the CommonTestHelpers module. These are used
by the integration tests.
- Updated the integration tests to use a loopback adapter to be less intrusive
in the build worker environment.
n/a
and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestP …
=> SqlAlwaysOnService: Update integration tests to use loopback adapter

.MetaTestOptIn.json, CHANGELOG.md, DSCResources/MSFT_SqlServerDatabaseMail/MSFT_SqlServerDatabaseMail.psm1, DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.psm1
- Enabled PSSA rule violations to fail build in the CI environment.
- Fixed Script Analyzer rule error.
- Changes to SqlServerDatabaseMail
- Fixed Script Analyzer rule error.
n/a
---
This change is [<img …
=> SqlServerDsc: Enabled PSSA rule violations to fail build

CHANGELOG.md, Tests/Integration/MSFT_SqlAlwaysOnService.Integration.Tests.ps1, Tests/Integration/MSFT_SqlAlwaysOnService.config.ps1, Tests/Integration/MSFT_SqlDatabaseDefaultLocation.Integration.Tests.ps1, Tests/Integration/MSFT_SqlDatabaseDefaultLocation.config.ps1, Tests/Integration/MSFT_SqlRS.Integration.Tests.ps1, Tests/Integration/MSFT_SqlRS.config.ps1, Tests/Integration/MSFT_SqlScript.Integration.Tests.ps1, Tests/Integration/MSFT_SqlScript.config.ps1, Tests/Integration/MSFT_SqlServerDatabaseMail.Integration.Tests.ps1, Tests/Integration/MSFT_SqlServerDatabaseMail.config.ps1, Tests/Integration/MSFT_SqlServerLogin.Integration.Tests.ps1, Tests/Integration/MSFT_SqlServerLogin.config.ps1, Tests/Integration/MSFT_SqlServerRole.Integration.Tests.ps1, Tests/Integration/MSFT_SqlServerRole.config.ps1, Tests/Integration/MSFT_SqlServiceAccount.Integration.Tests.ps1, Tests/Integration/MSFT_SqlServiceAccount.config.ps1, Tests/Integration/MSFT_SqlSetup.Integration.Tests.ps1, Tests/Integration/MSFT_SqlSetup.config.ps1, appveyor.yml
- Moved decoration for integration test to resolve a breaking change in
DscResource.Tests.
***Note:** This PR needs to be updated when the PR is merged in DscResource.Tests. Right now it's uysing the PR branch for testing.*
n/a
---
This change …
=> SqlServerDsc: Moved decoration for integration test

CHANGELOG.md
Fix minor typo in CHANGELOG.md
n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1130)
=> SqlServerDsc: Fix typo in CHANGELOG.md

.github/stale.yml, CHANGELOG.md
- Activated the GitHub App Stale on the GitHub repository.
As per issue https://github.com/PowerShell/DscResources/issues/401
--- …
=> Activate Stale GitHub App (bot)

.github/stale.yml
- Update Stale
- Adding 'resource proposal' as exempt label for issues
*Have not added an entry to the CHANGELOG.md, because there are already one covering this.*
Fixes #1135 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> Adding 'resource proposal' as exempt label for issues

.github/stale.yml
Updated Stale to match configuration in issue PowerShell/DscResources#1133.
Fixes #1137
*Already an entry in the change log that covers this.*
--- …
=> Updated Stale configuration

SqlServerDscHelper.psm1
- Fix correct verbose message for Import-SQLPSModule
Already a entry in the change log that covers this.
This is a fix for a previous PR.
--- …
=> Fix correct verbose message for Import-SQLPSModule

CHANGELOG.md
Fix change log after recent merge
n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1211)
=> Fix change log after recent merge

CHANGELOG.md, SqlServerDscHelper.psm1, Tests/Unit/SqlServerDSCHelper.Tests.ps1
- Changes to SqlServerDscHelper
- Fix style guideline lint errors.
- Changes to Connect-SQL
- Adding verbose message in Connect-SQL so it
now shows the username that is connecting.
- Changes to Import-SQLPS
- Fixed so that when importing SQLPS it imports
using the path (and not the .psd1 file).
- Fixed so that the verbose message correctly
shows the name, version and path when importing
the module SQLPS (it did show correctly for the
SqlServer module).
n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1221)
=> SqlServerDscHelper: Fixes for Connect-SQL and Import-SQLPS

README.md
- Move SqlServerSecureConnection resource to be in alphabetical order.
Not updated the CHANGELOG.md since it is already a suitable entry there.
n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1231)
=> README.md: SqlServerSecureConnection in alphabetical order

CHANGELOG.md, README.md
- Changes to README.md.
- Updated the Installation section in the README.md.
n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1234)
=> Updated the Installation section in the README.md

CHANGELOG.md, Tests/Integration/MSFT_SqlAlwaysOnService.config.ps1
- Updated integration tests to use NetworkingDsc
([issue #1129](https://github.com/PowerShell/SqlServerDsc/issues/1129)).
- Fixes #1129
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1229)
=> SqlAlwaysOnService: Updated integration tests to use NetworkingDsc

CHANGELOG.md, Examples/README.md
Added a link to the new xADObjectPermissionEntry examples in xActiveDirectory, fixed a broken link and a typo.
n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1241)
=> Fixed examples README

CHANGELOG.md
Fix minor typos in CHANGELOG.md
n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1274)
=> Fix minor typos in CHANGELOG.md

CHANGELOG.md
Re-order entries in CHANGELOG.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1283)
=> Re-order entries in CHANGELOG.md

CHANGELOG.md
- Fix CHANGELOG.md after recent merge.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1288)
=> Fix CHANGELOG.md after recent merge

CHANGELOG.md, DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.psm1, Tests/Unit/MSFT_SqlSetup.Tests.ps1
SqlSetup:Fixes issue #1254
- Fixes #1254
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1299)
=> SqlSetup:Fixes issue #1254

CHANGELOG.md, DSCResources/MSFT_SqlScript/MSFT_SqlScript.psm1, DSCResources/MSFT_SqlScriptQuery/MSFT_SqlScriptQuery.psm1, Modules/DscResource.Common/DscResource.Common.psm1
- Changes to SqlScript
- Correctly passes the `$VerbosePreference` to the helper function
`Invoke-SqlScript` so that `PRINT` statements is outputted correctly
when verbose output is requested, e.g
`Start-DscConfiguration -Verbose`.
- Changes to SqlScriptQuery
- Correctly passes the `$VerbosePreference` to the helper function
`Invoke-SqlScript` so that `PRINT` statements is outputted correctly
when verbose output is requested, e.g
`Start-DscConfiguration -Verbose`.
This change is already covered in existing integration tests.
- Fixes #1317 
--- …
=> SqlScript/SqlScriptQuery: Passes $VerbosePreference to helper function

CHANGELOG.md, DSCResources/MSFT_SqlSetup/en-US/MSFT_SqlSetup.strings.psd1, DSCResources/MSFT_SqlSetup/sv-SE/MSFT_SqlSetup.strings.psd1, Modules/DscResource.Common/DscResource.Common.psm1, Modules/DscResource.Common/en-US/DscResource.Common.strings.psd1, Modules/DscResource.Common/sv-SE/DscResource.Common.strings.psd1
- Concatenated Robocopy localization strings (issue #694).
There are already unit tests covering this change.
- Fixes #694 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1323)
=> SqlSetup: Concatenated Robocopy localization strings

CHANGELOG.md, DSCResources/MSFT_SqlWaitForAG/MSFT_SqlWaitForAG.psm1, DSCResources/MSFT_SqlWaitForAG/en-US/MSFT_SqlWaitForAG.strings.psd1, Tests/Unit/MSFT_SqlWaitForAG.Tests.ps1
- Changes to SqlWaitForAG
- Added en-US localization (issue #625).
- Fixes #625 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1325)
=> SqlWaitForAG: Added localization

CHANGELOG.md, DSCResources/MSFT_SqlScript/MSFT_SqlScript.psm1, DSCResources/MSFT_SqlScript/en-US/MSFT_SqlScript.strings.psd1, DSCResources/MSFT_SqlScriptQuery/MSFT_SqlScriptQuery.psm1, DSCResources/MSFT_SqlScriptQuery/en-US/MSFT_SqlScriptQuery.strings.psd1, Tests/Unit/MSFT_SqlScript.Tests.ps1, Tests/Unit/MSFT_SqlScriptQuery.Tests.ps1
- Changes to SqlScript
- Added en-US localization (issue #624).
- Added additional unit tests for code coverage.
- Changes to SqlScriptQuery
- Added en-US localization.
- Added additional unit tests for code coverage.
- Fixes #624 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1324)
=> SqlScript/SqlScriptQuery: Added localization

CHANGELOG.md, DSCResources/MSFT_SqlServerPermission/MSFT_SqlServerPermission.psm1, DSCResources/MSFT_SqlServerPermission/en-US/MSFT_SqlServerPermission.strings.psd1, Modules/DscResource.Common/en-US/DscResource.Common.strings.psd1, Modules/DscResource.Common/sv-SE/DscResource.Common.strings.psd1, Tests/Unit/MSFT_SqlServerPermission.Tests.ps1
- Changes to SqlServerPermission
- Added en-US localization (issue #619).
- Fixes #619 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1328)
=> SqlServerPermission: Added localization

CHANGELOG.md, DSCResources/MSFT_SqlServerMaxDop/MSFT_SqlServerMaxDop.psm1, DSCResources/MSFT_SqlServerMaxDop/en-US/MSFT_SqlServerMaxDop.strings.psd1, Modules/DscResource.Common/en-US/DscResource.Common.strings.psd1, Modules/DscResource.Common/sv-SE/DscResource.Common.strings.psd1, Tests/Unit/MSFT_SqlServerMaxDop.Tests.ps1
- Changes to SqlServerMaxDop
- Added en-US localization (issue #616).
- Fixes #616 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1332)
=> SqlServerMaxDop: Added localization

CHANGELOG.md, DSCResources/MSFT_SqlRS/MSFT_SqlRS.psm1, DSCResources/MSFT_SqlRS/MSFT_SqlRS.schema.mof, DSCResources/MSFT_SqlRS/en-US/MSFT_SqlRS.strings.psd1, README.md, Tests/Unit/MSFT_SqlRS.Tests.ps1
Reporting Services need to be restarted after a settings change (e.g. reserved URLs).
In addition to that, a parameter has been added, `$SuppressRestart`, which if set, suppresses Reporting Services restart, even after initialisation.
- Fixes #1331
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1334)
=> SqlRs: [#1331] Reporting Services are restarted on settings change

CHANGELOG.md, DSCResources/MSFT_SqlServerLogin/MSFT_SqlServerLogin.psm1, DSCResources/MSFT_SqlServerLogin/en-US/MSFT_SqlServerLogin.strings.psd1, Modules/DscResource.Common/en-US/DscResource.Common.strings.psd1, Modules/DscResource.Common/sv-SE/DscResource.Common.strings.psd1, Modules/DscResource.LocalizationHelper/DscResource.LocalizationHelper.psm1, Tests/Unit/DscResource.LocalizationHelper.Tests.ps1, Tests/Unit/MSFT_SqlServerLogin.Tests.ps1
- Changes to SqlServerLogin
- Added en-US localization (issue #615).
- Added unit tests to improved code coverage.
- Fixes #615 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1333)
=> SqlServerLogin: Added localization

CHANGELOG.md, DSCResources/MSFT_SqlServerEndpoint/MSFT_SqlServerEndpoint.psm1, DSCResources/MSFT_SqlServerEndpoint/en-US/MSFT_SqlServerEndpoint.strings.psd1, DSCResources/MSFT_SqlServerEndpointPermission/MSFT_SqlServerEndpointPermission.psm1, DSCResources/MSFT_SqlServerEndpointPermission/en-US/MSFT_SqlServerEndpointPermission.strings.psd1, DSCResources/MSFT_SqlServerEndpointState/MSFT_SqlServerEndpointState.psm1, DSCResources/MSFT_SqlServerEndpointState/en-US/MSFT_SqlServerEndpointState.strings.psd1, Modules/DscResource.Common/en-US/DscResource.Common.strings.psd1, Modules/DscResource.Common/sv-SE/DscResource.Common.strings.psd1, Tests/Unit/MSFT_SqlServerEndpoint.Tests.ps1, Tests/Unit/MSFT_SqlServerEndpointPermission.Tests.ps1, Tests/Unit/MSFT_SqlServerEndpointState.Tests.ps1
- Changes to SqlServerEndpoint
- Added en-US localization (issue #611).
- Changes to SqlServerEndpointPermission
- Added en-US localization (issue #612).
- Changes to SqlServerEndpointState
- Added en-US localization (issue #613).
- Fixes #611 
- Fixes #612 
- Fixes #613 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1337)
=> SqlServerEndpoint*: Added localization

CHANGELOG.md, DSCResources/MSFT_SqlDatabaseRole/MSFT_SqlDatabaseRole.psm1, DSCResources/MSFT_SqlDatabaseRole/en-US/MSFT_SqlDatabaseRole.strings.psd1, Modules/DscResource.Common/en-US/DscResource.Common.strings.psd1, Modules/DscResource.Common/sv-SE/DscResource.Common.strings.psd1, Tests/Unit/MSFT_SqlDatabaseRole.Tests.ps1
- Changes to SqlDatabaseRole
- Added en-US localization (issue #610).
- Fixes #610
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1338)
=> SqlDatabaseRole: Added localization

CHANGELOG.md, DSCResources/MSFT_SqlDatabaseOwner/MSFT_SqlDatabaseOwner.psm1, DSCResources/MSFT_SqlDatabaseOwner/en-US/MSFT_SqlDatabaseOwner.strings.psd1, Modules/DscResource.Common/en-US/DscResource.Common.strings.psd1, Modules/DscResource.Common/sv-SE/DscResource.Common.strings.psd1, Tests/Unit/MSFT_SqlDatabaseOwner.Tests.ps1
- Changes to SqlDatabaseOwner
- Added en-US localization (issue #607).
- Fixes #607 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1342)
=> SqlDatabaseOwner: Added localization

CHANGELOG.md, DSCResources/MSFT_SqlAGListener/MSFT_SqlAGListener.psm1, DSCResources/MSFT_SqlAGListener/en-US/MSFT_SqlAGListener.strings.psd1, Modules/DscResource.Common/en-US/DscResource.Common.strings.psd1, Modules/DscResource.Common/sv-SE/DscResource.Common.strings.psd1, Tests/Unit/MSFT_SqlAGListener.Tests.ps1
- Changes to SqlAGListener
- Added en-US localization (issue #604).
- Fixes #604 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1346)
=> SqlAGListener: Added localization

CHANGELOG.md, DSCResources/MSFT_SqlAlwaysOnService/MSFT_SqlAlwaysOnService.psm1, DSCResources/MSFT_SqlAlwaysOnService/en-US/MSFT_SqlAlwaysOnService.strings.psd1, Modules/DscResource.Common/en-US/DscResource.Common.strings.psd1, Modules/DscResource.Common/sv-SE/DscResource.Common.strings.psd1, Tests/Unit/MSFT_SqlAlwaysOnService.Tests.ps1
- Added en-US localization (issue #603).
- Fixes #603 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1347)
=> SqlAlwaysOnService: Added localization

CHANGELOG.md, DSCResources/MSFT_SqlAlias/MSFT_SqlAlias.psm1, DSCResources/MSFT_SqlAlias/en-US/MSFT_SqlAlias.strings.psd1, Tests/Unit/MSFT_SqlAlias.Tests.ps1
- Changes to SqlAlias
- Added en-US localization (issue #602).
- Removed ShouldProcess for the code, since it has no purpose in a DSC
resource (issue #242).
- Fixes #242 
- Fixes #602
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1348)
=> SqlAlias: Added localization

CHANGELOG.md, DSCResources/MSFT_SqlRS/MSFT_SqlRS.psm1, Tests/Unit/MSFT_SqlRS.Tests.ps1
A fix for Reporting Services initialization on SQL Standard and lower editions
An explicit call to `InitializeReportServer` CIM method is not needed when initialising Reporting Services, since the call to `SetDatabaseConnection` CIM method initialises it.
An explicit call to `InitializeReportServer` after `SetDatabaseConnection` on SQL Standard and lower editions fails since SSRS attempts to configure scale-out deployment, which is not supported on SQL Standard and lower editions.
- Fixes #1258 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1335)
=> SqlRs: [#1258] Fix for Reporting Services initialization

CHANGELOG.md, DSCResources/MSFT_SqlRS/MSFT_SqlRS.psm1, Modules/DscResource.Common/DscResource.Common.psm1, Tests/Integration/MSFT_SqlRS.Integration.Tests.ps1, Tests/Integration/MSFT_SqlRS.config.ps1, Tests/Unit/DscResource.Common.Tests.ps1, Tests/Unit/MSFT_SqlRS.Tests.ps1, appveyor.yml
SqlRs resource is now aware of SSRS 2017. SSRS 2017 changes the Windows service name, Windows user account name that runs the service, supports a single SSRS instance (named 'SSRS')
- partially fixes #864 - it only handles initialisation (i.e. current behaviour), not installing SSRS 2017
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1261)
=> SqlRs: [#864] SSRS 2017 username, service instance names

CHANGELOG.md, DSCResources/MSFT_SqlAG/MSFT_SqlAG.psm1, DSCResources/MSFT_SqlAG/en-US/MSFT_SqlAG.strings.psd1, DSCResources/MSFT_SqlAGReplica/MSFT_SqlAGReplica.psm1, DSCResources/MSFT_SqlAGReplica/en-US/MSFT_SqlAGReplica.strings.psd1, Modules/DscResource.Common/en-US/DscResource.Common.strings.psd1, Modules/DscResource.Common/sv-SE/DscResource.Common.strings.psd1, Tests/Unit/MSFT_SqlAG.Tests.ps1, Tests/Unit/MSFT_SqlAGReplica.Tests.ps1
- Changes to SqlAG
- Added en-US localization.
- Added en-US localization.
n/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1365)
=> SqlServerDsc: Fix last localization

CHANGELOG.md, Tests/Unit/MSFT_SqlAgentOperator.Tests.ps1
Fix typo in test it block
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1371)
=> SqlAgentOperator: Fix typo in test 

CHANGELOG.md
- Update change log after recent merges.
n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1373)
=> SqlServerDsc: Update CHANGELOG.md

CHANGELOG.md, Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1, Modules/SqlServerDsc.Common/en-US/SqlServerDsc.Common.strings.psd1, Modules/SqlServerDsc.Common/sv-SE/SqlServerDsc.Common.strings.psd1, Tests/Unit/SqlServerDsc.Common.Tests.ps1
- Changes to helper function Connect-SQL
- The function now make it more clear that when using the parameter
`SetupCredential` is impersonates that user, and by default it does
not impersonates a user but uses the credential that the resource
is run as (for example the built-in credential parameter
`PsDscRunAsCredential`).
- Added parameter alias `-DatabaseCredential` for the parameter
`-SetupCredential`.
This PR partly continues the work that @kungfu71186 started in PR https://github.com/PowerShell/SqlServerDsc/pull/1356.
Helps to eventually close PR #1356.
--- …
=> SqlServerDsc.Common: Updates Connect-SQL

CHANGELOG.md, DSCResources/MSFT_SqlServerSecureConnection/MSFT_SqlServerSecureConnection.psm1, Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1, Tests/Unit/MSFT_SqlServerSecureConnection.Tests.ps1
- Changes to SqlServerSecureConnection
- Forced $Thumbprint to lowercase to fix issue#1350
- Fixes #1350 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1376)
=> SqlServerSecureConnection: Fix issue #1350

Tests/Unit/SqlServerDsc.Common.Tests.ps1
- Fixes #1306
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1384)
=> Restart-SqlService: Regression test for issues #1306

CHANGELOG.md, DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.psm1
Picked this issue up when testing new PSSA rules.
- Fixes #1387 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1388)
=> Fix minor style violation in SqlSetup - Fixes #1387

CHANGELOG.md, Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1, Modules/SqlServerDsc.Common/en-US/SqlServerDsc.Common.strings.psd1, Modules/SqlServerDsc.Common/sv-SE/SqlServerDsc.Common.strings.psd1, Tests/Unit/SqlServerDsc.Common.Tests.ps1
- Changes to helper function Connect-SQL
- Connect-SQL now uses parameter sets to more intuitive evaluate that
the correct parameters are used in different scenarios (issue #1403).
- Fixes #1403 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1410)
=> SqlServerDsc: Changes to helper function Connect-SQL

CHANGELOG.md, DSCResources/MSFT_SqlAG/MSFT_SqlAG.psm1, DSCResources/MSFT_SqlAGReplica/MSFT_SqlAGReplica.psm1, DSCResources/MSFT_SqlDatabaseDefaultLocation/MSFT_SqlDatabaseDefaultLocation.psm1, Tests/TestHelpers/CommonTestHelper.psm1, Tests/Unit/MSFT_SqlAGReplica.Tests.ps1, Tests/Unit/MSFT_SqlScriptQuery.Tests.ps1, Tests/Unit/SqlServerDsc.Common.Tests.ps1, Tests/Unit/Stubs/Write-ModuleStubFile.ps1
- Fix keywords to lower-case to align with guideline.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1425)
=> SqlServerDsc: Fix keywords to lower-case to align with guideline

CHANGELOG.md, DSCResources/MSFT_SqlAlias/MSFT_SqlAlias.psm1, DSCResources/MSFT_SqlRS/MSFT_SqlRS.psm1, DSCResources/MSFT_SqlServerConfiguration/MSFT_SqlServerConfiguration.psm1, DSCResources/MSFT_SqlServerNetwork/MSFT_SqlServerNetwork.psm1
- Fix keywords to have space before a parenthesis to align with guideline
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1426)
=> SqlServerDsc: Fix keywords to have space before a parenthesis

CHANGELOG.md, DSCResources/MSFT_SqlAG/MSFT_SqlAG.psm1, DSCResources/MSFT_SqlAGReplica/MSFT_SqlAGReplica.psm1, DSCResources/MSFT_SqlAlias/MSFT_SqlAlias.psm1, DSCResources/MSFT_SqlDatabaseDefaultLocation/MSFT_SqlDatabaseDefaultLocation.psm1, DSCResources/MSFT_SqlRS/MSFT_SqlRS.psm1, DSCResources/MSFT_SqlServerConfiguration/MSFT_SqlServerConfiguration.psm1, DSCResources/MSFT_SqlServerNetwork/MSFT_SqlServerNetwork.psm1, SqlServerDsc.psd1, Tests/TestHelpers/CommonTestHelper.psm1, Tests/Unit/MSFT_SqlAGReplica.Tests.ps1, Tests/Unit/MSFT_SqlScriptQuery.Tests.ps1, Tests/Unit/SqlServerDsc.Common.Tests.ps1, Tests/Unit/Stubs/Write-ModuleStubFile.ps1
Releasing version 13.2.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1429)
=> Release of version 13.2.0.0 of SqlServerDsc

CHANGELOG.md, DSCResources/MSFT_SqlSetup/en-US/MSFT_SqlSetup.strings.psd1
Fixes typo in strings 
- Fixes issue #1419 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sqlserverdsc/1438)
=> SqlSetup: Fixes typo in strings file 

CHANGELOG.md, GitVersion.yml
- Ignore commit in `GitVersion.yml` to force the correct initial release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1456)
=> Ignore commit to force the correct initial release

CHANGELOG.md, build.ps1, tests/Unit/MSFT_SqlDatabaseRole.Tests.ps1
- SqlServerDsc
- Update build.ps1 from latest template.
- SqlDatabaseRole
- Update unit test to have the correct description on the `Describe`-block
for the test of `Set-TargetResource`.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1458)
=> SqlDatabaseRole: Correct description on the Describe-block

CHANGELOG.md, source/DSCResources/MSFT_SqlDatabase/MSFT_SqlDatabase.psm1, source/DSCResources/MSFT_SqlDatabase/MSFT_SqlDatabase.schema.mof, source/DSCResources/MSFT_SqlDatabase/en-US/MSFT_SqlDatabase.strings.psd1, source/Examples/Resources/SqlDatabase/1-CreateDatabase.ps1, tests/Unit/MSFT_SqlDatabase.Tests.ps1
This PR implements the ability to manage the database compatibility level
- Fixes #1476 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1477)
=> Implemented the ability to manage the database compatibility level

.vscode/settings.json, CHANGELOG.md, CONTRIBUTING.md, RequiredModules.psd1, azure-pipelines.yml, build.ps1, build.yaml
- SqlServerDsc
- Update the CI pipeline files.
- Replaced Microsoft-hosted agent (build image) `win1803` with `windows-2019` (issue #1466).
- Fixes #1466
- Closes #1467
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1480)
=> SqlServerDsc: Replaced Microsoft-hosted agent win1803

CHANGELOG.md, azure-pipelines.yml
- SqlServerDsc
- Only run CI pipeline on branch `master` when there are changes to files
inside the `source` folder.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1491)
=> SqlServerDsc: Run CI on changes in source folder

CHANGELOG.md, source/DSCResources/MSFT_SqlAG/MSFT_SqlAG.psm1
- SqlAG
- Fix hashtables to align with style guideline (issue #1437).
- Fixes #1437
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1494)
=> SqlAG: Fix hashtables to align with style guideline

CHANGELOG.md, azure-pipelines.yml
- Now code coverage is reported to Codecov
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1515)
=> Now code coverage is reported to Codecov

CHANGELOG.md, source/DSCResources/DSC_SqlAgentAlert/DSC_SqlAgentAlert.psm1, source/DSCResources/DSC_SqlAgentFailsafe/DSC_SqlAgentFailsafe.psm1, source/DSCResources/DSC_SqlDatabaseOwner/DSC_SqlDatabaseOwner.psm1, source/DSCResources/DSC_SqlDatabasePermission/DSC_SqlDatabasePermission.psm1, source/DSCResources/DSC_SqlDatabaseRecoveryModel/DSC_SqlDatabaseRecoveryModel.psm1, source/DSCResources/DSC_SqlDatabaseUser/DSC_SqlDatabaseUser.psm1, source/DSCResources/DSC_SqlServerDatabaseMail/DSC_SqlServerDatabaseMail.psm1
- SqlServerDsc
- Updated to support DscResource.Common v0.7.1.
- Fixes #1522 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1523)
=> SqlServerDsc: Updated to support DscResource.Common v0.7.1

CHANGELOG.md, codecov.yml
- Add codecov.yml
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1526)
=> Fix codecov.yml

CHANGELOG.md, README.md, source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.psm1, source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.schema.mof, source/Examples/Resources/SqlSetup/1-InstallDefaultInstanceSingleServer.ps1, tests/Integration/DSC_SqlSetup.config.ps1, tests/Integration/README.md, tests/Unit/DSC_SqlSetup.Tests.ps1
- SqlSetup
- Added the properties `NpEnabled` and `TcpEnabled` (issue #1161).
- Fixes #1161
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1521)
=> SqlSetup: Added the properties NpEnabled and TcpEnabled

CHANGELOG.md, tests/Unit/DSC_SqlAGDatabase.Tests.ps1
- SQLAGDatabase: Unit tests failes intermittent
- Fixes #1532
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1533)
=> SqlAGDatabase: Unit tests fails intermittent

CHANGELOG.md, source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.psm1, tests/Unit/DSC_SqlSetup.Tests.ps1
- SqlSetup
- BREAKING CHANGE: Now if the parameter `AgtSvcStartupType` is not specified
in the configuration the resource will no longer by default add an
argument to `setup.exe` with a value of `Automatic` for the argument
`AGTSVCSTARTUPTYPE`. If the parameter `AgtSvcStartupType` is not specified
in the configuration there will be no setup argument added at all
(issue #464).
- Fixes #464
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1529)
=> BREAKING CHANGE: SqlSetup: Fix AgtSvcStartupType to not default to Automatic

CHANGELOG.md, source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1, tests/Unit/DSC_SqlAGDatabase.Tests.ps1
- SqlAGDatabase
- Fixed unit tests that failed intermittently when running unit tests
in PowerShell 7 (issue #1532).
- Minor code style issue changes.
- Fixes #1532
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1534)
=> SqlAGDatabase: Fixes unit tests that failed intermittently

CHANGELOG.md, README.md, source/DSCResources/DSC_SqlDatabase/DSC_SqlDatabase.schema.mof
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1531)
=> SqlDatabase: Update parameter documentation

CHANGELOG.md, build.yaml
- SqlServerDsc
- Fixing a problem with the latest ModuleBuild 1.7.0 that breaks the CI
pipeline.
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1545)
=> SqlServerDsc: Fix CI pipeline because of breaking change

CHANGELOG.md, README.md
- SqlServerDsc
- BREAKING CHANGE: Since the operating system Windows Server 2008 R2 and
the product SQL Server 2008 R2 has gone end-of-life the DSC resources
will no longer try to make the resource work with those. Moving forward,
and including this release, there might be code changes that will break
the resource on Windows Server 2008 R2 or with SQL Server 2008 R2 (issue #1514).
- Fixes #1514
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1537)
=> BREAKING CHANGE: SqlServerDsc: Moving away from Windows Server 2008 R2 and SQL Server 2008 R2

CHANGELOG.md, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1
- Added function `Import-Assembly` that can help import an assembly
into the PowerShell session.
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1549)
=> SqlServerDsc.Common: Fix comment-based help and remove debug code

CHANGELOG.md, README.md, source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.psm1, source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.schema.mof, source/Examples/Resources/SqlSetup/1-InstallDefaultInstanceSingleServer.ps1, tests/Integration/DSC_SqlSetup.Integration.Tests.ps1, tests/Integration/DSC_SqlSetup.config.ps1, tests/Unit/DSC_SqlSetup.Tests.ps1
- SqlSetup
- Added the property `UseEnglish` (issue #1473).
- Fixes #1473
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1547)
=> SqlSetup: Added the property UseEnglish

CHANGELOG.md, README.md, source/DSCResources/DSC_SqlScript/DSC_SqlScript.psm1, source/DSCResources/DSC_SqlScript/DSC_SqlScript.schema.mof, source/DSCResources/DSC_SqlScript/en-US/DSC_SqlScript.strings.psd1, source/DSCResources/DSC_SqlScriptQuery/DSC_SqlScriptQuery.psm1, source/DSCResources/DSC_SqlScriptQuery/DSC_SqlScriptQuery.schema.mof, source/DSCResources/DSC_SqlScriptQuery/en-US/DSC_SqlScriptQuery.strings.psd1, source/Examples/Resources/SqlScript/1-RunScriptUsingSQLAuthentication.ps1, source/Examples/Resources/SqlScript/2-RunScriptUsingWindowsAuthentication.ps1, source/Examples/Resources/SqlScript/3-RunScriptCompleteExample.ps1, source/Examples/Resources/SqlScriptQuery/1-RunScriptUsingSQLAuthentication.ps1, source/Examples/Resources/SqlScriptQuery/2-RunScriptUsingWindowsAuthentication.ps1, source/Examples/Resources/SqlScriptQuery/3-RunScriptCompleteExample.ps1, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psd1, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1, tests/Integration/DSC_SqlDatabaseUser.config.ps1, tests/Integration/DSC_SqlScript.Integration.Tests.ps1, tests/Integration/DSC_SqlScript.config.ps1, tests/Integration/DSC_SqlScriptQuery.Integration.Tests.ps1, tests/Integration/DSC_SqlScriptQuery.config.ps1, tests/Unit/DSC_SqlScript.Tests.ps1, tests/Unit/DSC_SqlScriptQuery.Tests.ps1, tests/Unit/SqlServerDsc.Common.Tests.ps1
- SqlScript
- BREAKING CHANGE: The parameter `ServerInstance` is replaced by the two
parameters `ServerName` and `InstanceName`. The parameter `InstanceName`
is the only one mandatory which fixes the issue that it was possible to
run the same script using different host names (issue #925).
- SqlScriptQuery
- BREAKING CHANGE: The parameter `ServerInstance` is replaced by the two
parameters `ServerName` and `InstanceName`. The parameter `InstanceName`
is the only one mandatory which fixes the issue that it was possible to
run the same query using different host names (issue #925).
- Fixes #925
---
This change …
=> BREAKING CHANGE: SqlScript/SqlScriptQuery: Replaces parameter ServerInstance

CHANGELOG.md, source/DSCResources/DSC_SqlDatabasePermission/DSC_SqlDatabasePermission.psm1, source/DSCResources/DSC_SqlDatabasePermission/en-US/DSC_SqlDatabasePermission.strings.psd1, tests/Integration/DSC_SqlDatabasePermission.config.ps1, tests/Unit/DSC_SqlDatabasePermission.Tests.ps1
- SqlDatabasePermission
- Now possible to change permissions for database user-defined roles
(e.g. public) and database application roles (issue #1498).
- Fixes #1498
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1558)
=> SqlDatabasePermission: Supports roles and application roles

CHANGELOG.md, README.md, source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.psm1, source/DSCResources/DSC_SqlSetup/en-US/DSC_SqlSetup.strings.psd1, source/DSCResources/DSC_SqlSetup/sv-SE/DSC_SqlSetup.strings.psd1, tests/Unit/DSC_SqlSetup.Tests.ps1
This PR creates support for a major version upgrade in SQL server, by evaluating the installed versus source path versions when the "upgrade" string has been set as the action.
Fixes #1561 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1562)
=> SqlSetup: Support SQL Server Major Version Upgrade

CHANGELOG.md, build.yaml
- Deploy task was updated with the correct name
None..
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1574)
=> SqlServerDsc: Deploy task was updated with the correct name

.github/CONTRIBUTING.md, CHANGELOG.md, CONTRIBUTING.md, source/DSCResources/DSC_SqlAGReplica/README.md, source/DSCResources/DSC_SqlRSSetup/DSC_SqlRSSetup.schema.mof, source/DSCResources/DSC_SqlRSSetup/en-US/DSC_SqlRSSetup.strings.psd1, source/WikiSource/CredentialOverview.md, source/WikiSource/gMSA.md, tests/Integration/README.md
- SqlServerDsc
- Remove the file `.github/CONTRIBUTION.md` as it no longer filled any
purpose as GitHub will find the CONTRIBUTION.md in the root folder
directly now (issue #1227).
- The documentation in CONTRIBUTING.md has been somewhat updated.
- Update documentation around design pattern for accounts that does not
use passwords (issue #378)
and (issue #1230).
- Updating the Integration Test README.md to better explain what the
integration tests for SqlSetup, SqlRSSetup, and SqlRS does (issue #1315).
- SqlAGReplica
- Update documentation with a requirement for SqlServer in certain circumstances
(issue #1033).
- SqlRSSetup
- There was a typo in the error message that was thrown when not passing
either the `Edition` or `ProductKey` that could be misleading (issue #1386).
- Updated the …
=> SqlServerDsc: Documentation updates

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, source/DSCResources/DSC_SqlAG/DSC_SqlAG.schema.mof, source/DSCResources/DSC_SqlAGReplica/DSC_SqlAGReplica.schema.mof, source/DSCResources/DSC_SqlAgentAlert/DSC_SqlAgentAlert.schema.mof, source/DSCResources/DSC_SqlAgentFailsafe/DSC_SqlAgentFailsafe.schema.mof, source/DSCResources/DSC_SqlAgentOperator/DSC_SqlAgentOperator.schema.mof, source/DSCResources/DSC_SqlDatabaseDefaultLocation/DSC_SqlDatabaseDefaultLocation.schema.mof, source/DSCResources/DSC_SqlEndpointPermission/DSC_SqlEndpointPermission.schema.mof, source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.schema.mof, source/DSCResources/DSC_SqlMemory/DSC_SqlMemory.schema.mof, source/DSCResources/DSC_SqlProtocolTcpIp/DSC_SqlProtocolTcpIp.schema.mof, source/DSCResources/DSC_SqlRSSetup/DSC_SqlRSSetup.schema.mof
- SqlServerDsc
- Minor changes too schema property descriptions to generate documentation
correctly.
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1577)
=> SqlServerDsc: Minor changes too schema property descriptions

CHANGELOG.md, source/DSCResources/DSC_SqlDatabaseObjectPermission/DSC_SqlDatabaseObjectPermission.schema.mof, source/DSCResources/DSC_SqlDatabaseObjectPermission/README.md
- SqlDatabaseObjectPermission
- Since the task that publish Wiki content was updated to correctly handle
embedded instances the duplicate documentation was removed from the
resource README.md, and some was added to the schema MOF parameter
descriptions (issue #1580).
- Fixes #1580
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1581)
=> SqlDatabaseObjectPermission: Update documentation

CHANGELOG.md, azure-pipelines.yml, source/DSCResources/DSC_SqlAGListener/DSC_SqlAGListener.psm1, source/DSCResources/DSC_SqlAgentAlert/DSC_SqlAgentAlert.psm1, source/DSCResources/DSC_SqlAgentOperator/DSC_SqlAgentOperator.psm1, source/DSCResources/DSC_SqlAlias/DSC_SqlAlias.psm1, source/DSCResources/DSC_SqlAlwaysOnService/DSC_SqlAlwaysOnService.psm1, source/DSCResources/DSC_SqlDatabase/DSC_SqlDatabase.psm1, source/DSCResources/DSC_SqlDatabaseObjectPermission/DSC_SqlDatabaseObjectPermission.psm1, source/DSCResources/DSC_SqlDatabasePermission/DSC_SqlDatabasePermission.psm1, source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1, source/DSCResources/DSC_SqlMaxDop/DSC_SqlMaxDop.psm1, source/DSCResources/DSC_SqlMemory/DSC_SqlMemory.psm1, source/DSCResources/DSC_SqlPermission/DSC_SqlPermission.psm1, source/DSCResources/DSC_SqlProtocol/DSC_SqlProtocol.psm1, source/DSCResources/DSC_SqlProtocolTcpIp/DSC_SqlProtocolTcpIp.psm1, source/DSCResources/DSC_SqlReplication/DSC_SqlReplication.psm1, source/DSCResources/DSC_SqlReplication/DSC_SqlReplication.schema.mof, source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1, source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1, source/DSCResources/DSC_SqlWindowsFirewall/DSC_SqlWindowsFirewall.psm1, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1, source/WikiSource/Home.md
- SqlServerDsc
- Updated comment-based help according to style guideline throughout
(issue #1500).
- Fixes #1500
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1587)
=> SqlServerDsc: Updated comment-based help (issue #1500)

CHANGELOG.md, source/DSCResources/DSC_SqlSetup/README.md
- SqlSetup
- Updated the documentation with the currently supported features (issue #1566).
- Fixes #1566
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1589)
=> SqlSetup: Updated the documentation

CHANGELOG.md, source/DSCResources/DSC_SqlSetup/README.md
- SqlSetup
- Update documentation around permissions in directory tree for Analysis Services
(issue #1443).
- Fixes #1443
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1590)
=> SqlSetup: Update documentation for Analysis Services

CHANGELOG.md, azure-pipelines.yml, codecov.yml
- SqlServerDsc
- Using Codecov carry forward flag because we are not sending code coverage
report on each commit.
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1588)
=> SqlServerDsc: Codecov carry forward flag

CHANGELOG.md, tests/TestHelpers/CommonTestHelper.psm1
- CommonTestHelper
- Minor style changes.
_This PR is more for testing if Codecov carries commits forward from an earlier commit when not all commits builds and uploads coverage._
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1593)
=> CommonTestHelper: Minor style changes

CHANGELOG.md, source/DSCResources/DSC_SqlDatabaseObjectPermission/DSC_SqlDatabaseObjectPermission.psm1, tests/Integration/DSC_SqlDatabaseObjectPermission.Integration.Tests.ps1, tests/Integration/DSC_SqlDatabaseObjectPermission.config.ps1
SqlDatabaseObjectPermission
Fix issue https://github.com/dsccommunity/SqlServerDsc/issues/1600
$permissionProperty.Actual has no Where method:
$permissionProperty.Actual | Get-Member -MemberType Method
TypeName: Microsoft.Management.Infrastructure.CimInstance#root/microsoft/Windows/DesiredStateConfiguration/DSC_Databa
seObjectPermission
Name MemberType Definition
Clone Method System.Object ICloneable.Clone()
Dispose Method void Dispose(), void IDisposable.Dispose()
Equals Method bool Equals(System.Object obj)
GetCimSessionComputerName Method string GetCimSessionComputerName()
GetCimSessionInstanceId Method guid GetCimSessionInstanceId()
GetHashCode Method int GetHashCode()
GetObjectData Method void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.R...
GetType …
=> SqlDatabaseObjectPermission:  Fixes the problem with missing method named 'Where'

.vscode/analyzersettings.psd1, .vscode/settings.json, CHANGELOG.md, source/DSCResources/DSC_SqlAG/DSC_SqlAG.psm1, source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1, source/DSCResources/DSC_SqlAgentAlert/DSC_SqlAgentAlert.psm1, source/DSCResources/DSC_SqlAgentFailsafe/DSC_SqlAgentFailsafe.psm1, source/DSCResources/DSC_SqlAgentOperator/DSC_SqlAgentOperator.psm1, source/DSCResources/DSC_SqlAlias/DSC_SqlAlias.psm1, source/DSCResources/DSC_SqlConfiguration/DSC_SqlConfiguration.psm1, source/DSCResources/DSC_SqlDatabase/DSC_SqlDatabase.psm1, source/DSCResources/DSC_SqlDatabaseObjectPermission/DSC_SqlDatabaseObjectPermission.psm1, source/DSCResources/DSC_SqlDatabasePermission/DSC_SqlDatabasePermission.psm1, source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1, source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1, source/DSCResources/DSC_SqlPermission/DSC_SqlPermission.psm1, source/DSCResources/DSC_SqlProtocol/DSC_SqlProtocol.psm1, source/DSCResources/DSC_SqlProtocolTcpIp/DSC_SqlProtocolTcpIp.psm1, source/DSCResources/DSC_SqlRS/DSC_SqlRS.psm1, source/DSCResources/DSC_SqlRSSetup/DSC_SqlRSSetup.psm1, source/DSCResources/DSC_SqlSecureConnection/DSC_SqlSecureConnection.psm1, source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.psm1, source/DSCResources/DSC_SqlWindowsFirewall/DSC_SqlWindowsFirewall.psm1, source/DSCResources/MSFT_SqlServerNetwork/MSFT_SqlServerNetwork.psm1, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1, tests/Integration/DSC_SqlSetup.Integration.Tests.ps1, tests/TestHelpers/CommonTestHelper.psm1, tests/Unit/DSC_SqlRSSetup.Tests.ps1, tests/Unit/DSC_SqlServiceAccount.Tests.ps1, tests/Unit/DSC_SqlSetup.Tests.ps1
- SqlServerDsc
- Updated code formatting using latest release of PSScriptAnalyzer.
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1611)
=> SqlServerDsc: Update code formatting

CHANGELOG.md, source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1, source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.schema.mof, source/DSCResources/DSC_SqlWaitForAG/README.md, source/DSCResources/DSC_SqlWaitForAG/en-US/DSC_SqlWaitForAG.strings.psd1, source/Examples/Resources/SqlWaitForAG/1-WaitForASingleClusterGroup.ps1, source/Examples/Resources/SqlWaitForAG/2-WaitForMultipleClusterGroups.ps1, tests/Unit/DSC_SqlWaitForAG.Tests.ps1
The resource now waits for the clustergroup to be made, and when clusterGroup is found,
it checks for the existance of the AvailibilityGroup.
Fixes  #1569
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1636)
=> BREAKING CHANGE: SqlWaitForAG: Evaluate so that Availability Group is available

CHANGELOG.md, source/SqlServerDsc.psd1
- SqlServerDsc
- The module manifest property `DscResourcesToExport` now updates automatically
using the pipeline.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1650)
=> SqlServerDsc: Property DscResourcesToExport updates automatically

CHANGELOG.md, source/DSCResources/DSC_SqlAG/DSC_SqlAG.psm1, source/DSCResources/DSC_SqlAGListener/DSC_SqlAGListener.psm1, source/DSCResources/DSC_SqlAGReplica/DSC_SqlAGReplica.psm1, source/DSCResources/DSC_SqlAgentAlert/DSC_SqlAgentAlert.psm1, source/DSCResources/DSC_SqlAgentFailsafe/DSC_SqlAgentFailsafe.psm1, source/DSCResources/DSC_SqlAgentOperator/DSC_SqlAgentOperator.psm1, source/DSCResources/DSC_SqlAlias/DSC_SqlAlias.psm1, source/DSCResources/DSC_SqlAlwaysOnService/DSC_SqlAlwaysOnService.psm1, source/DSCResources/DSC_SqlConfiguration/DSC_SqlConfiguration.psm1, source/DSCResources/DSC_SqlDatabase/DSC_SqlDatabase.psm1, source/DSCResources/DSC_SqlDatabasePermission/DSC_SqlDatabasePermission.psm1, source/DSCResources/DSC_SqlDatabaseRole/DSC_SqlDatabaseRole.psm1, source/DSCResources/DSC_SqlDatabaseUser/DSC_SqlDatabaseUser.psm1, source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1, source/DSCResources/DSC_SqlEndpointPermission/DSC_SqlEndpointPermission.psm1, source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1, source/DSCResources/DSC_SqlMemory/DSC_SqlMemory.psm1, source/DSCResources/DSC_SqlPermission/DSC_SqlPermission.psm1, source/DSCResources/DSC_SqlRS/DSC_SqlRS.psm1, source/DSCResources/DSC_SqlReplication/DSC_SqlReplication.psm1, source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1, source/DSCResources/DSC_SqlScript/DSC_SqlScript.psm1, source/DSCResources/DSC_SqlScriptQuery/DSC_SqlScriptQuery.psm1, source/DSCResources/DSC_SqlSecureConnection/DSC_SqlSecureConnection.psm1, source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1, source/DSCResources/DSC_SqlWindowsFirewall/DSC_SqlWindowsFirewall.psm1
- SqlServerDsc
- Removed `Export-ModuleMember` from DSC resource that still had it.
- Fixes #698
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1656)
=> SqlServerDsc: Removes Export-ModuleMember

CHANGELOG.md, CONTRIBUTING.md, GitVersion.yml, README.md, azure-pipelines.yml, build.yaml, codecov.yml, source/SqlServerDsc.psd1, source/WikiSource/CredentialOverview.md, source/WikiSource/Home.md
- SqlServerDsc
- Renamed `master` branch to `main` (issue #1660).
- Fixes #1660
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1663)
=> SqlServerDsc: Updated pipeline files to support change of master to main

.vscode/analyzersettings.psd1, CHANGELOG.md
- SqlServerDsc
- Removed a left-over comment in the file `analyzersettings.psd1`.
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1686)
=> SqlServerDsc: Removes a left-over comment

CHANGELOG.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1690)
=> SqlServerDsc: Minor fix to CHANGELOG.md

CHANGELOG.md, RequiredModules.psd1, build.yaml
- SqlServerDsc
- Changed to the new GitHub deploy tasks that is required for the latest
version of the Sampler module.
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1697)
=> SqlServerDsc: Use new GitHub deploy tasks in pipeline

CHANGELOG.md, azure-pipelines.yml, codecov.yml
- SqlServerDsc
- Updated pipeline configuration to align with the latest changes in Sampler.
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1703)
=> SqlServerDsc: Update pipeline configuration

CHANGELOG.md, tests/Integration/DSC_SqlSetup.Integration.Tests.ps1
- SqlSetup
- Fixed integration tests for SQL Server 2016 and SQL Server 2017.
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1705)
=> SqlSetup: Fix integration test

CHANGELOG.md, codecov.yml
- SqlServerDsc
- Update codecov.yml to support carry forward flags.
_This is in preparation for adding a future request to Codecov.io._
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1706)
=> SqlServerDsc: Fix codecov

CHANGELOG.md, source/DSCResources/DSC_SqlAgentAlert/README.md, source/DSCResources/DSC_SqlAgentFailsafe/README.md
- SqlAgentAlert
- Switched README file with SqlAgentFailsafe
- SqlAgentFailsafe
- Switched README file with SqlAgentAlert
Fixes #1709 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1710)
=> SqlAgentAlert & SqlAgentFailsafe: Fix swapped README files

CHANGELOG.md, tests/Integration/DSC_SqlRSSetup.Integration.Tests.ps1, tests/Integration/README.md
- SqlRSSetup
- Integration tests is now installing _Microsoft SQL Server 2019 Reporting Services_
(issue #1717).
- Fixes #1717
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1718)
=> SqlRSSetup: Installing SSRS 2019 in integration test

CHANGELOG.md, azure-pipelines.yml
- SqlServerDsc
- Updated pipeline to use the build worker image 'ubuntu-latest'.
- Switch to installing GitVersion using 'dotnet tool install' (issue #1732).
- Fixes #1732
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1733)
=> SqlServerDsc: Pipeline is using 'ubuntu-latest'

CHANGELOG.md, source/WikiSource/Home.md
add introduction and links to DSC technology
- Fixes #1734 
- [x ] Added an entry to the change log under the Unreleased section of the
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1740)
=> Wiki: add introduction to DSC to wiki

.github/workflows/stale.yml, CHANGELOG.md, tests/Integration/DSC_SqlProtocolTcpIp.config.ps1
- SqlServerDsc
- Bumped Stale task to v5 in the GitHub workflow.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1742)
=> Bump Stale to v5

CHANGELOG.md, build.yaml
- SqlServerDsc
- Remove duplicate deploy step (already present in `azure-pipelines.yml`).
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1767)
=> Remove duplicate deploy step

CHANGELOG.md, appveyor.yml, azure-pipelines.yml, tests/TestHelpers/CommonTestHelper.psm1
- SqlServerDsc
- Support for debugging of integration tests in AppVeyor.
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1774)
=> SqlServerDsc: Add Support for AppVeyor (for debugging purposes)

CHANGELOG.md, appveyor.yml, tests/Integration/README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1775)
=> Fix Integration test README

CHANGELOG.md, appveyor.yml
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1776)
=> Fix AppVeyor to run only for changes to source

CHANGELOG.md, source/Classes/020.SqlAudit.ps1
- SqlAudit
- Fix documentation that contain minor style errors.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1782)
=> SqlAudit: Fix documentation

.github/workflows/stale.yml, CHANGELOG.md
- SqlServerDsc
- Update Stale GitHub Action to v6.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1787)
=> Update Stale GitHub Action to v6

CHANGELOG.md, build.yaml
- SqlServerDsc
- Update to build module in separate folder under `output`.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1789)
=> SqlServerDsc: Update to build module in separate folder under `output`

.github/ISSUE_TEMPLATE/Command_proposal.yml, .github/ISSUE_TEMPLATE/Problem_with_command.yml, CHANGELOG.md
- SqlServerDsc
- New GitHub issue templates for proposing new public commands, proposing
an enhancement to an existing command, or having a problem with an existing
command.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1799)
=> SqlServerDsc: Add new issues templates

CHANGELOG.md, tests/Integration/DSC_SqlAgentAlert.Integration.Tests.ps1, tests/Integration/DSC_SqlAgentFailsafe.Integration.Tests.ps1, tests/Integration/DSC_SqlAgentOperator.Integration.Tests.ps1, tests/Integration/DSC_SqlAlwaysOnService.Integration.Tests.ps1, tests/Integration/DSC_SqlAudit.Integration.Tests.ps1, tests/Integration/DSC_SqlDatabase.Integration.Tests.ps1, tests/Integration/DSC_SqlDatabaseDefaultLocation.Integration.Tests.ps1, tests/Integration/DSC_SqlDatabaseMail.Integration.Tests.ps1, tests/Integration/DSC_SqlDatabaseObjectPermission.Integration.Tests.ps1, tests/Integration/DSC_SqlDatabasePermission.Integration.Tests.ps1, tests/Integration/DSC_SqlDatabaseUser.Integration.Tests.ps1, tests/Integration/DSC_SqlEndpoint.Integration.Tests.ps1, tests/Integration/DSC_SqlLogin.Integration.Tests.ps1, tests/Integration/DSC_SqlPermission.Integration.Tests.ps1, tests/Integration/DSC_SqlProtocol.Integration.Tests.ps1, tests/Integration/DSC_SqlProtocolTcpIp.Integration.Tests.ps1, tests/Integration/DSC_SqlRS.Integration.Tests.ps1, tests/Integration/DSC_SqlRSSetup.Integration.Tests.ps1, tests/Integration/DSC_SqlReplication.Integration.Tests.ps1, tests/Integration/DSC_SqlRole.Integration.Tests.ps1, tests/Integration/DSC_SqlScript.Integration.Tests.ps1, tests/Integration/DSC_SqlScriptQuery.Integration.Tests.ps1, tests/Integration/DSC_SqlSecureConnection.Integration.Tests.ps1, tests/Integration/DSC_SqlServiceAccount.Integration.Tests.ps1, tests/Integration/DSC_SqlSetup.Integration.Tests.ps1, tests/Integration/DSC_SqlWindowsFirewall.Integration.Tests.ps1
- SqlServerDsc
- Integration tests now wait for LCM after each It-block, not just at the
end of a Context-block. Hopefully this will mitigate some of the intermittent
errors we have seen when running the integration tests in the pipeline.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1806)
=> SqlServerDsc: Mitigate intermittent errors for integration tests

CHANGELOG.md, RequiredModules.psd1
- SqlServerDsc
- Use preview version of Pester to support the development of Pester as
this is a code base with a diverse set of tests thar can help catch
issues in Pester. If preview release of Pester prevents release we
should temporary shift back to stable.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1807)
=> SqlServerDsc: Use preview of Pester

CHANGELOG.md, source/Private/Assert-SetupActionProperties.ps1, tests/Unit/Private/Assert-SetupActionProperties.Tests.ps1
- Removed `Install` Keyword from the if condition present in the SqlServerDsc/source/Private/Assert-SetupActionProperties.ps1 
Script.
- Updated CHANGELOG.md Regarding appropriate Changes.
- Updated Assert-SetupActionProperties.Tests for updating the test cases.
- Fixes #1810
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1814)
=> `Install-SqlServerDsc`: AgtSvcAccount no longer needed for `Install`

.github/prquantifier.yaml, CHANGELOG.md
- SqlServerDsc
- Add the GitHub App _Pull Request Quantifier_ as an experiment to see if it
brings any value.
- Fixes #1811
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1827)
=> SqlServerDsc: Add GitHub App; Pull Request Quantifier

.github/prquantifier.yaml, CHANGELOG.md
- SqlServerDsc
- Updated thresholds, and label names and colors for the GitHub App _Pull Request Quantifier_.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sqlserverdsc/1829)
=> SqlServerDsc: Update quantifier label names and colors

CHANGELOG.md, source/Public/Uninstall-SqlDscServer.ps1, tests/Unit/Public/Uninstall-SqlDscServer.Tests.ps1
- `Uninstall-SqlDscServer`
- Now support the argument `SuppressPrivacyStatementNotice` ([issue #1809](https://github.com/dsccommunity/SqlServerDsc/issues/1809)).
- Fixes #1809
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1851)
=> `Uninstall-SqlDscServer`: Now support argument `SuppressPrivacyStatementNotice`

CHANGELOG.md, source/Classes/004.StartupParameters.ps1, source/DSCResources/DSC_SqlServiceAccount/DSC_SqlServiceAccount.psm1, source/Private/Assert-ManagedServiceType.ps1, source/Private/ConvertFrom-ManagedServiceType.ps1, source/Private/ConvertTo-ManagedServiceType.ps1, source/Public/Add-SqlDscTraceFlag.ps1, source/Public/Get-SqlDscManagedComputer.ps1, source/Public/Get-SqlDscManagedComputerService.ps1, source/Public/Get-SqlDscStartupParameter.ps1, source/Public/Get-SqlDscTraceFlag.ps1, source/Public/Remove-SqlDscTraceFlag.ps1, source/Public/Set-SqlDscStartupParameter.ps1, source/Public/Set-SqlDscTraceFlag.ps1, source/en-US/SqlServerDsc.strings.psd1, tests/Unit/Classes/StartupParameters.Tests.ps1, tests/Unit/Private/Assert-ManagedServiceType.Tests.ps1, tests/Unit/Private/ConvertFrom-ManagedServiceType.Tests.ps1, tests/Unit/Private/ConvertTo-ManagedServiceType.Tests.ps1, tests/Unit/Private/Invoke-SetupAction.Tests.ps1, tests/Unit/Public/Add-SqlDscTraceFlag.Tests.ps1, tests/Unit/Public/Get-SqlDscAudit.Tests.ps1, tests/Unit/Public/Get-SqlDscManagedComputer.Tests.ps1, tests/Unit/Public/Get-SqlDscManagedComputerService.Tests.ps1, tests/Unit/Public/Get-SqlDscStartupParameter.Tests.ps1, tests/Unit/Public/Get-SqlDscTraceFlag.Tests.ps1, tests/Unit/Public/Remove-SqlDscTraceFlag.Tests.ps1, tests/Unit/Public/Set-SqlDscStartupParameter.Tests.ps1, tests/Unit/Public/Set-SqlDscTraceFlag.Tests.ps1, tests/Unit/Stubs/SMO.cs
- SqlServerDsc
- The following private functions were added to the module (see comment-based
help for more information):
- `ConvertTo-ManagedServiceType`
- `ConvertFrom-ManagedServiceType`
- `Assert-ManagedServiceType`
- The following public functions were added to the module (see comment-based
help for more information):
- `Get-SqlDscManagedComputer`
- `Get-SqlDscManagedComputerService`
- `Get-SqlDscTraceFlag`
- `Add-SqlDscTraceFlag`
- `Remove-SqlDscTraceFlag`
- `Set-SqlDscTraceFlag`
- `Get-SqlDscStartupParameter`
- `Set-SqlDscStartupParameter`
None.
_In preparation for refactoring SqlTraceFlag to a class-based resource._
- - -
This …
=> SqlServerDsc: Add new commands to handle trace flags

CHANGELOG.md, tests/Unit/DSC_SqlRS.Tests.ps1
Clearer test name `When Reports virtual directory is different`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1874)
=> SqlRs: Clearer test naming

CHANGELOG.md, Resolve-Dependency.ps1
- SqlServerDsc
- Update pipeline script that is used to resolve dependencies.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1875)
=> SqlServerDsc: Fix pipeline script

CHANGELOG.md, tests/Integration/DSC_SqlAgentAlert.Integration.Tests.ps1, tests/Integration/DSC_SqlAgentFailsafe.Integration.Tests.ps1, tests/Integration/DSC_SqlAgentOperator.Integration.Tests.ps1, tests/Integration/DSC_SqlAlwaysOnService.Integration.Tests.ps1, tests/Integration/DSC_SqlAudit.Integration.Tests.ps1, tests/Integration/DSC_SqlDatabase.Integration.Tests.ps1, tests/Integration/DSC_SqlDatabaseDefaultLocation.Integration.Tests.ps1, tests/Integration/DSC_SqlDatabaseMail.Integration.Tests.ps1, tests/Integration/DSC_SqlDatabaseObjectPermission.Integration.Tests.ps1, tests/Integration/DSC_SqlDatabasePermission.Integration.Tests.ps1, tests/Integration/DSC_SqlDatabaseUser.Integration.Tests.ps1, tests/Integration/DSC_SqlEndpoint.Integration.Tests.ps1, tests/Integration/DSC_SqlLogin.Integration.Tests.ps1, tests/Integration/DSC_SqlPermission.Integration.Tests.ps1, tests/Integration/DSC_SqlProtocol.Integration.Tests.ps1, tests/Integration/DSC_SqlProtocolTcpIp.Integration.Tests.ps1, tests/Integration/DSC_SqlRS.Integration.Tests.ps1, tests/Integration/DSC_SqlRSSetup.Integration.Tests.ps1, tests/Integration/DSC_SqlRS_Default.Integration.Tests.ps1, tests/Integration/DSC_SqlReplication.Integration.Tests.ps1, tests/Integration/DSC_SqlRole.Integration.Tests.ps1, tests/Integration/DSC_SqlScript.Integration.Tests.ps1, tests/Integration/DSC_SqlScriptQuery.Integration.Tests.ps1, tests/Integration/DSC_SqlSecureConnection.Integration.Tests.ps1, tests/Integration/DSC_SqlServiceAccount.Integration.Tests.ps1, tests/Integration/DSC_SqlSetup.Integration.Tests.ps1, tests/Integration/DSC_SqlTraceFlag.Integration.Tests.ps1, tests/Integration/DSC_SqlWindowsFirewall.Integration.Tests.ps1
- SqlServerDsc
- Update the initializing header for all integration test to be equal to
the unit tests.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1864)
=> SqlServerDsc: Update initializing header integration test

CHANGELOG.md, azure-pipelines.yml, source/Public/Import-SqlDscPreferredModule.ps1, tests/Integration/DSC_SqlRS.Integration.Tests.ps1, tests/Integration/DSC_SqlRS.config.ps1, tests/Integration/DSC_SqlRS_Default.Integration.Tests.ps1, tests/Integration/DSC_SqlRS_Default.config.ps1
- SqlServerDsc
- Rename task jobs in Azure Pipelines (issue #1881).
- SqlRs
- Some code cleanup (issue #1881).
- Integration tests configuration names was renamed to better tell what
the configuration does (issue #1880).
- Fixes #1880
- Fixes #1881
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1887)
=> SqlServerDsc: Some maintenance resolving issues

CHANGELOG.md, source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.psm1, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1, source/Private/Assert-Feature.ps1, source/Private/Assert-SetupActionProperties.ps1, source/Private/Get-FileVersionInformation.ps1, source/Public/Test-SqlDscIsSupportedFeature.ps1, source/en-US/SqlServerDsc.strings.psd1, tests/Unit/DSC_SqlSetup.Tests.ps1, tests/Unit/Private/Assert-Feature.Tests.ps1, tests/Unit/Private/Assert-SetupActionProperties.Tests.ps1, tests/Unit/Private/Get-FileVersionInformation.Tests.ps1, tests/Unit/Public/Test-SqlDscIsSupportedFeature.Tests.ps1
- New public command:
- `Test-SqlDscIsSupportedFeature` - Evaluates if a feature is supported by a specific
Microsoft SQL Server major version. _This command must be extended with_
_a full list of when features were added and removed in each major_
_version to fully work_.
- New private commands:
- `Get-FileVersionInformation` - Returns the version information
for a file.
- `Assert-Feature` - Throws an exception if a feature is not supported
for a specific Microsoft SQL Server major version.
- Update private command:
- `Assert-SetupActionProperties` was changed to throw
an exception when a feature is not supported (uses `Assert-Feature`).
The private function indirectly used by the setup action commands.
- SqlSetup
- Update to support checking non-supported features using the command …
=> SqlSetup: Add better validation of features

CHANGELOG.md, source/DSCResources/DSC_SqlDatabaseMail/DSC_SqlDatabaseMail.psm1, tests/Integration/DSC_SqlDatabaseMail.Integration.Tests.ps1, tests/Integration/DSC_SqlDatabaseMail.config.ps1
- SqlDatabaseMail
- Update integration tests to verify multiple instances of SqlDatabaseMail
in the same configuration (issue #1871).
- Changed comparison logic to use `Compare-DscParameterState` (issue #1871).
- Return the correct profile name and mail server name from the current
state (issue #1871).
- Fixes #1871
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1922)
=> SqlDatabaseMail: Update integration tests to verify multiple instances

CHANGELOG.md, azure-pipelines.yml, source/Public/Get-SqlDscPreferredModule.ps1, source/Public/Import-SqlDscPreferredModule.ps1, source/en-US/SqlServerDsc.strings.psd1, tests/Unit/Public/Get-SqlDscPreferredModule.Tests.ps1, tests/Unit/Public/Import-SqlDscPreferredModule.Tests.ps1
- `Import-SqlDscPreferredModule`
- Better handle preferred module and re-uses logic in `Get-SqlDscPreferredModule`.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1921)
=> `Import-SqlDscPreferredModule`: Better handle preferred module

CHANGELOG.md, azure-pipelines.yml
- SqlServerDsc
- Temporary disable integration tests for dbatools.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1930)
=> SqlServerDsc: Temporary disable integration tests for dbatools

.vscode/settings.json, CHANGELOG.md, source/Private/Assert-SetupActionProperties.ps1, source/Private/Invoke-SetupAction.ps1, source/Public/Disable-SqlDscAudit.ps1, source/Public/Enable-SqlDscAudit.ps1, source/Public/Get-SqlDscAudit.ps1, source/Public/Get-SqlDscPreferredModule.ps1, source/Public/Get-SqlDscServerPermission.ps1, source/Public/Invoke-SqlDscQuery.ps1, source/Public/New-SqlDscAudit.ps1, source/Public/Remove-SqlDscAudit.ps1, source/Public/Repair-SqlDscServer.ps1, source/Public/Set-SqlDscAudit.ps1, source/Public/Set-SqlDscDatabasePermission.ps1, source/Public/Set-SqlDscServerPermission.ps1, source/Public/Test-SqlDscIsDatabasePrincipal.ps1
- SqlServerDsc
- Fix style changes in all private and public commands.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1936)
=> SqlServerDsc: clean up code in commands

CHANGELOG.md, source/DSCResources/DSC_SqlWindowsFirewall/DSC_SqlWindowsFirewall.psm1
This change avoids duplicating the Browser Firewall Rule for the AS feature which leads to an error in in subsequent Test-TargetResource runs.
- Fixes #1942 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1944)
=> SqlWindowsFirewall: Avoid Duplication of SQL Server Browser Firewall Rule

.github/workflows/code-analysis-built-module.yml, .github/workflows/code-analysis.yml, CHANGELOG.md, RequiredModules.psd1
- SqlServerDsc
- Running PSScriptAnalyzer on the built module (issue #1945).
- Fixes #1945
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1947)
=> SqlServerDsc: Running PSScriptAnalyzer on built module

.vscode/settings.json, CHANGELOG.md
- SqlServerDsc
- Fix a path in VS Code workspace settings to correctly use Script Analyzer on Linux and macOS.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1948)
=> SqlServerDsc: Fix workspace settings

CHANGELOG.md, source/Classes/020.SqlDatabasePermission.ps1, source/Classes/020.SqlPermission.ps1, source/DSCResources/DSC_SqlDatabaseMail/README.md, source/DSCResources/DSC_SqlDatabaseObjectPermission/README.md, source/DSCResources/DSC_SqlDatabaseUser/README.md, source/DSCResources/DSC_SqlEndpoint/README.md, source/DSCResources/DSC_SqlMaxDop/README.md, source/DSCResources/DSC_SqlMemory/README.md, source/DSCResources/DSC_SqlRSSetup/README.md, source/DSCResources/DSC_SqlSecureConnection/README.md, source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.schema.mof, source/DSCResources/DSC_SqlSetup/README.md, source/Examples/README.md, source/Examples/Resources/SqlRS/2-CustomConfiguration.ps1, source/Examples/Resources/SqlRS/3-CustomConfigurationUsingSsl.ps1, source/WikiSource/Home.md, tests/Integration/README.md
- SqlServerDsc
- Updating note comments throughout markdown and generated markdown.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1958)
=> SqlServerDsc: Updating note comments

.github/CODEOWNERS, .vscode/settings.json, CHANGELOG.md
- SqlServerDsc
- CODEOWNERS file was added to support automatically set reviewer.
- Fixes #1969 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1971)
=> SqlServerDsc: Add CODEOWNERS file

CHANGELOG.md, Resolve-Dependency.ps1, Resolve-Dependency.psd1, build.ps1
- SqlServerDsc
- Updated pipeline files to support PSResourceGet.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1972)
=> SqlServerDsc: Update pipeline files to support PSResourceGet

CHANGELOG.md, source/DSCResources/DSC_SqlDatabase/DSC_SqlDatabase.psm1, source/DSCResources/DSC_SqlDatabase/DSC_SqlDatabase.schema.mof
Add Version160 to CompatibilityLevel ValidateSet
None
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1973)
=> SqlDatabase: Add Version160 to CompatibilityLevel ValidateSet

CHANGELOG.md, Resolve-Dependency.psd1
- SqlServerDsc
- Bump PSResourceGet to v1.0.0 (used when resolving dependencies).
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1975)
=> SqlServerDsc: Bump PSResourceGet to v1.0.0

CHANGELOG.md, CONTRIBUTING.md, source/Classes/020.SqlDatabasePermission.ps1, source/Classes/020.SqlPermission.ps1, source/DSCResources/DSC_SqlDatabaseMail/README.md, source/DSCResources/DSC_SqlDatabaseObjectPermission/README.md, source/DSCResources/DSC_SqlEndpoint/README.md, source/DSCResources/DSC_SqlRSSetup/README.md, source/DSCResources/DSC_SqlSecureConnection/README.md, source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.schema.mof, source/DSCResources/DSC_SqlSetup/README.md, source/Examples/README.md, source/WikiSource/Home.md
- SqlServerDsc
- Update markdown highlights with newly supported keywords.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1978)
=> Fix markdown highlights

CHANGELOG.md, tests/Unit/Private/Assert-Feature.Tests.ps1
- `Assert-Feature`
- Fixed unit tests.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1979)
=> `Assert-Feature`: Fix unit tests

CHANGELOG.md, tests/Integration/DSC_SqlAgentOperator.Integration.Tests.ps1, tests/Integration/DSC_SqlAgentOperator.config.ps1
- SqlAgentOperator
- Integration test for changing e-mail address on an existing operator.
To verify part of issue #1990 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1991)
=> SqlAgentOperator: Modify integration test to change EmailAddress

CHANGELOG.md, tests/Integration/DSC_SqlAgentOperator.Integration.Tests.ps1, tests/Integration/DSC_SqlAgentOperator.config.ps1
- SqlAgentOperator
- Integration test for changing e-mail address on an existing operator.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1993)
=> SqlAgentOperator: Update integration test

CHANGELOG.md, RequiredModules.psd1, Resolve-Dependency.ps1, Resolve-Dependency.psd1, tests/Integration/DSC_SqlSetup.config.ps1
- SqlServer
- Updated pipeline files to support pre-releases with ModuleFast (when
resolving dependencies).
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1989)
=> SqlServerDsc: Update pipeline files

CHANGELOG.md, build.yaml
- SqlServerDsc
- Enabled NUnit results for HQRM tests.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1995)
=> SqlServerDsc: Enable NUnit results for HQRM tests

CHANGELOG.md, source/Classes/002.DatabasePermission.ps1, source/Classes/002.ServerPermission.ps1
- SqlDatabasePermission
- New method ToString() for making verbose output better.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/1997)
=> DatabasePermission/ServerPermission: Fix ToString() method

CHANGELOG.md, appveyor.yml, azure-pipelines.yml, source/Public/Connect-SqlDscDatabaseEngine.ps1, tests/Integration/Commands/Connect-SqlDscDatabaseEngine.Integration.Tests.ps1, tests/Integration/Commands/Install-SqlDscServer.Integration.Tests.ps1, tests/Integration/Commands/Prerequisites.Integration.Tests.ps1, tests/Integration/Commands/README.md, tests/Integration/Resources/README.md
- `Connect-SqlDscDatabaseEngine`
- Added integration test for the command.
- Comment-based help for parameter `LoginType` was corrected.
- An integration test now runs to test the command.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2030)
=> `Connect-SqlDscDatabaseEngine`: Added integration tests

CHANGELOG.md, source/Public/Connect-SqlDscDatabaseEngine.ps1, tests/Integration/Commands/Connect-SqlDscDatabaseEngine.Integration.Tests.ps1, tests/Integration/Commands/Install-SqlDscServer.Integration.Tests.ps1, tests/Integration/Commands/README.md
- `Connect-SqlDscDatabaseEngine`
- Update comment-based help with more examples.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2031)
=> `Connect-SqlDscDatabaseEngine`: Improve integration tests

CHANGELOG.md, azure-pipelines.yml, tests/Integration/Commands/Connect-SqlDscDatabaseEngine.Integration.Tests.ps1, tests/Integration/Commands/Install-SqlDscServer.Integration.Tests.ps1, tests/Integration/Commands/Uninstall-SqlDscServer.Integration.Tests.ps1
- `Uninstall-SqlDscServer`
- Added integration test for the command.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2033)
=> `Uninstall-SqlDscServer`: Add integration test

CHANGELOG.md, build.yaml
- SqlServerDsc
- Replaced inline task `Package_Wiki_Content` with the one now available
in the module _DscResource.DocGenerator_.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2034)
=> SqlServerDsc: Replaced inline task `Package_Wiki_Content`

CHANGELOG.md, RequiredModules.psd1, build.yaml, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1, source/WikiSource/Credential-overview.md, source/en-US/ServerPermission.strings.psd1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2050)
=> Fix localization hqrm

CHANGELOG.md, source/DSCResources/DSC_SqlRSSetup/DSC_SqlRSSetup.psm1, source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.psm1, source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1, tests/Unit/SqlServerDsc.Common.Tests.ps1
- Removed the function `Format-Path` in favor of the command
with the same name in the module _DscResource.Common_.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2084)
=> Replace `Format-Path` function

CHANGELOG.md, tests/Integration/Commands/Get-SqlDscRSSetupConfiguration.Integration.Tests.ps1, tests/Integration/Resources/DSC_SqlAgentAlert.Integration.Tests.ps1, tests/Integration/Resources/DSC_SqlAgentFailsafe.Integration.Tests.ps1, tests/Integration/Resources/DSC_SqlAgentOperator.Integration.Tests.ps1, tests/Integration/Resources/DSC_SqlAlwaysOnService.Integration.Tests.ps1, tests/Integration/Resources/DSC_SqlAudit.Integration.Tests.ps1, tests/Integration/Resources/DSC_SqlDatabase.Integration.Tests.ps1, tests/Integration/Resources/DSC_SqlDatabaseDefaultLocation.Integration.Tests.ps1, tests/Integration/Resources/DSC_SqlDatabaseMail.Integration.Tests.ps1, tests/Integration/Resources/DSC_SqlDatabaseObjectPermission.Integration.Tests.ps1, tests/Integration/Resources/DSC_SqlDatabasePermission.Integration.Tests.ps1, tests/Integration/Resources/DSC_SqlDatabaseUser.Integration.Tests.ps1, tests/Integration/Resources/DSC_SqlEndpoint.Integration.Tests.ps1, tests/Integration/Resources/DSC_SqlLogin.Integration.Tests.ps1, tests/Integration/Resources/DSC_SqlPermission.Integration.Tests.ps1, tests/Integration/Resources/DSC_SqlProtocol.Integration.Tests.ps1, tests/Integration/Resources/DSC_SqlProtocolTcpIp.Integration.Tests.ps1, tests/Integration/Resources/DSC_SqlRS.Integration.Tests.ps1, tests/Integration/Resources/DSC_SqlRS_Default.Integration.Tests.ps1, tests/Integration/Resources/DSC_SqlReplication.Integration.Tests.ps1, tests/Integration/Resources/DSC_SqlScript.Integration.Tests.ps1, tests/Integration/Resources/DSC_SqlScriptQuery.Integration.Tests.ps1, tests/Integration/Resources/DSC_SqlSecureConnection.Integration.Tests.ps1, tests/Integration/Resources/DSC_SqlServiceAccount.Integration.Tests.ps1, tests/Integration/Resources/DSC_SqlSetup.Integration.Tests.ps1, tests/Integration/Resources/DSC_SqlTraceFlag.Integration.Tests.ps1, tests/Integration/Resources/DSC_SqlWindowsFirewall.Integration.Tests.ps1
- SqlServerDsc
- Now integration tests will fail on an exception when the command `Test-DscConfiguration`
is run
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2088)
=> Integration test use `-ErrorAction 'Stop'` for `Test-DscConfiguration`

CHANGELOG.md, source/en-US/SqlAudit.strings.psd1, source/en-US/SqlPermission.strings.psd1, tests/Unit/Classes/DatabasePermission.Tests.ps1, tests/Unit/Classes/ServerPermission.Tests.ps1, tests/Unit/Classes/SqlAudit.Tests.ps1, tests/Unit/Classes/SqlDatabasePermission.Tests.ps1, tests/Unit/Classes/SqlPermission.Tests.ps1, tests/Unit/Classes/SqlReason.Tests.ps1, tests/Unit/Classes/SqlResourceBase.Tests.ps1, tests/Unit/Classes/StartupParameters.Tests.ps1
- SqlServerDsc
- Cleanup in unit tests for classes.
- Cleanup in localization string files.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2090)
=> SqlServerDsc: Cleanup in unit tests and localization files 

.github/copilot-instructions.md, CHANGELOG.md
- SqlServerDsc
- Refine and enhance clarity in Copilot instructions
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2093)
=> Refine and enhance clarity in Copilot instructions

.github/workflows/copilot-setup-steps.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2114)
=> Fix workflow name

.github/workflows/copilot-setup-steps.yml, CHANGELOG.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SqlServerDsc/2144)
=> Refactor environment variable configuration in Copilot setup workflow
